# LOAD VARIABLES, DFs AND FUNCTIONS

In [123]:
import pandas as pd
import re
import os
# %pip install openpyxl

In [124]:
def list_files_with_prefix(folder_path, prefix):
    try:
        folder = os.path.dirname(folder_path)

        matching_files = trinucleotide_counts[
            trinucleotide_counts["Path"].str.contains(folder) &
            trinucleotide_counts["Path"].str.contains(prefix)
        ]["Path"].tolist()

        matching_files.sort()
        return matching_files

    except Exception:
        return []

In [125]:
import pandas as pd
SP_0000 = pd.read_csv("SP_0000.csv")
SP_2020 = pd.read_csv("SP_2020.csv")
SP_2021 = pd.read_csv("SP_2021.csv")
SP_2022 = pd.read_csv("SP_2022.csv")
SP_2023 = pd.read_csv("SP_2023.csv")

SP_df = pd.concat([SP_0000, SP_2020, SP_2021, SP_2022, SP_2023], ignore_index=True).set_index("LY_SP")

SP_df = SP_df[SP_df.count().sort_values(ascending=False).index]

SP_df.to_csv("SP.csv")

SP_df

,LY,SP,SP_sample_number,SP_cultivar,SP_plot,SP_subplot,SP_block,SP_spray_fungicide,SP_density,SP_location,...,SP_parcel,SP_id_on_field_2022,SP_fertiliser,SP_distance_LY_T_2020,SP_grid_point_LY_T_2020,SP_grid_number_LY_T_2020,SP_scheme_LY_T_2020,SP_sampling_1_LY_T_2020,SP_edge_LY_T_2020,SP_sampling_0_LY_T_2020
LY_SP,,,,,,,,,,,,,,,,,,,,,
LY_X_0000__SP_000,LY_X_0000,SP_000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LY_Z_0000__SP_000,LY_Z_0000,SP_000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LY_T_2020__SP_001,LY_T_2020,SP_001,1,Elixir,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,diagonal,ext,1.0,large,A_2,right,A_3
LY_T_2020__SP_002,LY_T_2020,SP_002,2,Elixir,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,other,ext,2.0,large,C_10,other,C_10
LY_T_2020__SP_003,LY_T_2020,SP_003,3,Elixir,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,cross,ext,3.0,large,D_15,center,D_30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LY_T_2023__SP_104,LY_T_2023,SP_104,104,Kvium,104.0,9.0,3.0,False,300.0,T,...,NaN,NaN,NORMAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LY_T_2023__SP_105,LY_T_2023,SP_105,105,Sheriff,105.0,9.0,3.0,False,150.0,T,...,NaN,NaN,NORMAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LY_T_2023__SP_106,LY_T_2023,SP_106,106,Kvium,106.0,10.0,3.0,False,450.0,T,...,NaN,NaN,NORMAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LY_T_2023__SP_107,LY_T_2023,SP_107,107,Sheriff,107.0,9.0,3.0,False,300.0,T,...,NaN,NaN,NORMAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LY_T_2023__SP_108,LY_T_2023,SP_108,108,Sheriff,108.0,12.0,3.0,False,450.0,T,...,NaN,NaN,NORMAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
trinucleotide_counts=pd.read_csv("../trinucleotide_count_full.csv", sep="\t")
trinucleotide_counts["file"]=trinucleotide_counts["Path"].str.split("/").str[-1]
trinucleotide_counts["folder"]=trinucleotide_counts["Path"].str.split("/").str[-2]
trinucleotide_counts["read"]=trinucleotide_counts["file"].str.split("_R._").str[0]
trinucleotide_counts["read_fixed"]=trinucleotide_counts["read"].str.upper()
trinucleotide_counts

,Path,Reads,TTC,ACG,file,folder,read,read_fixed
0,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,19381,60,0,H-200622-16S-c-15-3_S105_L001_R2_001.fastq.gz,seq230707_DWDQH,H-200622-16S-c-15-3_S105_L001,H-200622-16S-C-15-3_S105_L001
1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,35772,105,0,A-230622-16S-c-59-1_S124_L001_R2_001.fastq.gz,seq230707_DWDQH,A-230622-16S-c-59-1_S124_L001,A-230622-16S-C-59-1_S124_L001
2,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,53481,0,53003,A-230622-16S-c-72-5_S182_L001_R1_001.fastq.gz,seq230707_DWDQH,A-230622-16S-c-72-5_S182_L001,A-230622-16S-C-72-5_S182_L001
3,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,22360,0,22096,H-200622-16S-c-17-2_S116_L001_R1_001.fastq.gz,seq230707_DWDQH,H-200622-16S-c-17-2_S116_L001,H-200622-16S-C-17-2_S116_L001
4,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,21283,0,21006,H-200622-16S-c-17-5_S119_L001_R1_001.fastq.gz,seq230707_DWDQH,H-200622-16S-c-17-5_S119_L001,H-200622-16S-C-17-5_S119_L001
...,...,...,...,...,...,...,...,...
15418,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,76263,36459,5,washed-1-S-240622-ITS-w-13-4_S241_L001_R2_001....,seq231107_RISO1,washed-1-S-240622-ITS-w-13-4_S241_L001,WASHED-1-S-240622-ITS-W-13-4_S241_L001
15419,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,85255,40806,0,washed-1-R-170622-ITS-w-D16_S88_L001_R2_001.fa...,seq231107_RISO1,washed-1-R-170622-ITS-w-D16_S88_L001,WASHED-1-R-170622-ITS-W-D16_S88_L001
15420,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,79254,38171,0,washed-1-control-A-230622-ITS-c-71-5_S270_L001...,seq231107_RISO1,washed-1-control-A-230622-ITS-c-71-5_S270_L001,WASHED-1-CONTROL-A-230622-ITS-C-71-5_S270_L001
15421,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,92065,42170,1,washed-1-R-140622-ITS-w-C9_S57_L001_R2_001.fas...,seq231107_RISO1,washed-1-R-140622-ITS-w-C9_S57_L001,WASHED-1-R-140622-ITS-W-C9_S57_L001
15422,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,92065,2,28,washed-1-R-140622-ITS-w-C9_S57_L001_R1_001.fas...,seq231107_RISO1,washed-1-R-140622-ITS-w-C9_S57_L001,WASHED-1-R-140622-ITS-W-C9_S57_L001

In [127]:
# ON ERDA
# directory_path = '../sequencing_runs/'
# folders = [folder for folder in os.listdir(directory_path) if os.path.isdir(os.path.join(directory_path, folder))]
# df_folder_structure = pd.DataFrame(folders, columns=['dir_name'])
# df_folder_structure["full_path"] = df_folder_structure["dir_name"].apply(lambda x: os.path.abspath(os.path.join(directory_path, x)))
# df_folder_structure.shotgun("sequencing_runs_paths_ERDA.csv")
df_folder_structure=pd.read_csv("../sequencing_runs_paths_ERDA.csv")
df_folder_structure

,Unnamed: 0,dir_name,full_path
0,0,seq230707_DWDQH,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
1,1,seq230315_PF2CP,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
2,2,seq240222_RQS8X,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
3,3,seq240412_BRLUV,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
4,4,seq240424_T6U6R,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
5,5,seq231206_RISO2,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
6,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
7,7,seq230123_ISEQ2,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
8,8,seq221122_ISEQ1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
9,9,seq221219_K93FG,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
10,10,seq240508_LNERQ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
11,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
12,12,seq230220_ISEQ3,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
13,13,seq240826_X6DU5,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
14,14,seq231107_RISO1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
15,15,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
16,16,seq240209_KSVAZ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
17,17,seq230526_LQJXR,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
18,18,seq240719_NR8NI,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
19,19,seq221216_ISEQ4,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
20,20,seq240710_DR8PG,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
21,21,seq240515_E8KTD,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
22,22,seq240820_C6WGP,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...
23,23,seq231107_RISO1_error,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...

In [ ]:
washed_file  = "../EXCEL_FILES/washed_individually_metadata_DK_20260306.xlsx"
crushed_file = "../EXCEL_FILES/crushed_metadata_20260227.xlsx"
shotgun_file = "../EXCEL_FILES/shotgun_metadata_20250117.xlsx"

metadata_2020_washed_amplicon = pd.read_excel(washed_file, sheet_name="2020").rename(columns={"sample-ID": "bio_sample_ID"}) # DONE
metadata_2021_crushed_amplicon = pd.read_excel(crushed_file, sheet_name="2021") # DONE
metadata_2022_crushed_amplicon = pd.read_excel(crushed_file, sheet_name="2022") # DONE

metadata_2022_washed_shotgun = pd.read_excel(shotgun_file, sheet_name="2022_shotgun") # DONE
metadata_2022_washed_amplicon = pd.read_excel(washed_file, sheet_name="2022").rename(columns={"sample_ID": "bio_sample_ID"}) # DONE
metadata_2022_washed_shotgun_amplicon = pd.read_excel(shotgun_file, sheet_name="2022_amplicons") # DONE

metadata_2023_crushed_amplicon_16S = pd.read_excel(crushed_file, sheet_name="2023_16S") # DONE
metadata_2023_crushed_amplicon_ITS = pd.read_excel(crushed_file, sheet_name="2023_ITS")

metadata_2023_washed_shotgun_amplicon = pd.read_excel(shotgun_file, sheet_name="2023_amplicons")
metadata_2023_washed_shotgun = pd.read_excel(shotgun_file, sheet_name="2023_shotgun")

metadata_control_crushed_amplicon = pd.read_excel(crushed_file, sheet_name="seq_controls")


metadata_tables = [ metadata_2020_washed_amplicon, metadata_2021_crushed_amplicon, metadata_2022_crushed_amplicon, metadata_2022_washed_shotgun, metadata_2022_washed_amplicon, metadata_2022_washed_shotgun_amplicon, metadata_2023_crushed_amplicon_16S, metadata_2023_crushed_amplicon_ITS, metadata_2023_washed_shotgun_amplicon, metadata_2023_washed_shotgun, metadata_control_crushed_amplicon]
sources = [
    ("2020", "WASHED",  "amplicon"),
    ("2021", "CRUSHED", "amplicon"),
    ("2022", "CRUSHED", "amplicon"),
    ("2022", "WASHED",  "shotgun"),
    ("2022", "WASHED",  "amplicon"),
    ("2022", "WASHED",  "shotgun_amplicon"),
    ("2023", "CRUSHED", "amplicon"),
    ("2023", "CRUSHED", "amplicon"),
    ("2023", "WASHED",  "shotgun_amplicon"),
    ("2023", "WASHED",  "shotgun"),
    ("control", "CRUSHED", "amplicon"),]

for df, (year, leaf, lib) in zip(metadata_tables, sources):
    df["YEAR"] = year
    df["LEAF_PROTOCOL"] = leaf
    df["LIBRARY_PREPARATION"] = lib
    # df.dropna(axis=1, how="all", inplace=True)

# BLOCKS

## WASH AMP 2020

In [7]:
metadata_2020_washed_amplicon.columns = metadata_2020_washed_amplicon.columns.str.replace('-', '_')
metadata_2020_washed_amplicon.columns = metadata_2020_washed_amplicon.columns.str.replace('worrewt', 'correct')

# metadata_2020_washed_amplicon[metadata_2020_washed_amplicon["run_ID"]=="RISO2"]
# metadata_2020_washed_amplicon["run_ID"]=metadata_2020_washed_amplicon["run_ID"].str.replace("RIS2", "RISO2")
print("Number of samples: "  + str(len(metadata_2020_washed_amplicon)))
print("Number of sequence runs: "  + str(metadata_2020_washed_amplicon["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2020_washed_amplicon["run_ID"].value_counts()

Number of samples: 108
Number of sequence runs: 108

Number of sequence runs per folder:

run_ID
seq230714_FWU63    54
seq230710_GW4I8    54
Name: count, dtype: int64

In [8]:
# Merge two DataFrames (metadata_2020_washed_amplicon and df_folder_structure) 
# on the columns "run_ID" and "dir_name" respectively, keeping all rows from metadata_2020_washed_amplicon 
# (left join).

metadata_2020_washed_amplicon_full = metadata_2020_washed_amplicon.merge(
    df_folder_structure, left_on="run_ID", right_on="dir_name", how="left"
)

# Filter rows to keep only those where the "seq_sample_ID" column is not NaN.
metadata_2020_washed_amplicon_full = metadata_2020_washed_amplicon_full[
    metadata_2020_washed_amplicon_full["seq_sample_ID"].notna()
]

# Create a new column "suggested_correct_seq_sample_ID". If "correct_seq_sample_ID" is NaN,
# it will use the value from "seq_sample_ID", otherwise, it uses "correct_seq_sample_ID".
metadata_2020_washed_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_2020_washed_amplicon_full['correct_seq_sample_ID'].fillna(
        metadata_2020_washed_amplicon_full['seq_sample_ID']
    )

# Replace underscores with hyphens and remove the prefix "washed-1-" from the values in 
# the "suggested_correct_seq_sample_ID" column.
metadata_2020_washed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2020_washed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-")
metadata_2020_washed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2020_washed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("washed-1-", "")

# Sort the DataFrame by the "run_ID" column in ascending order.
metadata_2020_washed_amplicon_full = metadata_2020_washed_amplicon_full.sort_values("run_ID")

# End of code, the resulting DataFrame is assigned to metadata_2020_washed_amplicon_full.
metadata_2020_washed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,grid_number,grid_point,distance,scheme,sampling_0,...,rund_ID_2nd,note,correct_seq_sample_ID,YEAR,LEAF_PROTOCOL,LIBRARY_PREPARATION,Unnamed: 0,dir_name,full_path,suggested_correct_seq_sample_ID
107,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,T-2020-ITS-w-P1-pos,2020,WASHED,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-w-P1-pos
77,T-030620-w-24,NaN,24.0,2020-06-03,deep,26.0,middle,other,medium,C_10,...,NaN,NaN,T-030620-ITS-w-24,2020,WASHED,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-24
76,T-030620-w-23,NaN,23.0,2020-06-03,deep,25.0,middle,other,medium,C_10,...,NaN,NaN,T-030620-ITS-w-23,2020,WASHED,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-23
75,T-030620-w-22,NaN,22.0,2020-06-03,deep,24.0,middle,other,medium,C_10,...,NaN,NaN,T-030620-ITS-w-22,2020,WASHED,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-22
74,T-030620-w-21,NaN,21.0,2020-06-03,deep,23.0,middle,cross,large,C_10,...,NaN,NaN,T-030620-ITS-w-21,2020,WASHED,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,T-030620-w-31,NaN,31.0,2020-06-03,deep,33.0,middle,other,medium,D_30,...,NaN,Alex_big,T-030620-16S-w-31,2020,WASHED,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-31
29,T-030620-w-30,NaN,30.0,2020-06-03,deep,32.0,middle,other,medium,D_30,...,NaN,NaN,T-030620-16S-w-30,2020,WASHED,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-30
28,T-030620-w-29,NaN,29.0,2020-06-03,deep,31.0,middle,other,medium,D_30,...,NaN,NaN,T-030620-16S-w-29,2020,WASHED,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-29
26,T-030620-w-27,NaN,27.0,2020-06-03,deep,29.0,middle,other,medium,D_30,...,NaN,NaN,T-030620-16S-w-27,2020,WASHED,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-27
53,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,T-2020-16S-w-P1-pos,2020,WASHED,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-w-P1-pos

In [ ]:
# Iterate over each row and print files
metadata_2020_washed_amplicon_full["forward_fq"]=""
metadata_2020_washed_amplicon_full["reverse_fq"]=""
metadata_2020_washed_amplicon_full["current_seq_sample_ID"]=""
metadata_2020_washed_amplicon_full["corrected_forward_fq"]=""
metadata_2020_washed_amplicon_full["corrected_reverse_fq"]=""

total_rows = len(metadata_2020_washed_amplicon_full)  # Get the total number of rows
n=0
for index, row in metadata_2020_washed_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID = row['suggested_correct_seq_sample_ID']

        # Check if the number of matching files is not equal to 2
        if len(matching_files) == 2:
            metadata_2020_washed_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2020_washed_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2020_washed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2020_washed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2020_washed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2

        else:
            prefix2 = prefix.replace("washed-1-", "").replace("-", "_")
            matching_files2 = list_files_with_prefix(folder_path, prefix2)

            if len(matching_files2) == 2:
                metadata_2020_washed_amplicon_full.loc[index, "forward_fq"] = matching_files2[0]
                metadata_2020_washed_amplicon_full.loc[index, "reverse_fq"] = matching_files2[1]
                ending_R1= "_S" + re.search(r"_S(\d+)", matching_files2[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files2[0])[1]
                ending_R2= "_S" + re.search(r"_S(\d+)", matching_files2[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files2[1])[1]
                metadata_2020_washed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files2[0].split("/")[-1])[0]
                metadata_2020_washed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
                metadata_2020_washed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2
            
        

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")
    
    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1

# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
metadata_2020_washed_amplicon_full

Processing... 100.00% complete
Processing complete!

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,grid_number,grid_point,distance,scheme,sampling_0,...,LIBRARY_PREPARATION,Unnamed: 0,dir_name,full_path,suggested_correct_seq_sample_ID,forward_fq,reverse_fq,current_seq_sample_ID,corrected_forward_fq,corrected_reverse_fq
107,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-w-P1-pos,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-pos,T-2020-ITS-w-P1-pos_S54_L001_R1_001.fastq.gz,T-2020-ITS-w-P1-pos_S54_L001_R2_001.fastq.gz
77,T-030620-w-24,NaN,24.0,2020-06-03,deep,26.0,middle,other,medium,C_10,...,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-24,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-24,T-030620-ITS-w-24_S24_L001_R1_001.fastq.gz,T-030620-ITS-w-24_S24_L001_R2_001.fastq.gz
76,T-030620-w-23,NaN,23.0,2020-06-03,deep,25.0,middle,other,medium,C_10,...,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-23,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-23,T-030620-ITS-w-23_S23_L001_R1_001.fastq.gz,T-030620-ITS-w-23_S23_L001_R2_001.fastq.gz
75,T-030620-w-22,NaN,22.0,2020-06-03,deep,24.0,middle,other,medium,C_10,...,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-22,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-22,T-030620-ITS-w-22_S22_L001_R1_001.fastq.gz,T-030620-ITS-w-22_S22_L001_R2_001.fastq.gz
74,T-030620-w-21,NaN,21.0,2020-06-03,deep,23.0,middle,cross,large,C_10,...,amplicon,11,seq230710_GW4I8,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-ITS-w-21,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-21,T-030620-ITS-w-21_S21_L001_R1_001.fastq.gz,T-030620-ITS-w-21_S21_L001_R2_001.fastq.gz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,T-030620-w-31,NaN,31.0,2020-06-03,deep,33.0,middle,other,medium,D_30,...,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-31,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-31,T-030620-16S-w-31_S31_L001_R1_001.fastq.gz,T-030620-16S-w-31_S31_L001_R2_001.fastq.gz
29,T-030620-w-30,NaN,30.0,2020-06-03,deep,32.0,middle,other,medium,D_30,...,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-30,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-30,T-030620-16S-w-30_S30_L001_R1_001.fastq.gz,T-030620-16S-w-30_S30_L001_R2_001.fastq.gz
28,T-030620-w-29,NaN,29.0,2020-06-03,deep,31.0,middle,other,medium,D_30,...,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-29,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-29,T-030620-16S-w-29_S29_L001_R1_001.fastq.gz,T-030620-16S-w-29_S29_L001_R2_001.fastq.gz
26,T-030620-w-27,NaN,27.0,2020-06-03,deep,29.0,middle,other,medium,D_30,...,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-030620-16S-w-27,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-27,T-030620-16S-w-27_S27_L001_R1_001.fastq.gz,T-030620-16S-w-27_S27_L001_R2_001.fastq.gz
53,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,amplicon,6,seq230714_FWU63,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-w-P1-pos,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-pos,T-2020-16S-w-P1-pos_S54_L001_R1_001.fastq.gz,T-2020-16S-w-P1-pos_S54_L001_R2_001.fastq.gz

In [10]:
# Define a list of columns to be moved to the end
columns_to_move = ["current_seq_sample_ID", "correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]

# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2020_washed_amplicon_full = metadata_2020_washed_amplicon_full[
    [col for col in metadata_2020_washed_amplicon_full.columns if col not in columns_to_move] + columns_to_move
]

# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_2020_washed_amplicon_full['forward_fq'] = metadata_2020_washed_amplicon_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_2020_washed_amplicon_full['reverse_fq'] = metadata_2020_washed_amplicon_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2020_washed_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2020_washed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2020_washed_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2020_washed_amplicon_full["ALREADY_CORRECT"] = metadata_2020_washed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2020_washed_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2020_washed_amplicon_full = metadata_2020_washed_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])

# Save the resulting DataFrame to a CSV file named 'test_metadata_15_11_2024.csv'
metadata_2020_washed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,grid_number,grid_point,distance,scheme,sampling_0,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
105,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-52_S52_L001_R1_001.fastq.gz,T-2020-ITS-c-52_S52_L001_R2_001.fastq.gz,not-a-sample-do-not-include_S52_L001_R1_001.fa...,not-a-sample-do-not-include_S52_L001_R2_001.fa...,T-2020-ITS-c-52,not_a_sample_do_not_include,not-a-sample-do-not-include,False,False
104,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-51_S51_L001_R1_001.fastq.gz,T-2020-ITS-c-51_S51_L001_R2_001.fastq.gz,not-a-sample-do-not-include_S51_L001_R1_001.fa...,not-a-sample-do-not-include_S51_L001_R2_001.fa...,T-2020-ITS-c-51,not_a_sample_do_not_include,not-a-sample-do-not-include,False,False
51,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-52_S52_L001_R1_001.fastq.gz,T-2020-16S-c-52_S52_L001_R2_001.fastq.gz,not-a-sample-do-not-include_S52_L001_R1_001.fa...,not-a-sample-do-not-include_S52_L001_R2_001.fa...,T-2020-16S-c-52,not_a_sample_do_not_include,not-a-sample-do-not-include,False,False
50,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-51_S51_L001_R1_001.fastq.gz,T-2020-16S-c-51_S51_L001_R2_001.fastq.gz,not-a-sample-do-not-include_S51_L001_R1_001.fa...,not-a-sample-do-not-include_S51_L001_R2_001.fa...,T-2020-16S-c-51,not_a_sample_do_not_include,not-a-sample-do-not-include,False,False
107,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-ITS-c-pos_S54_L001_R1_001.fastq.gz,T-2020-ITS-c-pos_S54_L001_R2_001.fastq.gz,T-2020-ITS-w-P1-pos_S54_L001_R1_001.fastq.gz,T-2020-ITS-w-P1-pos_S54_L001_R2_001.fastq.gz,T-2020-ITS-c-pos,T-2020-ITS-w-P1-pos,T-2020-ITS-w-P1-pos,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,T-030620-w-31,NaN,31.0,2020-06-03,deep,33.0,middle,other,medium,D_30,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-31_S31_L001_R1_001.fastq.gz,T-2020-16S-c-31_S31_L001_R2_001.fastq.gz,T-030620-16S-w-31_S31_L001_R1_001.fastq.gz,T-030620-16S-w-31_S31_L001_R2_001.fastq.gz,T-2020-16S-c-31,T-030620-16S-w-31,T-030620-16S-w-31,True,False
29,T-030620-w-30,NaN,30.0,2020-06-03,deep,32.0,middle,other,medium,D_30,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-30_S30_L001_R1_001.fastq.gz,T-2020-16S-c-30_S30_L001_R2_001.fastq.gz,T-030620-16S-w-30_S30_L001_R1_001.fastq.gz,T-030620-16S-w-30_S30_L001_R2_001.fastq.gz,T-2020-16S-c-30,T-030620-16S-w-30,T-030620-16S-w-30,True,False
28,T-030620-w-29,NaN,29.0,2020-06-03,deep,31.0,middle,other,medium,D_30,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-29_S29_L001_R1_001.fastq.gz,T-2020-16S-c-29_S29_L001_R2_001.fastq.gz,T-030620-16S-w-29_S29_L001_R1_001.fastq.gz,T-030620-16S-w-29_S29_L001_R2_001.fastq.gz,T-2020-16S-c-29,T-030620-16S-w-29,T-030620-16S-w-29,True,False
26,T-030620-w-27,NaN,27.0,2020-06-03,deep,29.0,middle,other,medium,D_30,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-27_S27_L001_R1_001.fastq.gz,T-2020-16S-c-27_S27_L001_R2_001.fastq.gz,T-030620-16S-w-27_S27_L001_R1_001.fastq.gz,T-030620-16S-w-27_S27_L001_R2_001.fastq.gz,T-2020-16S-c-27,T-030620-16S-w-27,T-030620-16S-w-27,True,False
53,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2020-16S-c-pos_S54_L001_R1_001.fastq.gz,T-2020-16S-c-pos_S54_L001_R2_001.fastq.gz,T-2020-16S-w-P1-pos_S54_L001_R1_001.fastq.gz,T-2020-16S-w-P1-pos_S54_L001_R2_001.fastq.gz,T-2020-16S-c-pos,T-2020-16S-w-P1-pos,T-2020-16S-w-P1-pos,True,False

In [ ]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]

metadata_2020_washed_amplicon_full_SP=metadata_2020_washed_amplicon_full.merge(pd.concat([SP_0000, SP_2020]), left_on="sample_number", right_on="SP_sample_number", how="left")#.to_csv("test.csv")

metadata_2020_washed_amplicon_full_SP["BS"] = (
    "BS_" +
    pd.to_datetime(metadata_2020_washed_amplicon_full_SP["sample_date"])
    .dt.strftime("%y%m%d") + "_" +metadata_2020_washed_amplicon_full_SP["LEAF_PROTOCOL"].str[0] + "_1")

metadata_2020_washed_amplicon_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2020_washed_amplicon_full_SP["DNA_ext_date"])
    .dt.strftime("%y%m%d"))

metadata_2020_washed_amplicon_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2020_washed_amplicon_full_SP["PCR2_date"])
    .dt.strftime("%y%m%d") + "_"+ metadata_2020_washed_amplicon_full_SP["amplicon"] )


# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2020_washed_amplicon_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2020_washed_amplicon_full_SP[id_col].eq("alex-control")
is_water = metadata_2020_washed_amplicon_full_SP[id_col].eq("Ultrapure-water")

control_mask = is_zymo | is_alex | is_water

# LY and SP fixed for all three
metadata_2020_washed_amplicon_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2020_washed_amplicon_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2020_washed_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2020_washed_amplicon_full_SP.loc[control_mask, "LY_SP"] = (metadata_2020_washed_amplicon_full_SP.loc[control_mask, "LY"] + "__" + metadata_2020_washed_amplicon_full_SP.loc[control_mask, "SP"])
# BS depends on which control
metadata_2020_washed_amplicon_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2020_washed_amplicon_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2020_washed_amplicon_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"

metadata_2020_washed_amplicon_full_SP["LY_SP_BS"]=metadata_2020_washed_amplicon_full_SP["LY"] + "__" + metadata_2020_washed_amplicon_full_SP["SP"]+ "__"  +metadata_2020_washed_amplicon_full_SP["BS"] 
metadata_2020_washed_amplicon_full_SP["LY_SP_BS_EX"]=metadata_2020_washed_amplicon_full_SP["LY_SP_BS"] + "__"  +metadata_2020_washed_amplicon_full_SP["EX"] 
metadata_2020_washed_amplicon_full_SP["LY_SP_BS_EX_LP"]=metadata_2020_washed_amplicon_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2020_washed_amplicon_full_SP["LP"] 


print(len(metadata_2020_washed_amplicon_full))
print(len(metadata_2020_washed_amplicon_full_SP))

metadata_2020_washed_amplicon_full_SP
# metadata_2020_washed_amplicon_full_SP[~metadata_2020_washed_amplicon_full_SP["SP"].isna()].groupby("SP").count()

108
108

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,grid_number,grid_point,distance,scheme,sampling_0,...,SP_sampling_0_LY_T_2020,SP_sampling_1_LY_T_2020,SP_edge_LY_T_2020,SP_cultivar,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
1,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
2,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230323_16S,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
3,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230323_16S,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
4,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ZYMCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,T-030620-w-31,NaN,31.0,2020-06-03,deep,33.0,middle,other,medium,D_30,...,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_031__BS_200603_W_1,LY_T_2020__SP_031__BS_200603_W_1__EX_210109,LY_T_2020__SP_031__BS_200603_W_1__EX_210109__L...
104,T-030620-w-30,NaN,30.0,2020-06-03,deep,32.0,middle,other,medium,D_30,...,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_030__BS_200603_W_1,LY_T_2020__SP_030__BS_200603_W_1__EX_210109,LY_T_2020__SP_030__BS_200603_W_1__EX_210109__L...
105,T-030620-w-29,NaN,29.0,2020-06-03,deep,31.0,middle,other,medium,D_30,...,D_30,D_15,center,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_029__BS_200603_W_1,LY_T_2020__SP_029__BS_200603_W_1__EX_210109,LY_T_2020__SP_029__BS_200603_W_1__EX_210109__L...
106,T-030620-w-27,NaN,27.0,2020-06-03,deep,29.0,middle,other,medium,D_30,...,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_027__BS_200603_W_1,LY_T_2020__SP_027__BS_200603_W_1__EX_210109,LY_T_2020__SP_027__BS_200603_W_1__EX_210109__L...
107,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ZYMCTL_X_0,EX_000000,LP_230323_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...

In [12]:
metadata_2020_washed_amplicon_full_SP.groupby("LY_SP_BS").first()

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,grid_number,grid_point,distance,scheme,sampling_0,...,SP_scheme_LY_T_2020,SP_sampling_0_LY_T_2020,SP_sampling_1_LY_T_2020,SP_edge_LY_T_2020,SP_cultivar,BS,EX,LP,LY_SP_BS_EX,LY_SP_BS_EX_LP
LY_SP_BS,,,,,,,,,,,,,,,,,,,,,
LY_T_2020__SP_001__BS_200603_W_1,T-030620-w-1,NaN,1.0,2020-06-03,deep,1.0,ext,diagonal,large,A_3,...,large,A_3,A_2,right,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_001__BS_200603_W_1__EX_210109,LY_T_2020__SP_001__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_002__BS_200603_W_1,T-030620-w-2,NaN,2.0,2020-06-03,deep,2.0,ext,other,large,C_10,...,large,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_002__BS_200603_W_1__EX_210109,LY_T_2020__SP_002__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_003__BS_200603_W_1,T-030620-w-3,NaN,3.0,2020-06-03,deep,3.0,ext,cross,large,D_30,...,large,D_30,D_15,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_003__BS_200603_W_1__EX_210109,LY_T_2020__SP_003__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_004__BS_200603_W_1,T-030620-w-4,NaN,4.0,2020-06-03,deep,4.0,ext,other,large,D_30,...,large,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_004__BS_200603_W_1__EX_210109,LY_T_2020__SP_004__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_005__BS_200603_W_1,T-030620-w-5,NaN,5.0,2020-06-03,deep,5.0,ext,diagonal,large,D_30,...,large,D_30,E_18,left,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_005__BS_200603_W_1__EX_210109,LY_T_2020__SP_005__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_006__BS_200603_W_1,T-030620-w-6,NaN,6.0,2020-06-03,deep,6.0,ext,other,large,D_30,...,large,D_30,E_18,left,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_006__BS_200603_W_1__EX_210109,LY_T_2020__SP_006__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_007__BS_200603_W_1,T-030620-w-7,NaN,7.0,2020-06-03,deep,7.0,middle,diagonal,large,D_30,...,large,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_007__BS_200603_W_1__EX_210109,LY_T_2020__SP_007__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_008__BS_200603_W_1,T-030620-w-8,NaN,8.0,2020-06-03,deep,8.0,middle,other,medium,D_30,...,medium,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_008__BS_200603_W_1__EX_210109,LY_T_2020__SP_008__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_009__BS_200603_W_1,T-030620-w-9,NaN,9.0,2020-06-03,deep,9.0,middle,other,medium,D_30,...,medium,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_009__BS_200603_W_1__EX_210109,LY_T_2020__SP_009__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_010__BS_200603_W_1,T-030620-w-10,NaN,10.0,2020-06-03,deep,10.0,middle,other,medium,A_3,...,medium,A_3,A_2,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_010__BS_200603_W_1__EX_210109,LY_T_2020__SP_010__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_011__BS_200603_W_1,T-030620-w-11,NaN,11.0,2020-06-03,deep,11.0,middle,cross,large,A_3,...,large,A_3,B_5,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_011__BS_200603_W_1__EX_210109,LY_T_2020__SP_011__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_012__BS_200603_W_1,T-030620-w-12,NaN,12.0,2020-06-03,deep,12.0,middle,diagonal,large,B_6,...,large,B_6,B_5,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_012__BS_200603_W_1__EX_210109,LY_T_2020__SP_012__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_013__BS_200603_W_1,T-030620-w-13,NaN,13.0,2020-06-03,deep,13.0,ext,other,large,B_6,...,large,B_6,B_5,right,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_013__BS_200603_W_1__EX_210109,LY_T_2020__SP_013__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_014__BS_200603_W_1,T-030620-w-14,NaN,14.0,2020-06-03,deep,14.0,ext,cross,large,B_6,...,large,B_6,B_5,right,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_014__BS_200603_W_1__EX_210109,LY_T_2020__SP_014__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_015__BS_200603_W_1,T-030620-w-15,NaN,15.0,2020-06-03,deep,15.0,middle,cross,large,B_6,...,large,B_6,B_5,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_015__BS_200603_W_1__EX_210109,LY_T_2020__SP_015__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_016__BS_200603_W_1,T-030620-w-16,NaN,16.0,2020-06-03,deep,16.0,middle,diagonal,medium,B_6,...,medium,B_6,C_10,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_016__BS_200603_W_1__EX_210109,LY_T_2020__SP_016__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_017__BS_200603_W_1,T-030620-w-17,NaN,17.0,2020-06-03,deep,18.0,middle,cross,small,B_6,...,small,B_6,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_017__BS_200603_W_1__EX_210109,LY_T_2020__SP_017__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_018__BS_200603_W_1,T-030620-w-18,NaN,18.0,2020-06-03,deep,20.0,middle,other,small,C_10,...,small,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_018__BS_200603_W_1__EX_210109,LY_T_2020__SP_018__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_019__BS_200603_W_1,T-030620-w-19,NaN,19.0,2020-06-03,deep,21.0,middle,other,medium,C_10,...,medium,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_019__BS_200603_W_1__EX_210109,LY_T_2020__SP_019__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_020__BS_200603_W_1,T-030620-w-20,NaN,20.0,2020-06-03,deep,22.0,middle,other,medium,C_10,...,medium,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_020__BS_200603_W_1__EX_210109,LY_T_2020__SP_020__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_021__BS_200603_W_1,T-030620-w-21,NaN,21.0,2020-06-03,deep,23.0,middle,cross,large,C_10,...,large,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_021__BS_200603_W_1__EX_210109,LY_T_2020__SP_021__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_022__BS_200603_W_1,T-030620-w-22,NaN,22.0,2020-06-03,deep,24.0,middle,other,medium,C_10,...,medium,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_022__BS_200603_W_1__EX_210109,LY_T_2020__SP_022__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_023__BS_200603_W_1,T-030620-w-23,NaN,23.0,2020-06-03,deep,25.0,middle,other,medium,C_10,...,medium,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_023__BS_200603_W_1__EX_210109,LY_T_2020__SP_023__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_024__BS_200603_W_1,T-030620-w-24,NaN,24.0,2020-06-03,deep,26.0,middle,other,medium,C_10,...,medium,C_10,C_10,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_024__BS_200603_W_1__EX_210109,LY_T_2020__SP_024__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_025__BS_200603_W_1,T-030620-w-25,NaN,25.0,2020-06-03,deep,27.0,middle,other,medium,C_10,...,medium,C_10,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_025__BS_200603_W_1__EX_210109,LY_T_2020__SP_025__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_026__BS_200603_W_1,T-030620-w-26,NaN,26.0,2020-06-03,deep,28.0,middle,other,medium,C_10,...,medium,C_10,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_026__BS_200603_W_1__EX_210109,LY_T_2020__SP_026__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_027__BS_200603_W_1,T-030620-w-27,NaN,27.0,2020-06-03,deep,29.0,middle,other,medium,D_30,...,medium,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_027__BS_200603_W_1__EX_210109,LY_T_2020__SP_027__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_028__BS_200603_W_1,T-030620-w-28,NaN,28.0,2020-06-03,deep,30.0,middle,other,medium,D_30,...,medium,D_30,D_15,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_028__BS_200603_W_1__EX_210109,LY_T_2020__SP_028__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_029__BS_200603_W_1,T-030620-w-29,NaN,29.0,2020-06-03,deep,31.0,middle,other,medium,D_30,...,medium,D_30,D_15,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_029__BS_200603_W_1__EX_210109,LY_T_2020__SP_029__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_030__BS_200603_W_1,T-030620-w-30,NaN,30.0,2020-06-03,deep,32.0,middle,other,medium,D_30,...,medium,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_030__BS_200603_W_1__EX_210109,LY_T_2020__SP_030__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_031__BS_200603_W_1,T-030620-w-31,NaN,31.0,2020-06-03,deep,33.0,middle,other,medium,D_30,...,medium,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_031__BS_200603_W_1__EX_210109,LY_T_2020__SP_031__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_032__BS_200603_W_1,T-030620-w-32,NaN,32.0,2020-06-03,deep,34.0,middle,other,medium,D_30,...,medium,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_032__BS_200603_W_1__EX_210109,LY_T_2020__SP_032__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_033__BS_200603_W_1,T-030620-w-33,NaN,33.0,2020-06-03,deep,36.0,middle,other,medium,D_30,...,medium,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_033__BS_200603_W_1__EX_210109,LY_T_2020__SP_033__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_034__BS_200603_W_1,T-030620-w-34,NaN,34.0,2020-06-03,deep,37.0,middle,other,small,D_30,...,small,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_034__BS_200603_W_1__EX_210109,LY_T_2020__SP_034__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_035__BS_200603_W_1,T-030620-w-35,NaN,35.0,2020-06-03,deep,39.0,middle,other,small,D_30,...,small,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_035__BS_200603_W_1__EX_210109,LY_T_2020__SP_035__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_036__BS_200603_W_1,T-030620-w-36,NaN,36.0,2020-06-03,deep,41.0,middle,other,small,D_30,...,small,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_036__BS_200603_W_1__EX_210109,LY_T_2020__SP_036__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_037__BS_200603_W_1,T-030620-w-37,NaN,37.0,2020-06-03,deep,47.0,middle,other,small,D_30,...,small,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_037__BS_200603_W_1__EX_210109,LY_T_2020__SP_037__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_038__BS_200603_W_1,T-030620-w-38,NaN,38.0,2020-06-03,deep,49.0,middle,other,small,D_30,...,small,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_038__BS_200603_W_1__EX_210109,LY_T_2020__SP_038__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_039__BS_200603_W_1,T-030620-w-39,NaN,39.0,2020-06-03,deep,51.0,middle,other,small,D_30,...,small,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_039__BS_200603_W_1__EX_210109,LY_T_2020__SP_039__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_040__BS_200603_W_1,T-030620-w-40,NaN,40.0,2020-06-03,deep,57.0,ext,cross,large,D_30,...,large,D_30,E_18,left,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_040__BS_200603_W_1__EX_210109,LY_T_2020__SP_040__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_041__BS_200603_W_1,T-030620-w-41,NaN,41.0,2020-06-03,deep,58.0,ext,other,large,D_30,...,large,D_30,E_18,left,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_041__BS_200603_W_1__EX_210109,LY_T_2020__SP_041__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_042__BS_200603_W_1,T-030620-w-42,NaN,42.0,2020-06-03,deep,59.0,middle,diagonal,large,D_30,...,large,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_042__BS_200603_W_1__EX_210109,LY_T_2020__SP_042__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_043__BS_200603_W_1,T-030620-w-43,NaN,43.0,2020-06-03,deep,60.0,middle,cross,large,D_30,...,large,D_30,E_18,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_043__BS_200603_W_1__EX_210109,LY_T_2020__SP_043__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_044__BS_200603_W_1,T-030620-w-44,NaN,44.0,2020-06-03,deep,61.0,middle,diagonal,large,D_30,...,large,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_044__BS_200603_W_1__EX_210109,LY_T_2020__SP_044__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_045__BS_200603_W_1,T-030620-w-45,NaN,45.0,2020-06-03,deep,62.0,ext,other,large,D_30,...,large,D_30,E_18,right,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_045__BS_200603_W_1__EX_210109,LY_T_2020__SP_045__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_046__BS_200603_W_1,T-030620-w-46,NaN,46.0,2020-06-03,deep,63.0,ext,diagonal,large,D_30,...,large,D_30,E_18,right,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_046__BS_200603_W_1__EX_210109,LY_T_2020__SP_046__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_047__BS_200603_W_1,T-030620-w-47,NaN,47.0,2020-06-03,deep,64.0,ext,other,large,D_30,...,large,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_047__BS_200603_W_1__EX_210109,LY_T_2020__SP_047__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_048__BS_200603_W_1,T-030620-w-48,NaN,48.0,2020-06-03,deep,65.0,ext,cross,large,D_30,...,large,D_30,E_18,center,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_048__BS_200603_W_1__EX_210109,LY_T_2020__SP_048__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_049__BS_200603_W_1,T-030620-w-49,NaN,49.0,2020-06-03,deep,66.0,ext,other,large,D_30,...,large,D_30,E_18,other,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_049__BS_200603_W_1__EX_210109,LY_T_2020__SP_049__BS_200603_W_1__EX_210109__L...
LY_T_2020__SP_050__BS_200603_W_1,T-030620-w-50,NaN,50.0,2020-06-03,deep,67.0,ext,diagonal,large,D_30,...,large,D_30,E_18,left,Elixir,BS_200603_W_1,EX_210109,LP_230428_ITS,LY_T_2020__SP_050__BS_200603_W_1__EX_210109,LY_T_2020__SP_050__BS_200603_W_1__EX_210109__L...
LY_X_0000__SP_000__BS_ALXCTL_X_0,alex-control,NaN,NaN,NaT,None,NaN,None,None,None,None,...,None,None,None,None,None,BS_ALXCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
LY_X_0000__SP_000__BS_ULWCTL_X_0,Ultrapure-water,NaN,NaN,NaT,None,NaN,None,None,None,None,...,None,None,None,None,None,BS_ULWCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
LY_X_0000__SP_000__BS_ZYMCTL_X_0,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,None,NaN,None,None,None,None,...,None,None,None,None,None,BS_ZYMCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...

In [13]:
metadata_2020_washed_amplicon_full_SP

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,grid_number,grid_point,distance,scheme,sampling_0,...,SP_sampling_0_LY_T_2020,SP_sampling_1_LY_T_2020,SP_edge_LY_T_2020,SP_cultivar,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
1,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
2,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230323_16S,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
3,alex-control,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ALXCTL_X_0,EX_000000,LP_230323_16S,LY_X_0000__SP_000__BS_ALXCTL_X_0,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ALXCTL_X_0__EX_000000__L...
4,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ZYMCTL_X_0,EX_000000,LP_230428_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,T-030620-w-31,NaN,31.0,2020-06-03,deep,33.0,middle,other,medium,D_30,...,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_031__BS_200603_W_1,LY_T_2020__SP_031__BS_200603_W_1__EX_210109,LY_T_2020__SP_031__BS_200603_W_1__EX_210109__L...
104,T-030620-w-30,NaN,30.0,2020-06-03,deep,32.0,middle,other,medium,D_30,...,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_030__BS_200603_W_1,LY_T_2020__SP_030__BS_200603_W_1__EX_210109,LY_T_2020__SP_030__BS_200603_W_1__EX_210109__L...
105,T-030620-w-29,NaN,29.0,2020-06-03,deep,31.0,middle,other,medium,D_30,...,D_30,D_15,center,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_029__BS_200603_W_1,LY_T_2020__SP_029__BS_200603_W_1__EX_210109,LY_T_2020__SP_029__BS_200603_W_1__EX_210109__L...
106,T-030620-w-27,NaN,27.0,2020-06-03,deep,29.0,middle,other,medium,D_30,...,D_30,D_15,other,Elixir,BS_200603_W_1,EX_210109,LP_230323_16S,LY_T_2020__SP_027__BS_200603_W_1,LY_T_2020__SP_027__BS_200603_W_1__EX_210109,LY_T_2020__SP_027__BS_200603_W_1__EX_210109__L...
107,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ZYMCTL_X_0,EX_000000,LP_230323_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...

## CRUSH 2021

In [14]:

print("Number of samples: "  + str(len(metadata_2021_crushed_amplicon)))
print("Number of sequence runs: "  + str(metadata_2021_crushed_amplicon["run_ID"].value_counts().sum()))
print()

print("Number of sequence runs per folder: ")
metadata_2021_crushed_amplicon["run_ID"].value_counts()

Number of samples: 350
Number of sequence runs: 350

Number of sequence runs per folder:

run_ID
seq230714_FWU63    149
seq230710_GW4I8    148
seq231107_RISO1     53
Name: count, dtype: int64

In [15]:
metadata_2021_crushed_amplicon_full=metadata_2021_crushed_amplicon.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="right")
metadata_2021_crushed_amplicon_full
metadata_2021_crushed_amplicon_full=metadata_2021_crushed_amplicon_full[metadata_2021_crushed_amplicon_full["seq_sample_ID"].notna()]
metadata_2021_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_2021_crushed_amplicon_full['correct_seq_sample_ID'].fillna(metadata_2021_crushed_amplicon_full['seq_sample_ID'])
metadata_2021_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2021_crushed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "").str.replace("16s", "16S")
metadata_2021_crushed_amplicon_full=metadata_2021_crushed_amplicon_full.sort_values("run_ID")

# ###### REMOVE WHEN RISO1 IS FIXED!!!!!
# metadata_2021_crushed_amplicon_full=metadata_2021_crushed_amplicon_full[metadata_2021_crushed_amplicon_full["run_ID"]!="seq231107_RISO1"]
# metadata_2021_crushed_amplicon_full

In [16]:
# Iterate over each row and print files
metadata_2021_crushed_amplicon_full["forward_fq"]=""
metadata_2021_crushed_amplicon_full["reverse_fq"]=""
metadata_2021_crushed_amplicon_full["current_seq_sample_ID"]=""
metadata_2021_crushed_amplicon_full["corrected_forward_fq"]=""
metadata_2021_crushed_amplicon_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2021_crushed_amplicon_full)  # Get the total number of rows

for index, row in metadata_2021_crushed_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        # Check if the number of matching files is not equal to 2
        if len(matching_files) == 2:
            metadata_2021_crushed_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2021_crushed_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2021_crushed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2021_crushed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2021_crushed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2
        else:
            # prefix2=prefix.replace("crushed-1-", "").replace("-", "_")
            prefix2=prefix.replace("washed-1-", "")#.replace("-", "_")
            matching_files2 = list_files_with_prefix(folder_path, prefix2)
    
            if len(matching_files2) == 2:
                metadata_2021_crushed_amplicon_full.loc[index, "forward_fq"] = matching_files2[0]
                metadata_2021_crushed_amplicon_full.loc[index, "reverse_fq"] = matching_files2[1]
                ending_R1= "_S" + re.search(r"_S(\d+)", matching_files2[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files2[0])[1]
                ending_R2= "_S" + re.search(r"_S(\d+)", matching_files2[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files2[1])[1]
                metadata_2021_crushed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files2[0].split("/")[-1])[0]
                metadata_2021_crushed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
                metadata_2021_crushed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2
            else:
                print(f"Files in {folder_path} containing {prefix2}:")
            
            # print(correct_seq_sample_ID)
            # print(prefix)
            # print()

        #         print(f" - {prefix}")
        #         print(f" - {matching_files}")

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1

# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

Files in /home/jovyan/work/CCRP/MATRIX/RawData/Microbiomics/Metagenomics/sequencing_runs/seq230714_FWU63 containing T-2021-P2-16S-c-pos_:
Files in /home/jovyan/work/CCRP/MATRIX/RawData/Microbiomics/Metagenomics/sequencing_runs/seq230714_FWU63 containing T-2021-P2-16S-c-neg_:
Files in /home/jovyan/work/CCRP/MATRIX/RawData/Microbiomics/Metagenomics/sequencing_runs/seq230714_FWU63 containing T-2021-16s-c-112_:
Processing... 100.00% complete
Processing complete!

In [17]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2021_crushed_amplicon_full = metadata_2021_crushed_amplicon_full[
    [col for col in metadata_2021_crushed_amplicon_full.columns if col not in columns_to_move] + columns_to_move
]
# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_2021_crushed_amplicon_full['forward_fq'] = metadata_2021_crushed_amplicon_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_2021_crushed_amplicon_full['reverse_fq'] = metadata_2021_crushed_amplicon_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2021_crushed_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2021_crushed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2021_crushed_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2021_crushed_amplicon_full["ALREADY_CORRECT"] = metadata_2021_crushed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2021_crushed_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2021_crushed_amplicon_full = metadata_2021_crushed_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2021_crushed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
311,T-150621-c-mystery,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-16S-c-mystery_S51_L001_R1_001.fastq.gz,T-2021-16S-c-mystery_S51_L001_R2_001.fastq.gz,washed-1-T-2021-16S-c-mystery_S51_L001_R1_001....,washed-1-T-2021-16S-c-mystery_S51_L001_R2_001....,T-2021-16S-c-mystery,NaN,washed-1-T-2021-16S-c-mystery,False,False
184,T-150621-c-118,NaN,118.0,2021-06-15,deep,4.0,118.0,10.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-ITS-c-118_S19_L001_R1_001.fastq.gz,T-2021-ITS-c-118_S19_L001_R2_001.fastq.gz,T-150621-ITS-c-118_S19_L001_R1_001.fastq.gz,T-150621-ITS-c-118_S19_L001_R2_001.fastq.gz,T-2021-ITS-c-118,T-150621-ITS-c-118,T-150621-ITS-c-118,True,False
212,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-P1-ITS-c-pos_S147_L001_R1_001.fastq.gz,T-2021-P1-ITS-c-pos_S147_L001_R2_001.fastq.gz,T-000021-ITS-c-P1-pos_S147_L001_R1_001.fastq.gz,T-000021-ITS-c-P1-pos_S147_L001_R2_001.fastq.gz,T-2021-P1-ITS-c-pos,T-000021-ITS-c-P1-pos,T-000021-ITS-c-P1-pos,True,False
211,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-P1-ITS-c-neg_S148_L001_R1_001.fastq.gz,T-2021-P1-ITS-c-neg_S148_L001_R2_001.fastq.gz,T-000021-ITS-c-P1-neg_S148_L001_R1_001.fastq.gz,T-000021-ITS-c-P1-neg_S148_L001_R2_001.fastq.gz,T-2021-P1-ITS-c-neg,T-000021-ITS-c-P1-neg,T-000021-ITS-c-P1-neg,True,False
210,T-150621-c-144,NaN,144.0,2021-06-15,deep,4.0,144.0,12.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-ITS-c-144_S45_L001_R1_001.fastq.gz,T-2021-ITS-c-144_S45_L001_R2_001.fastq.gz,T-150621-ITS-c-144_S45_L001_R1_001.fastq.gz,T-150621-ITS-c-144_S45_L001_R2_001.fastq.gz,T-2021-ITS-c-144,T-150621-ITS-c-144,T-150621-ITS-c-144,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,T-150621-c-113,NaN,113.0,2021-06-15,deep,4.0,113.0,10.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-16s-c-113_S19_L001_R1_001.fastq.gz,T-2021-16s-c-113_S19_L001_R2_001.fastq.gz,T-150621-16S-c-113_S19_L001_R1_001.fastq.gz,T-150621-16S-c-113_S19_L001_R2_001.fastq.gz,T-2021-16s-c-113,T-150621-16S-c-113,T-150621-16S-c-113,True,False
331,T-150621-c-114,NaN,114.0,2021-06-15,deep,4.0,114.0,10.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-16s-c-114_S20_L001_R1_001.fastq.gz,T-2021-16s-c-114_S20_L001_R2_001.fastq.gz,T-150621-16S-c-114_S20_L001_R1_001.fastq.gz,T-150621-16S-c-114_S20_L001_R2_001.fastq.gz,T-2021-16s-c-114,T-150621-16S-c-114,T-150621-16S-c-114,True,False
332,T-150621-c-115,NaN,115.0,2021-06-15,deep,4.0,115.0,10.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-16s-c-115_S21_L001_R1_001.fastq.gz,T-2021-16s-c-115_S21_L001_R2_001.fastq.gz,T-150621-16S-c-115_S21_L001_R1_001.fastq.gz,T-150621-16S-c-115_S21_L001_R2_001.fastq.gz,T-2021-16s-c-115,T-150621-16S-c-115,T-150621-16S-c-115,True,False
321,T-150621-c-104,NaN,104.0,2021-06-15,deep,3.0,104.0,9.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-16s-c-104_S10_L001_R1_001.fastq.gz,T-2021-16s-c-104_S10_L001_R2_001.fastq.gz,T-150621-16S-c-104_S10_L001_R1_001.fastq.gz,T-150621-16S-c-104_S10_L001_R2_001.fastq.gz,T-2021-16s-c-104,T-150621-16S-c-104,T-150621-16S-c-104,True,False
361,T-150621-c-144,NaN,144.0,2021-06-15,deep,4.0,144.0,12.0,NaN,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2021-16s-c-144_S50_L001_R1_001.fastq.gz,T-2021-16s-c-144_S50_L001_R2_001.fastq.gz,T-150621-16S-c-144_S50_L001_R1_001.fastq.gz,T-150621-16S-c-144_S50_L001_R2_001.fastq.gz,T-2021-16s-c-144,T-150621-16S-c-144,T-150621-16S-c-144,True,False

In [ ]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]
metadata_2021_crushed_amplicon_full_SP=metadata_2021_crushed_amplicon_full.merge(pd.concat([SP_0000, SP_2021]), left_on="sample_number", right_on="SP_sample_number", how="left")#.to_csv("test.csv")


metadata_2021_crushed_amplicon_full_SP["BS"] = (
    "BS_" +
    pd.to_datetime(metadata_2021_crushed_amplicon_full_SP["sample_date"])
    .dt.strftime("%y%m%d") + "_" + metadata_2021_crushed_amplicon_full_SP["LEAF_PROTOCOL"].str[0] + "_1")

metadata_2021_crushed_amplicon_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2021_crushed_amplicon_full_SP["DNA_ext_date"], errors="coerce")
      .dt.strftime("%y%m%d")
      .fillna("000000"))

metadata_2021_crushed_amplicon_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2021_crushed_amplicon_full_SP["PCR2_date"])
    .dt.strftime("%y%m%d") + "_"+ metadata_2021_crushed_amplicon_full_SP["amplicon"] )


# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2021_crushed_amplicon_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2021_crushed_amplicon_full_SP[id_col].eq("alex-control")
is_water = metadata_2021_crushed_amplicon_full_SP[id_col].eq("Ultrapure-water")
is_mystery= metadata_2021_crushed_amplicon_full_SP[id_col].eq("T-150621-c-mystery")

control_mask = is_zymo | is_alex | is_water 

# LY and SP fixed for all three
metadata_2021_crushed_amplicon_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2021_crushed_amplicon_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2021_crushed_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2021_crushed_amplicon_full_SP.loc[control_mask, "LY_SP"] = (metadata_2021_crushed_amplicon_full_SP.loc[control_mask, "LY"] + "__" + metadata_2021_crushed_amplicon_full_SP.loc[control_mask, "SP"])


metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "LY"] = "LY_Z_0000"
metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "SP"] = "SP_000"
metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "EX"] = "EX_000000"
metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "LY_SP"] = (metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "SP"])



# BS depends on which control
metadata_2021_crushed_amplicon_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2021_crushed_amplicon_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2021_crushed_amplicon_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"
metadata_2021_crushed_amplicon_full_SP.loc[is_mystery, "BS"] = "BS_MYSTRY_X_0"


# TODO turn the dates in identifiers to numbers FX EX_030323 should be EX_047 


metadata_2021_crushed_amplicon_full_SP["LY_SP_BS"]=metadata_2021_crushed_amplicon_full_SP["LY"] + "__" + metadata_2021_crushed_amplicon_full_SP["SP"]+ "__"  +metadata_2021_crushed_amplicon_full_SP["BS"] 
metadata_2021_crushed_amplicon_full_SP["LY_SP_BS_EX"]=metadata_2021_crushed_amplicon_full_SP["LY_SP_BS"] + "__"  +metadata_2021_crushed_amplicon_full_SP["EX"] 
metadata_2021_crushed_amplicon_full_SP["LY_SP_BS_EX_LP"]=metadata_2021_crushed_amplicon_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2021_crushed_amplicon_full_SP["LP"] 


metadata_2021_crushed_amplicon_full_SP.to_csv("test.csv")


print(len(metadata_2021_crushed_amplicon_full))
print(len(metadata_2021_crushed_amplicon_full_SP))
metadata_2021_crushed_amplicon_full_SP

# metadata_2021_crushed_amplicon_full_SP[~metadata_2021_crushed_amplicon_full_SP["SP"].isna()].groupby("SP").count()

350
350

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,SP_spray_fungicide,SP_fertilizer,SP_cultivar,SP_density,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,T-150621-c-mystery,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_MYSTRY_X_0,EX_000000,LP_231024_16S,LY_Z_0000__SP_000__BS_MYSTRY_X_0,LY_Z_0000__SP_000__BS_MYSTRY_X_0__EX_000000,LY_Z_0000__SP_000__BS_MYSTRY_X_0__EX_000000__L...
1,T-150621-c-118,NaN,118.0,2021-06-15,deep,4.0,118.0,10.0,NaN,n,...,False,HALF,Rembrandt,300.0,BS_210615_C_1,EX_000000,LP_230421_ITS,LY_T_2021__SP_118__BS_210615_C_1,LY_T_2021__SP_118__BS_210615_C_1__EX_000000,LY_T_2021__SP_118__BS_210615_C_1__EX_000000__L...
2,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ZYMCTL_X_0,EX_000000,LP_230420_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
3,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,BS_ULWCTL_X_0,EX_000000,LP_230420_ITS,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
4,T-150621-c-144,NaN,144.0,2021-06-15,deep,4.0,144.0,12.0,NaN,n,...,False,NORMAL,Kvium,450.0,BS_210615_C_1,EX_000000,LP_230421_ITS,LY_T_2021__SP_144__BS_210615_C_1,LY_T_2021__SP_144__BS_210615_C_1__EX_000000,LY_T_2021__SP_144__BS_210615_C_1__EX_000000__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,T-150621-c-113,NaN,113.0,2021-06-15,deep,4.0,113.0,10.0,NaN,n,...,False,HALF,Kvium,450.0,BS_210615_C_1,EX_000000,LP_231024_16S,LY_T_2021__SP_113__BS_210615_C_1,LY_T_2021__SP_113__BS_210615_C_1__EX_000000,LY_T_2021__SP_113__BS_210615_C_1__EX_000000__L...
346,T-150621-c-114,NaN,114.0,2021-06-15,deep,4.0,114.0,10.0,NaN,n,...,False,HALF,Kvium,150.0,BS_210615_C_1,EX_000000,LP_231024_16S,LY_T_2021__SP_114__BS_210615_C_1,LY_T_2021__SP_114__BS_210615_C_1__EX_000000,LY_T_2021__SP_114__BS_210615_C_1__EX_000000__L...
347,T-150621-c-115,NaN,115.0,2021-06-15,deep,4.0,115.0,10.0,NaN,n,...,False,HALF,Rembrandt,450.0,BS_210615_C_1,EX_000000,LP_231024_16S,LY_T_2021__SP_115__BS_210615_C_1,LY_T_2021__SP_115__BS_210615_C_1__EX_000000,LY_T_2021__SP_115__BS_210615_C_1__EX_000000__L...
348,T-150621-c-104,NaN,104.0,2021-06-15,deep,3.0,104.0,9.0,NaN,n,...,False,NORMAL,Sheriff,450.0,BS_210615_C_1,EX_000000,LP_231024_16S,LY_T_2021__SP_104__BS_210615_C_1,LY_T_2021__SP_104__BS_210615_C_1__EX_000000,LY_T_2021__SP_104__BS_210615_C_1__EX_000000__L...
349,T-150621-c-144,NaN,144.0,2021-06-15,deep,4.0,144.0,12.0,NaN,n,...,False,NORMAL,Kvium,450.0,BS_210615_C_1,EX_000000,LP_231024_16S,LY_T_2021__SP_144__BS_210615_C_1,LY_T_2021__SP_144__BS_210615_C_1__EX_000000,LY_T_2021__SP_144__BS_210615_C_1__EX_000000__L...

In [19]:
metadata_2021_crushed_amplicon_full_SP.groupby("LY_SP_BS").first()

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,SP_subplot,SP_spray_fungicide,SP_fertilizer,SP_cultivar,SP_density,BS,EX,LP,LY_SP_BS_EX,LY_SP_BS_EX_LP
LY_SP_BS,,,,,,,,,,,,,,,,,,,,,
LY_T_2021__SP_001__BS_210615_C_1,T-150621-c-1,NaN,1.0,2021-06-15,deep,1.0,1.0,1.0,NaN,n,...,1.0,False,HALF,Heerup,450.0,BS_210615_C_1,EX_000000,LP_230420_ITS,LY_T_2021__SP_001__BS_210615_C_1__EX_000000,LY_T_2021__SP_001__BS_210615_C_1__EX_000000__L...
LY_T_2021__SP_002__BS_210615_C_1,T-150621-c-2,NaN,2.0,2021-06-15,deep,1.0,2.0,1.0,NaN,n,...,1.0,False,HALF,Heerup,300.0,BS_210615_C_1,EX_000000,LP_230420_ITS,LY_T_2021__SP_002__BS_210615_C_1__EX_000000,LY_T_2021__SP_002__BS_210615_C_1__EX_000000__L...
LY_T_2021__SP_003__BS_210615_C_1,T-150621-c-3,NaN,3.0,2021-06-15,deep,1.0,3.0,1.0,NaN,n,...,1.0,False,HALF,Kvium,450.0,BS_210615_C_1,EX_000000,LP_230420_ITS,LY_T_2021__SP_003__BS_210615_C_1__EX_000000,LY_T_2021__SP_003__BS_210615_C_1__EX_000000__L...
LY_T_2021__SP_004__BS_210615_C_1,T-150621-c-4,NaN,4.0,2021-06-15,deep,1.0,4.0,1.0,NaN,n,...,1.0,False,HALF,Sheriff,300.0,BS_210615_C_1,EX_000000,LP_230420_ITS,LY_T_2021__SP_004__BS_210615_C_1__EX_000000,LY_T_2021__SP_004__BS_210615_C_1__EX_000000__L...
LY_T_2021__SP_005__BS_210615_C_1,T-150621-c-5,NaN,5.0,2021-06-15,deep,1.0,5.0,1.0,NaN,n,...,1.0,False,HALF,Rembrandt,150.0,BS_210615_C_1,EX_000000,LP_230420_ITS,LY_T_2021__SP_005__BS_210615_C_1__EX_000000,LY_T_2021__SP_005__BS_210615_C_1__EX_000000__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LY_T_2021__SP_143__BS_210615_C_1,T-150621-c-143,NaN,143.0,2021-06-15,deep,4.0,143.0,12.0,NaN,n,...,12.0,False,NORMAL,Sheriff,150.0,BS_210615_C_1,EX_000000,LP_230421_ITS,LY_T_2021__SP_143__BS_210615_C_1__EX_000000,LY_T_2021__SP_143__BS_210615_C_1__EX_000000__L...
LY_T_2021__SP_144__BS_210615_C_1,T-150621-c-144,NaN,144.0,2021-06-15,deep,4.0,144.0,12.0,NaN,n,...,12.0,False,NORMAL,Kvium,450.0,BS_210615_C_1,EX_000000,LP_230421_ITS,LY_T_2021__SP_144__BS_210615_C_1__EX_000000,LY_T_2021__SP_144__BS_210615_C_1__EX_000000__L...
LY_X_0000__SP_000__BS_ULWCTL_X_0,Ultrapure-water,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,...,NaN,None,None,None,NaN,BS_ULWCTL_X_0,EX_000000,LP_230420_ITS,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
LY_X_0000__SP_000__BS_ZYMCTL_X_0,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,...,NaN,None,None,None,NaN,BS_ZYMCTL_X_0,EX_000000,LP_230420_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
LY_Z_0000__SP_000__BS_MYSTRY_X_0,T-150621-c-mystery,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,...,NaN,None,None,None,NaN,BS_MYSTRY_X_0,EX_000000,LP_231024_16S,LY_Z_0000__SP_000__BS_MYSTRY_X_0__EX_000000,LY_Z_0000__SP_000__BS_MYSTRY_X_0__EX_000000__L...

## CRUSH 2022

In [20]:
# metadata_2022_crushed_amplicon[metadata_2022_crushed_amplicon["run_ID"]=="RISO2"]
# metadata_2022_crushed_amplicon["run_ID"]=metadata_2022_crushed_amplicon["run_ID"].str.replace("RIS2", "RISO2")
print("Number of samples: "  + str(len(metadata_2022_crushed_amplicon)))
print("Number of sequence runs: "  + str(metadata_2022_crushed_amplicon["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2022_crushed_amplicon["run_ID"].value_counts()

Number of samples: 737
Number of sequence runs: 731

Number of sequence runs per folder:

run_ID
seq230707_DWDQH    367
seq230526_JRV78    364
Name: count, dtype: int64

In [21]:
metadata_2022_crushed_amplicon_full=metadata_2022_crushed_amplicon.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2022_crushed_amplicon_full=metadata_2022_crushed_amplicon_full[metadata_2022_crushed_amplicon_full["seq_sample_ID"].notna()]
metadata_2022_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_2022_crushed_amplicon_full['correct_seq_sample_ID'].fillna(metadata_2022_crushed_amplicon_full['seq_sample_ID'])
metadata_2022_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2022_crushed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "")
metadata_2022_crushed_amplicon_full=metadata_2022_crushed_amplicon_full.sort_values("run_ID")
metadata_2022_crushed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,run_ID,note,correct_seq_sample_ID,YEAR,LEAF_PROTOCOL,LIBRARY_PREPARATION,Unnamed: 0,dir_name,full_path,suggested_correct_seq_sample_ID
368,R-160622-c-1,NaN,1.0,2022-06-16,timeline,1.0,1.0,NaN,A16,n,...,seq230526_JRV78,Alex_may__have_thawed_before_freezedrying,NaN,2022,CRUSHED,amplicon,15.0,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-160622-ITS-c-1
488,H-200622-c-17-7,NaN,17.0,2022-06-20,deep,3.0,8.0,NaN,A7,n,...,seq230526_JRV78,NaN,NaN,2022,CRUSHED,amplicon,15.0,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,H-200622-ITS-c-17-7
489,H-200622-c-18-1,NaN,18.0,2022-06-20,deep,3.0,9.0,NaN,B5,y,...,seq230526_JRV78,Alex_May_have_thawed_before_freezedrying,NaN,2022,CRUSHED,amplicon,15.0,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,H-200622-ITS-c-18-1
490,H-200622-c-18-2,NaN,18.0,2022-06-20,deep,3.0,9.0,NaN,B5,y,...,seq230526_JRV78,NaN,NaN,2022,CRUSHED,amplicon,15.0,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,H-200622-ITS-c-18-2
491,H-200622-c-18-3,NaN,18.0,2022-06-20,deep,3.0,9.0,NaN,B5,y,...,seq230526_JRV78,NaN,NaN,2022,CRUSHED,amplicon,15.0,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,H-200622-ITS-c-18-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,R-210622-c-43-6,NaN,43.0,2022-06-21,deep,13.0,19.0,NaN,A16,n,...,seq230707_DWDQH,NaN,NaN,2022,CRUSHED,amplicon,0.0,seq230707_DWDQH,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-c-43-6
250,R-210622-c-43-7,NaN,43.0,2022-06-21,deep,13.0,19.0,NaN,A16,n,...,seq230707_DWDQH,NaN,NaN,2022,CRUSHED,amplicon,0.0,seq230707_DWDQH,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-c-43-7
251,R-210622-c-44-1,NaN,44.0,2022-06-21,deep,13.0,20.0,NaN,A7,n,...,seq230707_DWDQH,NaN,NaN,2022,CRUSHED,amplicon,0.0,seq230707_DWDQH,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-c-44-1
253,R-210622-c-44-3,NaN,44.0,2022-06-21,deep,13.0,20.0,NaN,A7,n,...,seq230707_DWDQH,NaN,NaN,2022,CRUSHED,amplicon,0.0,seq230707_DWDQH,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-c-44-3
0,R-160622-c-1,NaN,1.0,2022-06-16,timeline,1.0,1.0,NaN,A16,n,...,seq230707_DWDQH,Alex_may__have_thawed_before_freezedrying,NaN,2022,CRUSHED,amplicon,0.0,seq230707_DWDQH,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-160622-16S-c-1

In [22]:
# Iterate over each row and print files
metadata_2022_crushed_amplicon_full["forward_fq"]=""
metadata_2022_crushed_amplicon_full["reverse_fq"]=""
metadata_2022_crushed_amplicon_full["current_seq_sample_ID"]=""
metadata_2022_crushed_amplicon_full["corrected_forward_fq"]=""
metadata_2022_crushed_amplicon_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2022_crushed_amplicon_full)  # Get the total number of rows

for index, row in metadata_2022_crushed_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        # Check if the number of matching files is not equal to 2
        if len(matching_files) == 2:
            metadata_2022_crushed_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2022_crushed_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2022_crushed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2022_crushed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2022_crushed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2
    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1

# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

Processing... 100.00% complete
Processing complete!

In [23]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2022_crushed_amplicon_full = metadata_2022_crushed_amplicon_full[
    [col for col in metadata_2022_crushed_amplicon_full.columns if col not in columns_to_move] + columns_to_move
]

# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_2022_crushed_amplicon_full['forward_fq'] = metadata_2022_crushed_amplicon_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_2022_crushed_amplicon_full['reverse_fq'] = metadata_2022_crushed_amplicon_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2022_crushed_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2022_crushed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2022_crushed_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2022_crushed_amplicon_full["ALREADY_CORRECT"] = metadata_2022_crushed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2022_crushed_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2022_crushed_amplicon_full = metadata_2022_crushed_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2022_crushed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
686,A-230622-c-61-1,NaN,61.0,2022-06-23,deep,3.0,13.0,NaN,A7,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,,,,,,NaN,A-230622-ITS-c-61-1,False,False
687,A-230622-c-61-2,NaN,61.0,2022-06-23,deep,3.0,13.0,NaN,A7,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,,,,,,NaN,A-230622-ITS-c-61-2,False,False
688,A-230622-c-61-3,NaN,61.0,2022-06-23,deep,3.0,13.0,NaN,A7,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,,,,,,NaN,A-230622-ITS-c-61-3,False,False
717,A-230622-c-70-5,NaN,70.0,2022-06-23,deep,4.0,22.0,NaN,A5,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,,,,,,NaN,A-230622-ITS-c-70-5,False,False
718,A-230622-c-70-6,NaN,70.0,2022-06-23,deep,4.0,22.0,NaN,A5,n,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,,,,,,NaN,A-230622-ITS-c-70-6,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-P1-16S-c-pos_S88_L001_R1_001.fastq.gz,R-P1-16S-c-pos_S88_L001_R2_001.fastq.gz,R-000022-16S-c-P1-pos_S88_L001_R1_001.fastq.gz,R-000022-16S-c-P1-pos_S88_L001_R2_001.fastq.gz,R-P1-16S-c-pos,R-000022-16S-c-P1-pos,R-000022-16S-c-P1-pos,True,False
85,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-P1-16S-c-neg_S89_L001_R1_001.fastq.gz,R-P1-16S-c-neg_S89_L001_R2_001.fastq.gz,R-000022-16S-c-P1-neg_S89_L001_R1_001.fastq.gz,R-000022-16S-c-P1-neg_S89_L001_R2_001.fastq.gz,R-P1-16S-c-neg,R-000022-16S-c-P1-neg,R-000022-16S-c-P1-neg,True,False
367,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-P4-16S-c-neg_S187_L001_R1_001.fastq.gz,R-P4-16S-c-neg_S187_L001_R2_001.fastq.gz,R-000022-16S-c-P4-neg_S187_L001_R1_001.fastq.gz,R-000022-16S-c-P4-neg_S187_L001_R2_001.fastq.gz,R-P4-16S-c-neg,R-000022-16S-c-P4-neg,R-000022-16S-c-P4-neg,True,False
277,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-P3-16S-c-pos_S97_L001_R1_001.fastq.gz,R-P3-16S-c-pos_S97_L001_R2_001.fastq.gz,R-000022-16S-c-P3-pos_S97_L001_R1_001.fastq.gz,R-000022-16S-c-P3-pos_S97_L001_R2_001.fastq.gz,R-P3-16S-c-pos,R-000022-16S-c-P3-pos,R-000022-16S-c-P3-pos,True,False
276,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-P3-16S-c-neg_S96_L001_R1_001.fastq.gz,R-P3-16S-c-neg_S96_L001_R2_001.fastq.gz,R-000022-16S-c-P3-neg_S96_L001_R1_001.fastq.gz,R-000022-16S-c-P3-neg_S96_L001_R2_001.fastq.gz,R-P3-16S-c-neg,R-000022-16S-c-P3-neg,R-000022-16S-c-P3-neg,True,False

In [24]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]
metadata_2022_crushed_amplicon_full["location"]=metadata_2022_crushed_amplicon_full["bio_sample_ID"].str.split("-").str[0]
metadata_2022_crushed_amplicon_full_SP=metadata_2022_crushed_amplicon_full.merge(pd.concat([SP_0000, SP_2022]), left_on=["plot", "location"], right_on=["SP_plot", "SP_location"], how="left")#.to_csv("test.csv")

metadata_2022_crushed_amplicon_full_SP["triplicate"] = (metadata_2022_crushed_amplicon_full_SP["bio_sample_ID"].str.split("-").str[4].fillna(0)).astype(str)
metadata_2022_crushed_amplicon_full_SP["BS"] = (
    "BS_" +
    pd.to_datetime(metadata_2022_crushed_amplicon_full_SP["sample_date"])
    .dt.strftime("%y%m%d") + "_" + metadata_2022_crushed_amplicon_full_SP["LEAF_PROTOCOL"].str[0] + "_" + metadata_2022_crushed_amplicon_full_SP["triplicate"] )

metadata_2022_crushed_amplicon_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2022_crushed_amplicon_full_SP["DNA_ext_date"], errors="coerce")
      .dt.strftime("%y%m%d")
      .fillna("000000"))

metadata_2022_crushed_amplicon_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2022_crushed_amplicon_full_SP["PCR2_date"])
    .dt.strftime("%y%m%d") + "_"+ metadata_2022_crushed_amplicon_full_SP["amplicon"] )


# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2022_crushed_amplicon_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2022_crushed_amplicon_full_SP[id_col].eq("alex-control")
is_water = metadata_2022_crushed_amplicon_full_SP[id_col].eq("Ultrapure-water")
is_mystery= metadata_2022_crushed_amplicon_full_SP[id_col].eq("T-150621-c-mystery")
is_contaminated= metadata_2022_crushed_amplicon_full_SP[id_col].eq("contaminated-well")


control_mask = is_zymo | is_alex | is_water 

# LY and SP fixed for all three
metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"

metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "LY_SP"] = (metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "LY"] + "__" + metadata_2022_crushed_amplicon_full_SP.loc[control_mask, "SP"])


metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "LY"] = "LY_Z_0000"
metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "SP"] = "SP_000"
metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "EX"] = "EX_000000"
metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "LY_SP"] = (metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "SP"])


metadata_2022_crushed_amplicon_full_SP.loc[is_contaminated, "LY"] = "LY_Z_0000"
metadata_2022_crushed_amplicon_full_SP.loc[is_contaminated, "SP"] = "SP_000"
metadata_2022_crushed_amplicon_full_SP.loc[is_contaminated, "EX"] = "EX_000000"
metadata_2022_crushed_amplicon_full_SP.loc[is_contaminated, "LY_SP"] = (metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "SP"])


# BS depends on which control
metadata_2022_crushed_amplicon_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2022_crushed_amplicon_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2022_crushed_amplicon_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"
metadata_2022_crushed_amplicon_full_SP.loc[is_mystery, "BS"] = "BS_MYSTRY_X_0"
metadata_2022_crushed_amplicon_full_SP.loc[is_contaminated, "BS"] = "BS_CONTAM_X_0"



metadata_2022_crushed_amplicon_full_SP["LY_SP_BS"]=metadata_2022_crushed_amplicon_full_SP["LY"] + "__" + metadata_2022_crushed_amplicon_full_SP["SP"]+ "__"  +metadata_2022_crushed_amplicon_full_SP["BS"] 
metadata_2022_crushed_amplicon_full_SP["LY_SP_BS_EX"]=metadata_2022_crushed_amplicon_full_SP["LY_SP_BS"] + "__"  +metadata_2022_crushed_amplicon_full_SP["EX"] 
metadata_2022_crushed_amplicon_full_SP["LY_SP_BS_EX_LP"]=metadata_2022_crushed_amplicon_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2022_crushed_amplicon_full_SP["LP"] 


metadata_2022_crushed_amplicon_full_SP.to_csv("test.csv")


print(len(metadata_2022_crushed_amplicon_full))
print(len(metadata_2022_crushed_amplicon_full_SP))
metadata_2022_crushed_amplicon_full_SP

# metadata_2022_crushed_amplicon_full_SP[~metadata_2022_crushed_amplicon_full_SP["SP"].isna()].groupby("SP").count()

727
727

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,SP_lane,SP_parcel,SP_location,triplicate,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,A-230622-c-61-1,NaN,61.0,2022-06-23,deep,3.0,13.0,NaN,A7,n,...,3.0,18.0,A,1,BS_220623_C_1,EX_221012,LP_230313_ITS,LY_A_2022__SP_013__BS_220623_C_1,LY_A_2022__SP_013__BS_220623_C_1__EX_221012,LY_A_2022__SP_013__BS_220623_C_1__EX_221012__L...
1,A-230622-c-61-2,NaN,61.0,2022-06-23,deep,3.0,13.0,NaN,A7,n,...,3.0,18.0,A,2,BS_220623_C_2,EX_221012,LP_230313_ITS,LY_A_2022__SP_013__BS_220623_C_2,LY_A_2022__SP_013__BS_220623_C_2__EX_221012,LY_A_2022__SP_013__BS_220623_C_2__EX_221012__L...
2,A-230622-c-61-3,NaN,61.0,2022-06-23,deep,3.0,13.0,NaN,A7,n,...,3.0,18.0,A,3,BS_220623_C_3,EX_221012,LP_230313_ITS,LY_A_2022__SP_013__BS_220623_C_3,LY_A_2022__SP_013__BS_220623_C_3__EX_221012,LY_A_2022__SP_013__BS_220623_C_3__EX_221012__L...
3,A-230622-c-70-5,NaN,70.0,2022-06-23,deep,4.0,22.0,NaN,A5,n,...,4.0,72.0,A,5,BS_220623_C_5,EX_221012,LP_230313_ITS,LY_A_2022__SP_022__BS_220623_C_5,LY_A_2022__SP_022__BS_220623_C_5__EX_221012,LY_A_2022__SP_022__BS_220623_C_5__EX_221012__L...
4,A-230622-c-70-6,NaN,70.0,2022-06-23,deep,4.0,22.0,NaN,A5,n,...,4.0,72.0,A,6,BS_220623_C_6,EX_221012,LP_230313_ITS,LY_A_2022__SP_022__BS_220623_C_6,LY_A_2022__SP_022__BS_220623_C_6__EX_221012,LY_A_2022__SP_022__BS_220623_C_6__EX_221012__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_230201_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
723,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_230201_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
724,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_230320_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
725,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_230320_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
726,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_230320_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...

In [25]:
metadata_2022_crushed_amplicon_full_SP.groupby("LY_SP_BS").first()

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,SP_fertilizer,SP_lane,SP_parcel,SP_location,triplicate,BS,EX,LP,LY_SP_BS_EX,LY_SP_BS_EX_LP
LY_SP_BS,,,,,,,,,,,,,,,,,,,,,
LY_A_2022__SP_001__BS_220623_C_1,A-230622-c-49-1,NaN,49.0,2022-06-23,deep,1.0,1.0,NaN,A16,n,...,None,1.0,27.0,A,1,BS_220623_C_1,EX_221012,LP_230307_ITS,LY_A_2022__SP_001__BS_220623_C_1__EX_221012,LY_A_2022__SP_001__BS_220623_C_1__EX_221012__L...
LY_A_2022__SP_001__BS_220623_C_2,A-230622-c-49-2,NaN,49.0,2022-06-23,deep,1.0,1.0,NaN,A16,n,...,None,1.0,27.0,A,2,BS_220623_C_2,EX_221012,LP_230307_ITS,LY_A_2022__SP_001__BS_220623_C_2__EX_221012,LY_A_2022__SP_001__BS_220623_C_2__EX_221012__L...
LY_A_2022__SP_001__BS_220623_C_3,A-230622-c-49-3,NaN,49.0,2022-06-23,deep,1.0,1.0,NaN,A16,n,...,None,1.0,27.0,A,3,BS_220623_C_3,EX_221012,LP_230307_ITS,LY_A_2022__SP_001__BS_220623_C_3__EX_221012,LY_A_2022__SP_001__BS_220623_C_3__EX_221012__L...
LY_A_2022__SP_001__BS_220623_C_4,A-230622-c-49-4,NaN,49.0,2022-06-23,deep,1.0,1.0,NaN,A16,n,...,None,1.0,27.0,A,4,BS_220623_C_4,EX_221012,LP_230307_ITS,LY_A_2022__SP_001__BS_220623_C_4__EX_221012,LY_A_2022__SP_001__BS_220623_C_4__EX_221012__L...
LY_A_2022__SP_001__BS_220623_C_5,A-230622-c-49-5,NaN,49.0,2022-06-23,deep,1.0,1.0,NaN,A16,n,...,None,1.0,27.0,A,5,BS_220623_C_5,EX_221006,LP_230307_ITS,LY_A_2022__SP_001__BS_220623_C_5__EX_221006,LY_A_2022__SP_001__BS_220623_C_5__EX_221006__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LY_R_2022__SP_024__BS_220704_C_0,R-040722-c-120,NaN,120.0,2022-07-04,timeline,16.0,24.0,NaN,A5,n,...,NORMAL,16.0,9.0,R,0,BS_220704_C_0,EX_221006,LP_230131_ITS,LY_R_2022__SP_024__BS_220704_C_0__EX_221006,LY_R_2022__SP_024__BS_220704_C_0__EX_221006__L...
LY_R_2022__SP_024__BS_220714_C_0,R-140722-c-144,NaN,144.0,2022-07-14,timeline,16.0,24.0,NaN,A5,n,...,NORMAL,16.0,9.0,R,0,BS_220714_C_0,EX_221006,LP_230131_ITS,LY_R_2022__SP_024__BS_220714_C_0__EX_221006,LY_R_2022__SP_024__BS_220714_C_0__EX_221006__L...
LY_X_0000__SP_000__BS_ULWCTL_X_0,Ultrapure-water,NaN,NaN,NaT,None,NaN,NaN,NaN,None,None,...,None,NaN,NaN,None,0,BS_ULWCTL_X_0,EX_000000,LP_230203_ITS,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
LY_X_0000__SP_000__BS_ZYMCTL_X_0,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,None,NaN,NaN,NaN,None,None,...,None,NaN,NaN,None,Standard,BS_ZYMCTL_X_0,EX_000000,LP_230203_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
LY_Z_0000__SP_000__BS_CONTAM_X_0,contaminated-well,NaN,NaN,NaT,None,NaN,NaN,NaN,None,None,...,None,NaN,NaN,None,0,BS_CONTAM_X_0,EX_000000,LP_230313_ITS,LY_Z_0000__SP_000__BS_CONTAM_X_0__EX_000000,LY_Z_0000__SP_000__BS_CONTAM_X_0__EX_000000__L...

## SHOT WGS 2022

In [47]:

print("Number of samples: "  + str(len(metadata_2022_washed_shotgun)))
print("Number of sequence runs: "  + str(metadata_2022_washed_shotgun["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2022_washed_shotgun["run_ID"].value_counts()

Number of samples: 316
Number of sequence runs: 315

Number of sequence runs per folder:

run_ID
seq230315_PF2CP    226
seq230526_LQJXR     89
Name: count, dtype: int64

In [48]:
metadata_2022_washed_shotgun_full=metadata_2022_washed_shotgun.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2022_washed_shotgun_full=metadata_2022_washed_shotgun_full[metadata_2022_washed_shotgun_full["seq_sample_ID"].notna()]
metadata_2022_washed_shotgun_full['suggested_correct_seq_sample_ID'] = \
    metadata_2022_washed_shotgun_full['correct_seq_sample_ID'].fillna(metadata_2022_washed_shotgun_full['seq_sample_ID'])
metadata_2022_washed_shotgun_full['suggested_correct_seq_sample_ID'] = metadata_2022_washed_shotgun_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "")
metadata_2022_washed_shotgun_full=metadata_2022_washed_shotgun_full.sort_values("run_ID")

In [49]:
from collections import defaultdict
# Iterate over each row and print files
metadata_2022_washed_shotgun_full["forward_fq"]=""
metadata_2022_washed_shotgun_full["reverse_fq"]=""
metadata_2022_washed_shotgun_full["current_seq_sample_ID"]=""
metadata_2022_washed_shotgun_full["corrected_forward_fq"]=""
metadata_2022_washed_shotgun_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2022_washed_shotgun_full)  # Get the total number of rows

for index, row in metadata_2022_washed_shotgun_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        if len(matching_files) == 2:
            metadata_2022_washed_shotgun_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2022_washed_shotgun_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2022_washed_shotgun_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2022_washed_shotgun_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2022_washed_shotgun_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2


        if len(matching_files) >2:

            
            
            grouped_files = defaultdict(list)
            
            # Loop over each file and group by the part before R1/R2
            for file in matching_files:
                # Split the file name at R1 or R2
                base_name = file.split("/")[-1].rsplit("_R", 1)[0]  # Split from the last occurrence of "_R"
                grouped_files[base_name].append(file.split("/")[-1])
            
            metadata_2022_washed_shotgun_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", grouped_files[base_name][0].split("/")[-1])[0]
     
            
            # Print the grouped files
            m=0
            for base_name, files in grouped_files.items():      
                if len(files)==2:
            
                    if m==0:
                        # print(grouped_files[base_name][0])
                        metadata_2022_washed_shotgun_full.loc[index, "forward_fq"] = [grouped_files[base_name][0]]
                        metadata_2022_washed_shotgun_full.loc[index, "reverse_fq"] = [grouped_files[base_name][1]]
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2022_washed_shotgun_full.loc[index, "corrected_forward_fq"] = [correct_seq_sample_ID + ending_R1]
                        metadata_2022_washed_shotgun_full.loc[index, "corrected_reverse_fq"] = [correct_seq_sample_ID + ending_R2]
            
            
                    else:
                        metadata_2022_washed_shotgun_full.loc[index, "forward_fq"].append(grouped_files[base_name][0])
                        metadata_2022_washed_shotgun_full.loc[index, "reverse_fq"].append(grouped_files[base_name][1])
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2022_washed_shotgun_full.loc[index, "corrected_forward_fq"].append(correct_seq_sample_ID + ending_R1)
                        metadata_2022_washed_shotgun_full.loc[index, "corrected_reverse_fq"].append(correct_seq_sample_ID + ending_R2)
            
                
                    m=m+1
                else:
                    print("ERROR", base_name, files)


    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1
    
# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

# TODO ERROR washed-1-R-040722-s-24G_S145_L001 ['washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz']

ERROR washed-1-R-040722-s-24G_S145_L001 ['washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz']
Processing... 100.00% complete
Processing complete!

In [50]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2022_washed_shotgun_full = metadata_2022_washed_shotgun_full[
    [col for col in metadata_2022_washed_shotgun_full.columns if col not in columns_to_move] + columns_to_move]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2022_washed_shotgun_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2022_washed_shotgun_full["suggested_correct_seq_sample_ID"] == metadata_2022_washed_shotgun_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2022_washed_shotgun_full["ALREADY_CORRECT"] = metadata_2022_washed_shotgun_full["suggested_correct_seq_sample_ID"] == metadata_2022_washed_shotgun_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2022_washed_shotgun_full = metadata_2022_washed_shotgun_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2022_washed_shotgun_full

,bio_sample_ID,sample_date,sample_type,block,plot,subplot,ID_on_field,spray,fertiliser,cultivar,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
152,R-040722-s-9G,2022-07-04,timeline,NaN,9.0,NaN,B5,n,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-040722-s-9G_S79_L001_R1_001.fastq.gz, R-040...","[R-040722-s-9G_S79_L001_R2_001.fastq.gz, R-040...","[R-040722-s-9G_S79_L001_R1_001.fastq.gz, R-040...","[R-040722-s-9G_S79_L001_R2_001.fastq.gz, R-040...",16S-R-040722-s-9G,NaN,R-040722-s-9G,False,False
153,R-040722-s-10G,2022-07-04,timeline,NaN,10.0,NaN,A7,y,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-040722-s-10G_S87_L001_R1_001.fastq.gz, R-04...","[R-040722-s-10G_S87_L001_R2_001.fastq.gz, R-04...","[R-040722-s-10G_S87_L001_R1_001.fastq.gz, R-04...","[R-040722-s-10G_S87_L001_R2_001.fastq.gz, R-04...",16S-R-040722-s-10G,NaN,R-040722-s-10G,False,False
154,R-040722-s-11G,2022-07-04,timeline,NaN,11.0,NaN,A16,y,NaN,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-040722-s-11G_S96_L001_R1_001.fastq.gz, R-04...","[R-040722-s-11G_S96_L001_R2_001.fastq.gz, R-04...","[R-040722-s-11G_S96_L001_R1_001.fastq.gz, R-04...","[R-040722-s-11G_S96_L001_R2_001.fastq.gz, R-04...",16S-R-040722-s-11G,NaN,R-040722-s-11G,False,False
155,R-040722-s-12G,2022-07-04,timeline,NaN,12.0,NaN,A5,y,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-040722-s-12G_S105_L001_R1_001.fastq.gz, R-0...","[R-040722-s-12G_S105_L001_R2_001.fastq.gz, R-0...","[R-040722-s-12G_S105_L001_R1_001.fastq.gz, R-0...","[R-040722-s-12G_S105_L001_R2_001.fastq.gz, R-0...",16S-R-040722-s-12G,NaN,R-040722-s-12G,False,False
158,R-040722-s-15G,2022-07-04,timeline,NaN,15.0,NaN,A16,y,NaN,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-040722-s-15G_S131_L001_R1_001.fastq.gz, R-0...","[R-040722-s-15G_S131_L001_R2_001.fastq.gz, R-0...","[R-040722-s-15G_S131_L001_R1_001.fastq.gz, R-0...","[R-040722-s-15G_S131_L001_R2_001.fastq.gz, R-0...",16S-R-040722-s-15G,NaN,R-040722-s-15G,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-nex-lib-neg-5_S218_L001_R1_001.fastq.gz, R-...","[R-nex-lib-neg-5_S218_L001_R2_001.fastq.gz, R-...",[R-000022-s-nex-lib-neg-5_S218_L001_R1_001.fas...,[R-000022-s-nex-lib-neg-5_S218_L001_R2_001.fas...,R-nex-lib-neg-5,R-000022-s-nex-lib-neg-5,R-000022-s-nex-lib-neg-5,True,False
223,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-nex-lib-neg-6_S219_L001_R1_001.fastq.gz, R-...","[R-nex-lib-neg-6_S219_L001_R2_001.fastq.gz, R-...",[R-000022-s-nex-lib-neg-6_S219_L001_R1_001.fas...,[R-000022-s-nex-lib-neg-6_S219_L001_R2_001.fas...,R-nex-lib-neg-6,R-000022-s-nex-lib-neg-6,R-000022-s-nex-lib-neg-6,True,False
224,DES,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,[R-hug-kit-des-neg-1_S220_L001_R1_001.fastq.gz...,[R-hug-kit-des-neg-1_S220_L001_R2_001.fastq.gz...,[R-000022-s-hug-kit-des-neg-1_S220_L001_R1_001...,[R-000022-s-hug-kit-des-neg-1_S220_L001_R2_001...,R-hug-kit-des-neg-1,R-000022-s-hug-kit-des-neg-1,R-000022-s-hug-kit-des-neg-1,True,False
225,1xPBS,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,[R-hug-kit-pbs-neg-2_S221_L001_R1_001.fastq.gz...,[R-hug-kit-pbs-neg-2_S221_L001_R2_001.fastq.gz...,[R-000022-s-hug-kit-pbs-neg-2_S221_L001_R1_001...,[R-000022-s-hug-kit-pbs-neg-2_S221_L001_R2_001...,R-hug-kit-pbs-neg-2,R-000022-s-hug-kit-pbs-neg-2,R-000022-s-hug-kit-pbs-neg-2,True,False
226,1xPBS,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,[R-hug-kit-pbs-neg-3_S222_L001_R1_001.fastq.gz...,[R-hug-kit-pbs-neg-3_S222_L001_R2_001.fastq.gz...,[R-000022-s-hug-kit-pbs-neg-3_S222_L001_R1_001...,[R-000022-s-hug-kit-pbs-neg-3_S222_L001_R2_001...,R-hug-kit-pbs-neg-3,R-000022-s-hug-kit-pbs-neg-3,R-000022-s-hug-kit-pbs-neg-3,True,False

In [ ]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]
metadata_2022_washed_shotgun_full["location"]=metadata_2022_washed_shotgun_full["bio_sample_ID"].str.replace("_", "-").str.split("-").str[0]
metadata_2022_washed_shotgun_full_SP=metadata_2022_washed_shotgun_full.merge(pd.concat([SP_0000, SP_2022]), left_on=["plot", "location"], right_on=["SP_plot", "SP_location"], how="left")#.to_csv("test.csv")

metadata_2022_washed_shotgun_full_SP["triplicate"] = (metadata_2022_washed_shotgun_full_SP["bio_sample_ID"].str.split("-").str[4].fillna(0)).astype(str)
metadata_2022_washed_shotgun_full_SP["BS"] = (
    "BS_" +
    pd.to_datetime(metadata_2022_washed_shotgun_full_SP["sample_date"])
    .dt.strftime("%y%m%d") + "_" + metadata_2022_washed_shotgun_full_SP["LEAF_PROTOCOL"].str[0] + "_1" )

metadata_2022_washed_shotgun_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2022_washed_shotgun_full_SP["DNA_ext_date"], errors="coerce")
      .dt.strftime("%y%m%d")
      .fillna("000000"))

metadata_2022_washed_shotgun_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2022_washed_shotgun_full_SP["lib_date"])
    .dt.strftime("%y%m%d") + "_WGS")


# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2022_washed_shotgun_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2022_washed_shotgun_full_SP[id_col].eq("alex-control")
is_water = metadata_2022_washed_shotgun_full_SP[id_col].eq("Ultrapure-water")
is_mystery= metadata_2022_washed_shotgun_full_SP[id_col].eq("T-150621-c-mystery")
is_des= metadata_2022_washed_shotgun_full_SP[id_col].eq("DES")
is_pbs= metadata_2022_washed_shotgun_full_SP[id_col].eq("1xPBS")
is_contaminated= metadata_2022_washed_shotgun_full_SP[id_col].eq("contaminated-well")

control_mask = is_zymo | is_alex | is_water | is_des | is_pbs

# LY and SP fixed for all three
metadata_2022_washed_shotgun_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2022_washed_shotgun_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2022_washed_shotgun_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2022_washed_shotgun_full_SP.loc[control_mask, "EX"] = "EX_000000"

metadata_2022_washed_shotgun_full_SP.loc[control_mask, "LY_SP"] = (metadata_2022_washed_shotgun_full_SP.loc[control_mask, "LY"] + "__" + metadata_2022_washed_shotgun_full_SP.loc[control_mask, "SP"])


metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "LY"] = "LY_Z_0000"
metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "SP"] = "SP_000"
metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "EX"] = "EX_000000"
metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "LY_SP"] = (metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "SP"])


metadata_2022_washed_shotgun_full_SP.loc[is_contaminated, "LY"] = "LY_Z_0000"
metadata_2022_washed_shotgun_full_SP.loc[is_contaminated, "SP"] = "SP_000"
metadata_2022_washed_shotgun_full_SP.loc[is_contaminated, "EX"] = "EX_000000"
metadata_2022_washed_shotgun_full_SP.loc[is_contaminated, "LY_SP"] = (metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "SP"])


# BS depends on which control
metadata_2022_washed_shotgun_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2022_washed_shotgun_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2022_washed_shotgun_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"
metadata_2022_washed_shotgun_full_SP.loc[is_mystery, "BS"] = "BS_MYSTRY_X_0"
metadata_2022_washed_shotgun_full_SP.loc[is_des, "BS"] = "BS_DESCTL_X_0"
metadata_2022_washed_shotgun_full_SP.loc[is_pbs, "BS"] = "BS_PBSCTL_X_0"

metadata_2022_washed_shotgun_full_SP.loc[is_contaminated, "BS"] = "BS_CONTAM_X_0"



metadata_2022_washed_shotgun_full_SP["LY_SP_BS"]=metadata_2022_washed_shotgun_full_SP["LY"] + "__" + metadata_2022_washed_shotgun_full_SP["SP"]+ "__"  +metadata_2022_washed_shotgun_full_SP["BS"] 
metadata_2022_washed_shotgun_full_SP["LY_SP_BS_EX"]=metadata_2022_washed_shotgun_full_SP["LY_SP_BS"] + "__"  +metadata_2022_washed_shotgun_full_SP["EX"] 
metadata_2022_washed_shotgun_full_SP["LY_SP_BS_EX_LP"]=metadata_2022_washed_shotgun_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2022_washed_shotgun_full_SP["LP"] 


metadata_2022_washed_shotgun_full_SP.to_csv("test.csv")


print(len(metadata_2022_washed_shotgun_full))
print(len(metadata_2022_washed_shotgun_full_SP))
metadata_2022_washed_shotgun_full_SP

# metadata_2022_washed_shotgun_full_SP[~metadata_2022_washed_shotgun_full_SP["SP"].isna()].groupby("SP").count()

315
315

,bio_sample_ID,sample_date,sample_type,block,plot,subplot,ID_on_field,spray,fertiliser,cultivar,...,SP_lane,SP_parcel,SP_location,triplicate,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,R-040722-s-9G,2022-07-04,timeline,NaN,9.0,NaN,B5,n,NaN,kvium,...,7.0,15.0,R,0.0,BS_220704_W_1,EX_221121,LP_221212_WGS,LY_R_2022__SP_009__BS_220704_W_1,LY_R_2022__SP_009__BS_220704_W_1__EX_221121,LY_R_2022__SP_009__BS_220704_W_1__EX_221121__L...
1,R-040722-s-10G,2022-07-04,timeline,NaN,10.0,NaN,A7,y,NaN,heerup,...,8.0,1.0,R,0.0,BS_220704_W_1,EX_221027,LP_221212_WGS,LY_R_2022__SP_010__BS_220704_W_1,LY_R_2022__SP_010__BS_220704_W_1__EX_221027,LY_R_2022__SP_010__BS_220704_W_1__EX_221027__L...
2,R-040722-s-11G,2022-07-04,timeline,NaN,11.0,NaN,A16,y,NaN,rembrandt,...,8.0,5.0,R,0.0,BS_220704_W_1,EX_221121,LP_221212_WGS,LY_R_2022__SP_011__BS_220704_W_1,LY_R_2022__SP_011__BS_220704_W_1__EX_221121,LY_R_2022__SP_011__BS_220704_W_1__EX_221121__L...
3,R-040722-s-12G,2022-07-04,timeline,NaN,12.0,NaN,A5,y,NaN,kvium,...,8.0,21.0,R,0.0,BS_220704_W_1,EX_221027,LP_221212_WGS,LY_R_2022__SP_012__BS_220704_W_1,LY_R_2022__SP_012__BS_220704_W_1__EX_221027,LY_R_2022__SP_012__BS_220704_W_1__EX_221027__L...
4,R-040722-s-15G,2022-07-04,timeline,NaN,15.0,NaN,A16,y,NaN,rembrandt,...,9.0,26.0,R,0.0,BS_220704_W_1,EX_221125,LP_221213_WGS,LY_R_2022__SP_015__BS_220704_W_1,LY_R_2022__SP_015__BS_220704_W_1__EX_221125,LY_R_2022__SP_015__BS_220704_W_1__EX_221125__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,BS_ULWCTL_X_0,EX_000000,LP_221213_WGS,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
311,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,BS_ULWCTL_X_0,EX_000000,LP_221213_WGS,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
312,DES,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,BS_DESCTL_X_0,EX_000000,LP_230111_WGS,LY_X_0000__SP_000__BS_DESCTL_X_0,LY_X_0000__SP_000__BS_DESCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_DESCTL_X_0__EX_000000__L...
313,1xPBS,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,BS_PBSCTL_X_0,EX_000000,LP_230111_WGS,LY_X_0000__SP_000__BS_PBSCTL_X_0,LY_X_0000__SP_000__BS_PBSCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_PBSCTL_X_0__EX_000000__L...
314,1xPBS,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,BS_PBSCTL_X_0,EX_000000,LP_230111_WGS,LY_X_0000__SP_000__BS_PBSCTL_X_0,LY_X_0000__SP_000__BS_PBSCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_PBSCTL_X_0__EX_000000__L...

## WASHED AMP 2022

In [56]:

print("Number of samples: "  + str(len(metadata_2022_washed_amplicon)))
print("Number of sequence runs: "  + str(metadata_2022_washed_amplicon["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
print(len(metadata_2022_washed_amplicon["run_ID"]))
metadata_2022_washed_amplicon["run_ID"].value_counts()

Number of samples: 2252
Number of sequence runs: 2146

Number of sequence runs per folder:
2252

run_ID
seq240424_T6U6R    344
seq240412_BRLUV    342
seq231206_RISO2    340
seq240209_KSVAZ    337
seq240222_RQS8X    314
seq240508_LNERQ    245
seq231107_RISO1    224
Name: count, dtype: int64

In [57]:
# Merge two DataFrames (metadata_2022_washed_amplicon and df_folder_structure) 
# on the columns "run_ID" and "dir_name" respectively, keeping all rows from metadata_2022_washed_amplicon 
# (left join).
metadata_2022_washed_amplicon_full = metadata_2022_washed_amplicon.merge(
    df_folder_structure, left_on="run_ID", right_on="dir_name", how="left"
)

# Filter rows to keep only those where the "seq_sample_ID" column is not NaN.
metadata_2022_washed_amplicon_full = metadata_2022_washed_amplicon_full[
    metadata_2022_washed_amplicon_full["seq_sample_ID"].notna()
]

# Create a new column "suggested_correct_seq_sample_ID". If "correct_seq_sample_ID" is NaN,
# it will use the value from "seq_sample_ID", otherwise, it uses "correct_seq_sample_ID".
metadata_2022_washed_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_2022_washed_amplicon_full['correct_seq_sample_ID'].fillna(
        metadata_2022_washed_amplicon_full['seq_sample_ID']
    )

# Replace underscores with hyphens and remove the prefix "washed-1-" from the values in 
# the "suggested_correct_seq_sample_ID" column.
metadata_2022_washed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2022_washed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-")
metadata_2022_washed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2022_washed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("washed-1-", "")

# Sort the DataFrame by the "run_ID" column in ascending order.
metadata_2022_washed_amplicon_full = metadata_2022_washed_amplicon_full.sort_values("run_ID")

# End of code, the resulting DataFrame is assigned to metadata_2022_washed_amplicon_full.
metadata_2022_washed_amplicon_full

,bio_sample_ID,plot,letter,cultivar,spray,washed_date,DNA_plate_number,DNA_ext_date,Days_between_DNA_x,DNA_conc_individual,...,run_ID,note,correct_seq_sample_ID,YEAR,LEAF_PROTOCOL,LIBRARY_PREPARATION,Unnamed: 0,dir_name,full_path,suggested_correct_seq_sample_ID
2251,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,seq231107_RISO1,Error_SampleID_in_seq_run_says_2023_not_2022_'...,mix-2022-ITS-w-P14-pos,2022,WASHED,amplicon,14.0,seq231107_RISO1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,mix-2022-ITS-w-P14-pos
625,S-240622-w-13-4,13.0,A5,kvium,n,2023-02-24,4.0,2023-02-28,4.0,NaN,...,seq231107_RISO1,Error_seqSampleID_'washed-1-',S-240622-ITS-w-13-4,2022,WASHED,amplicon,14.0,seq231107_RISO1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,S-240622-ITS-w-13-4
626,S-240622-w-13-5,13.0,A5,kvium,n,2023-02-24,4.0,2023-02-28,4.0,NaN,...,seq231107_RISO1,Error_seqSampleID_'washed-1-',S-240622-ITS-w-13-5,2022,WASHED,amplicon,14.0,seq231107_RISO1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,S-240622-ITS-w-13-5
627,S-240622-w-13-6,13.0,A5,kvium,n,2023-02-24,4.0,2023-02-28,4.0,NaN,...,seq231107_RISO1,Error_seqSampleID_'washed-1-',S-240622-ITS-w-13-6,2022,WASHED,amplicon,14.0,seq231107_RISO1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,S-240622-ITS-w-13-6
628,S-240622-w-13-7,13.0,A5,kvium,n,2023-02-24,4.0,2023-02-28,4.0,NaN,...,seq231107_RISO1,Error_seqSampleID_'washed-1-',S-240622-ITS-w-13-7,2022,WASHED,amplicon,14.0,seq231107_RISO1,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,S-240622-ITS-w-13-7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2058,R-210622-w-21-1,21.0,B7,Heerup,n,2023-03-10,13.0,2023-03-28,18.0,NaN,...,seq240508_LNERQ,NaN,NaN,2022,WASHED,amplicon,10.0,seq240508_LNERQ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-w-21-1
2057,R-210622-w-20-7,20.0,A7,Heerup,y,2023-03-10,13.0,2023-03-28,18.0,NaN,...,seq240508_LNERQ,NaN,NaN,2022,WASHED,amplicon,10.0,seq240508_LNERQ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-w-20-7
2056,R-210622-w-20-6,20.0,A7,Heerup,y,2023-03-10,13.0,2023-03-28,18.0,NaN,...,seq240508_LNERQ,DNA_input_below_100pg,NaN,2022,WASHED,amplicon,10.0,seq240508_LNERQ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-w-20-6
2062,R-210622-w-21-5,21.0,B7,Heerup,n,2023-03-10,13.0,2023-03-28,18.0,NaN,...,seq240508_LNERQ,NaN,NaN,2022,WASHED,amplicon,10.0,seq240508_LNERQ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-w-21-5
2028,R-210622-w-16-6,16.0,B16,Rembrandt,n,2023-03-10,13.0,2023-03-27,17.0,NaN,...,seq240508_LNERQ,NaN,NaN,2022,WASHED,amplicon,10.0,seq240508_LNERQ,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-210622-16S-w-16-6

In [58]:
# Iterate over each row and print files
metadata_2022_washed_amplicon_full["forward_fq"]=""
metadata_2022_washed_amplicon_full["reverse_fq"]=""
metadata_2022_washed_amplicon_full["current_seq_sample_ID"]=""
metadata_2022_washed_amplicon_full["corrected_forward_fq"]=""
metadata_2022_washed_amplicon_full["corrected_reverse_fq"]=""

total_rows = len(metadata_2022_washed_amplicon_full)  # Get the total number of rows
n=0
for index, row in metadata_2022_washed_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID = row['suggested_correct_seq_sample_ID']

        # Check if the number of matching files is not equal to 2
        if len(matching_files) == 2:
            metadata_2022_washed_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2022_washed_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2022_washed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2022_washed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2022_washed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2

        else:
            prefix2 = prefix.replace("washed-1-", "").replace("-", "_")
            matching_files2 = list_files_with_prefix(folder_path, prefix2)

            if len(matching_files2) == 2:
                metadata_2022_washed_amplicon_full.loc[index, "forward_fq"] = matching_files2[0]
                metadata_2022_washed_amplicon_full.loc[index, "reverse_fq"] = matching_files2[1]
                ending_R1= "_S" + re.search(r"_S(\d+)", matching_files2[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files2[0])[1]
                ending_R2= "_S" + re.search(r"_S(\d+)", matching_files2[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files2[1])[1]
                metadata_2022_washed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files2[0].split("/")[-1])[0]
                metadata_2022_washed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
                metadata_2022_washed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2
            
        

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")
    
    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1

# After the loop, print 100% to indicate completion
print("\nProcessing complete!")

Processing... 100.00% complete
Processing complete!

In [59]:
# Define a list of columns to be moved to the end
columns_to_move = ["current_seq_sample_ID", "correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]

# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2022_washed_amplicon_full = metadata_2022_washed_amplicon_full[
    [col for col in metadata_2022_washed_amplicon_full.columns if col not in columns_to_move] + columns_to_move
]

# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_2022_washed_amplicon_full['forward_fq'] = metadata_2022_washed_amplicon_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_2022_washed_amplicon_full['reverse_fq'] = metadata_2022_washed_amplicon_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2022_washed_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2022_washed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2022_washed_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2022_washed_amplicon_full["ALREADY_CORRECT"] = metadata_2022_washed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2022_washed_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2022_washed_amplicon_full = metadata_2022_washed_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])

# Save the resulting DataFrame to a CSV file named 'test_metadata_15_11_2024.csv'
metadata_2022_washed_amplicon_full

,bio_sample_ID,plot,letter,cultivar,spray,washed_date,DNA_plate_number,DNA_ext_date,Days_between_DNA_x,DNA_conc_individual,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
720,S-240622-w-15-3,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,Washed_S-240622-ITS-w-15-3_S9_L001_R1_001.fast...,Washed_S-240622-ITS-w-15-3_S9_L001_R2_001.fast...,S-240622-ITS-w-15-3_S9_L001_R1_001.fastq.gz,S-240622-ITS-w-15-3_S9_L001_R2_001.fastq.gz,Washed_S-240622-ITS-w-15-3,NaN,S-240622-ITS-w-15-3,False,False
719,S-240622-w-15-2,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,Washed_S-240622-ITS-w-15-2_S8_L001_R1_001.fast...,Washed_S-240622-ITS-w-15-2_S8_L001_R2_001.fast...,S-240622-ITS-w-15-2_S8_L001_R1_001.fastq.gz,S-240622-ITS-w-15-2_S8_L001_R2_001.fastq.gz,Washed_S-240622-ITS-w-15-2,NaN,S-240622-ITS-w-15-2,False,False
718,S-240622-w-15-1,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,Washed_S-240622-ITS-w-15-1_S7_L001_R1_001.fast...,Washed_S-240622-ITS-w-15-1_S7_L001_R2_001.fast...,S-240622-ITS-w-15-1_S7_L001_R1_001.fastq.gz,S-240622-ITS-w-15-1_S7_L001_R2_001.fastq.gz,Washed_S-240622-ITS-w-15-1,NaN,S-240622-ITS-w-15-1,False,False
717,S-240622-w-14-7,14.0,A7,heerup,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,Washed_S-240622-ITS-w-14-7_S6_L001_R1_001.fast...,Washed_S-240622-ITS-w-14-7_S6_L001_R2_001.fast...,S-240622-ITS-w-14-7_S6_L001_R1_001.fastq.gz,S-240622-ITS-w-14-7_S6_L001_R2_001.fastq.gz,Washed_S-240622-ITS-w-14-7,NaN,S-240622-ITS-w-14-7,False,False
716,S-240622-w-14-6,14.0,A7,heerup,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,Washed_S-240622-ITS-w-14-6_S5_L001_R1_001.fast...,Washed_S-240622-ITS-w-14-6_S5_L001_R2_001.fast...,S-240622-ITS-w-14-6_S5_L001_R1_001.fastq.gz,S-240622-ITS-w-14-6_S5_L001_R2_001.fastq.gz,Washed_S-240622-ITS-w-14-6,NaN,S-240622-ITS-w-14-6,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,Ultrapure-water,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,H-2023-16S-w-P6-neg_S166_L001_R1_001.fastq.gz,H-2023-16S-w-P6-neg_S166_L001_R2_001.fastq.gz,H-2022-16S-w-P6-neg_S166_L001_R1_001.fastq.gz,H-2022-16S-w-P6-neg_S166_L001_R2_001.fastq.gz,H-2023-16S-w-P6-neg,H-2022-16S-w-P6-neg,H-2022-16S-w-P6-neg,True,False
1384,A-230623-w-23-1,23.0,A16,rembrandt,n,2023-08-01,9.0,2023-08-08,7.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,A-230623-16S-w-22-1_S63_L001_R1_001.fastq.gz,A-230623-16S-w-22-1_S63_L001_R2_001.fastq.gz,A-230622-16S-w-23-1_S63_L001_R1_001.fastq.gz,A-230622-16S-w-23-1_S63_L001_R2_001.fastq.gz,A-230623-16S-w-22-1,A-230622-16S-w-23-1,A-230622-16S-w-23-1,True,False
1728,L-230623-w-22-1,23.0,A5,Kvium,y,2023-07-11,11.0,2023-07-24,13.0,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,L-230623-16S-w-22-1_S65_L001_R1_001.fastq.gz,L-230623-16S-w-22-1_S65_L001_R2_001.fastq.gz,L-230622-16S-w-23-1_S65_L001_R1_001.fastq.gz,L-230622-16S-w-23-1_S65_L001_R2_001.fastq.gz,L-230623-16S-w-22-1,L-230622-16S-w-23-1,L-230622-16S-w-23-1,True,False
375,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-2022-ITS-w-P2-pos_S2_L001_R1_001.fastq.gz,R-2022-ITS-w-P2-pos_S2_L001_R2_001.fastq.gz,R-2022-ITS-w-P2-pos_S2_L001_R1_001.fastq.gz,R-2022-ITS-w-P2-pos_S2_L001_R2_001.fastq.gz,R-2022-ITS-w-P2-pos,R-2022-ITS-w-P2-pos,R-2022-ITS-w-P2-pos,True,True
374,Ultrapure-water,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-2022-ITS-w-P2-neg_S1_L001_R1_001.fastq.gz,R-2022-ITS-w-P2-neg_S1_L001_R2_001.fastq.gz,R-2022-ITS-w-P2-neg_S1_L001_R1_001.fastq.gz,R-2022-ITS-w-P2-neg_S1_L001_R2_001.fastq.gz,R-2022-ITS-w-P2-neg,R-2022-ITS-w-P2-neg,R-2022-ITS-w-P2-neg,True,True

In [ ]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]
metadata_2022_washed_amplicon_full["location"]=metadata_2022_washed_amplicon_full["bio_sample_ID"].str.replace("_", "-").str.split("-").str[0]
metadata_2022_washed_amplicon_full["sample_date"]=metadata_2022_washed_amplicon_full["bio_sample_ID"].str.replace("_", "-").str.split("-").str[1]
metadata_2022_washed_amplicon_full["PCR1_date"]=metadata_2022_washed_amplicon_full["PCR1_date"].str.replace("unknown", "")

metadata_2022_washed_amplicon_full_SP=metadata_2022_washed_amplicon_full.merge(pd.concat([SP_0000, SP_2022]), left_on=["plot", "location"], right_on=["SP_plot", "SP_location"], how="left")#.to_csv("test.csv")

metadata_2022_washed_amplicon_full_SP["triplicate"] = (metadata_2022_washed_amplicon_full_SP["bio_sample_ID"].str.split("-").str[4].fillna(0)).astype(str)
metadata_2022_washed_amplicon_full_SP["BS"] = (
    "BS_" + metadata_2022_washed_amplicon_full_SP["sample_date"] + 
	 "_" + metadata_2022_washed_amplicon_full_SP["LEAF_PROTOCOL"].str[0] + "_1" )

metadata_2022_washed_amplicon_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2022_washed_amplicon_full_SP["DNA_ext_date"], errors="coerce")
      .dt.strftime("%y%m%d")
      .fillna("000000"))


## TODO fix 29 FEB 2023

metadata_2022_washed_amplicon_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2022_washed_amplicon_full_SP["PCR2_date"], errors="coerce")
    .dt.strftime("%y%m%d") + "_"+ metadata_2022_washed_amplicon_full_SP["amplicon"] )



# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2022_washed_amplicon_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2022_washed_amplicon_full_SP[id_col].eq("alex-control")
is_water = metadata_2022_washed_amplicon_full_SP[id_col].eq("Ultrapure-water")
is_mystery= metadata_2022_washed_amplicon_full_SP[id_col].eq("T-150621-c-mystery")
is_des= metadata_2022_washed_amplicon_full_SP[id_col].eq("DES")
is_pbs= metadata_2022_washed_amplicon_full_SP[id_col].eq("1xPBS")
is_contaminated= metadata_2022_washed_amplicon_full_SP[id_col].eq("contaminated-well")

control_mask = is_zymo | is_alex | is_water | is_des | is_pbs

# LY and SP fixed for all three
metadata_2022_washed_amplicon_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2022_washed_amplicon_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2022_washed_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2022_washed_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"

metadata_2022_washed_amplicon_full_SP.loc[control_mask, "LY_SP"] = (metadata_2022_washed_amplicon_full_SP.loc[control_mask, "LY"] + "__" + metadata_2022_washed_amplicon_full_SP.loc[control_mask, "SP"])


metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "LY"] = "LY_Z_0000"
metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "SP"] = "SP_000"
metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "EX"] = "EX_000000"
metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "LY_SP"] = (metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "SP"])


metadata_2022_washed_amplicon_full_SP.loc[is_contaminated, "LY"] = "LY_Z_0000"
metadata_2022_washed_amplicon_full_SP.loc[is_contaminated, "SP"] = "SP_000"
metadata_2022_washed_amplicon_full_SP.loc[is_contaminated, "EX"] = "EX_000000"
metadata_2022_washed_amplicon_full_SP.loc[is_contaminated, "LY_SP"] = (metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "SP"])


# BS depends on which control
metadata_2022_washed_amplicon_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2022_washed_amplicon_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2022_washed_amplicon_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"
metadata_2022_washed_amplicon_full_SP.loc[is_mystery, "BS"] = "BS_MYSTRY_X_0"
metadata_2022_washed_amplicon_full_SP.loc[is_des, "BS"] = "BS_DESCTL_X_0"
metadata_2022_washed_amplicon_full_SP.loc[is_pbs, "BS"] = "BS_PBSCTL_X_0"

metadata_2022_washed_amplicon_full_SP.loc[is_contaminated, "BS"] = "BS_CONTAM_X_0"



metadata_2022_washed_amplicon_full_SP["LY_SP_BS"]=metadata_2022_washed_amplicon_full_SP["LY"] + "__" + metadata_2022_washed_amplicon_full_SP["SP"]+ "__"  +metadata_2022_washed_amplicon_full_SP["BS"] 
metadata_2022_washed_amplicon_full_SP["LY_SP_BS_EX"]=metadata_2022_washed_amplicon_full_SP["LY_SP_BS"] + "__"  +metadata_2022_washed_amplicon_full_SP["EX"] 
metadata_2022_washed_amplicon_full_SP["LY_SP_BS_EX_LP"]=metadata_2022_washed_amplicon_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2022_washed_amplicon_full_SP["LP"] 


metadata_2022_washed_amplicon_full_SP.to_csv("test.csv")


print(len(metadata_2022_washed_amplicon_full))
print(len(metadata_2022_washed_amplicon_full_SP))
metadata_2022_washed_amplicon_full_SP

# metadata_2022_washed_amplicon_full_SP[~metadata_2022_washed_amplicon_full_SP["SP"].isna()].groupby("SP").count()

2139
2139

,bio_sample_ID,plot,letter,cultivar,spray,washed_date,DNA_plate_number,DNA_ext_date,Days_between_DNA_x,DNA_conc_individual,...,SP_lane,SP_parcel,SP_location,triplicate,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,S-240622-w-15-3,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,47.0,S,3,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_015__BS_240622_W_1,LY_S_2022__SP_015__BS_240622_W_1__EX_230228,LY_S_2022__SP_015__BS_240622_W_1__EX_230228__L...
1,S-240622-w-15-2,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,47.0,S,2,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_015__BS_240622_W_1,LY_S_2022__SP_015__BS_240622_W_1__EX_230228,LY_S_2022__SP_015__BS_240622_W_1__EX_230228__L...
2,S-240622-w-15-1,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,47.0,S,1,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_015__BS_240622_W_1,LY_S_2022__SP_015__BS_240622_W_1__EX_230228,LY_S_2022__SP_015__BS_240622_W_1__EX_230228__L...
3,S-240622-w-14-7,14.0,A7,heerup,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,39.0,S,7,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_014__BS_240622_W_1,LY_S_2022__SP_014__BS_240622_W_1__EX_230228,LY_S_2022__SP_014__BS_240622_W_1__EX_230228__L...
4,S-240622-w-14-6,14.0,A7,heerup,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,39.0,S,6,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_014__BS_240622_W_1,LY_S_2022__SP_014__BS_240622_W_1__EX_230228,LY_S_2022__SP_014__BS_240622_W_1__EX_230228__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134,Ultrapure-water,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_240304_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
2135,A-230623-w-23-1,23.0,A16,rembrandt,n,2023-08-01,9.0,2023-08-08,7.0,NaN,...,4.0,77.0,A,1,BS_230623_W_1,EX_230808,LP_240314_16S,LY_A_2022__SP_023__BS_230623_W_1,LY_A_2022__SP_023__BS_230623_W_1__EX_230808,LY_A_2022__SP_023__BS_230623_W_1__EX_230808__L...
2136,L-230623-w-22-1,23.0,A5,Kvium,y,2023-07-11,11.0,2023-07-24,13.0,NaN,...,4.0,79.0,L,1,BS_230623_W_1,EX_230724,LP_240112_16S,LY_L_2022__SP_023__BS_230623_W_1,LY_L_2022__SP_023__BS_230623_W_1__EX_230724,LY_L_2022__SP_023__BS_230623_W_1__EX_230724__L...
2137,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_240417_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
2138,Ultrapure-water,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_240417_ITS,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...

In [63]:
parsed_dates = pd.to_datetime(
    metadata_2022_washed_amplicon_full_SP["PCR1_date"],
    format="%d/%m/%y",
    errors="coerce"
)
bad_dates_df = metadata_2022_washed_amplicon_full_SP[parsed_dates.isna()]
bad_dates_df

,bio_sample_ID,plot,letter,cultivar,spray,washed_date,DNA_plate_number,DNA_ext_date,Days_between_DNA_x,DNA_conc_individual,...,SP_lane,SP_parcel,SP_location,triplicate,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,S-240622-w-15-3,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,47.0,S,3,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_015__BS_240622_W_1,LY_S_2022__SP_015__BS_240622_W_1__EX_230228,LY_S_2022__SP_015__BS_240622_W_1__EX_230228__L...
1,S-240622-w-15-2,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,47.0,S,2,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_015__BS_240622_W_1,LY_S_2022__SP_015__BS_240622_W_1__EX_230228,LY_S_2022__SP_015__BS_240622_W_1__EX_230228__L...
2,S-240622-w-15-1,15.0,A16,rembrandt,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,47.0,S,1,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_015__BS_240622_W_1,LY_S_2022__SP_015__BS_240622_W_1__EX_230228,LY_S_2022__SP_015__BS_240622_W_1__EX_230228__L...
3,S-240622-w-14-7,14.0,A7,heerup,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,39.0,S,7,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_014__BS_240622_W_1,LY_S_2022__SP_014__BS_240622_W_1__EX_230228,LY_S_2022__SP_014__BS_240622_W_1__EX_230228__L...
4,S-240622-w-14-6,14.0,A7,heerup,n,2023-02-24,5.0,2023-02-28,4.0,NaN,...,5.0,39.0,S,6,BS_240622_W_1,EX_230228,LP_230829_ITS,LY_S_2022__SP_014__BS_240622_W_1,LY_S_2022__SP_014__BS_240622_W_1__EX_230228,LY_S_2022__SP_014__BS_240622_W_1__EX_230228__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134,Ultrapure-water,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_240304_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
2135,A-230623-w-23-1,23.0,A16,rembrandt,n,2023-08-01,9.0,2023-08-08,7.0,NaN,...,4.0,77.0,A,1,BS_230623_W_1,EX_230808,LP_240314_16S,LY_A_2022__SP_023__BS_230623_W_1,LY_A_2022__SP_023__BS_230623_W_1__EX_230808,LY_A_2022__SP_023__BS_230623_W_1__EX_230808__L...
2136,L-230623-w-22-1,23.0,A5,Kvium,y,2023-07-11,11.0,2023-07-24,13.0,NaN,...,4.0,79.0,L,1,BS_230623_W_1,EX_230724,LP_240112_16S,LY_L_2022__SP_023__BS_230623_W_1,LY_L_2022__SP_023__BS_230623_W_1__EX_230724,LY_L_2022__SP_023__BS_230623_W_1__EX_230724__L...
2137,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_240417_ITS,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
2138,Ultrapure-water,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_240417_ITS,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...

## SHOT AMP 2022

In [65]:
print("Number of samples: "  + str(len(metadata_2022_washed_shotgun_amplicon)))
print("Number of sequence runs: "  + str(metadata_2022_washed_shotgun_amplicon["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2022_washed_shotgun_amplicon["run_ID"].value_counts()

Number of samples: 148
Number of sequence runs: 144

Number of sequence runs per folder:

run_ID
seq230714_FWU63    72
seq230710_GW4I8    72
Name: count, dtype: int64

In [66]:
metadata_2022_washed_shotgun_amplicon_full=metadata_2022_washed_shotgun_amplicon.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2022_washed_shotgun_amplicon_full=metadata_2022_washed_shotgun_amplicon_full[metadata_2022_washed_shotgun_amplicon_full["seq_sample_ID"].notna()]
metadata_2022_washed_shotgun_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_2022_washed_shotgun_amplicon_full['correct_seq_sample_ID'].fillna(metadata_2022_washed_shotgun_amplicon_full['seq_sample_ID'])
metadata_2022_washed_shotgun_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2022_washed_shotgun_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "")
metadata_2022_washed_shotgun_amplicon_full=metadata_2022_washed_shotgun_amplicon_full.sort_values("run_ID")

In [67]:


# Iterate over each row and print files
metadata_2022_washed_shotgun_amplicon_full["forward_fq"]=""
metadata_2022_washed_shotgun_amplicon_full["reverse_fq"]=""
metadata_2022_washed_shotgun_amplicon_full["current_seq_sample_ID"]=""
metadata_2022_washed_shotgun_amplicon_full["corrected_forward_fq"]=""
metadata_2022_washed_shotgun_amplicon_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2022_washed_shotgun_amplicon_full)  # Get the total number of rows

for index, row in metadata_2022_washed_shotgun_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        if len(matching_files) == 2:
            metadata_2022_washed_shotgun_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2022_washed_shotgun_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2022_washed_shotgun_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2022_washed_shotgun_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2022_washed_shotgun_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2


        if len(matching_files) >2:    
            grouped_files = defaultdict(list)
            
            # Loop over each file and group by the part before R1/R2
            for file in matching_files:
                # Split the file name at R1 or R2
                base_name = file.split("/")[-1].rsplit("_R", 1)[0]  # Split from the last occurrence of "_R"
                grouped_files[base_name].append(file.split("/")[-1])
            
            metadata_2022_washed_shotgun_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", grouped_files[base_name][0].split("/")[-1])[0]
     
            
            # Print the grouped files
            m=0
            for base_name, files in grouped_files.items():      
                if len(files)==2:
            
                    if m==0:
                        # print(grouped_files[base_name][0])
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "forward_fq"] = [grouped_files[base_name][0]]
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "reverse_fq"] = [grouped_files[base_name][1]]
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "corrected_forward_fq"] = [correct_seq_sample_ID + ending_R1]
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "corrected_reverse_fq"] = [correct_seq_sample_ID + ending_R2]
            
            
                    else:
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "forward_fq"].append(grouped_files[base_name][0])
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "reverse_fq"].append(grouped_files[base_name][1])
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "corrected_forward_fq"].append(correct_seq_sample_ID + ending_R1)
                        metadata_2022_washed_shotgun_amplicon_full.loc[index, "corrected_reverse_fq"].append(correct_seq_sample_ID + ending_R2)
            
                
                    m=m+1
                else:
                    print("ERROR", base_name, files)

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1
    
# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

# TODO 
# ERROR washed-1-R-040722-s-24G_S145_L001 ['washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz']
# ERROR washed-1-R-040722-s-24G_S145_L001 ['washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz']

ERROR washed-1-R-040722-s-24G_S145_L001 ['washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz']
ERROR washed-1-R-040722-s-24G_S145_L001 ['washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R1_001.fastq.gz', 'washed-1-R-040722-s-24G_S145_L001_R2_001.fastq.gz']
Processing... 100.00% complete
Processing complete!

In [68]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2022_washed_shotgun_amplicon_full = metadata_2022_washed_shotgun_amplicon_full[
    [col for col in metadata_2022_washed_shotgun_amplicon_full.columns if col not in columns_to_move] + columns_to_move]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2022_washed_shotgun_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2022_washed_shotgun_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2022_washed_shotgun_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2022_washed_shotgun_amplicon_full["ALREADY_CORRECT"] = metadata_2022_washed_shotgun_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2022_washed_shotgun_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2022_washed_shotgun_amplicon_full = metadata_2022_washed_shotgun_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2022_washed_shotgun_amplicon_full

,bio_sample_ID,sample_date,sample_type,block,Plot,subplot,ID_on_field,spray,fertilizer,Cultivar,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
75,R-040722-s-2G,2022-07-04,timeline,NaN,2.0,NaN,A7,yes,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-2G_S77_L001_R1_001.fastq.gz,R-040722-ITS-s-2G_S77_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-2G,NaN,R-040722-ITS-s-2G,False,False
76,R-040722-s-3G,2022-07-04,timeline,NaN,3.0,NaN,B5,no,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-3G_S80_L001_R1_001.fastq.gz,R-040722-ITS-s-3G_S80_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-3G,NaN,R-040722-ITS-s-3G,False,False
77,R-040722-s-4G,2022-07-04,timeline,NaN,4.0,NaN,B7,no,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-4G_S83_L001_R1_001.fastq.gz,R-040722-ITS-s-4G_S83_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-4G,NaN,R-040722-ITS-s-4G,False,False
78,R-040722-s-5G,2022-07-04,timeline,NaN,5.0,NaN,B16,no,NaN,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-5G_S86_L001_R1_001.fastq.gz,R-040722-ITS-s-5G_S86_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-5G,NaN,R-040722-ITS-s-5G,False,False
79,R-040722-s-6G,2022-07-04,timeline,NaN,6.0,NaN,A5,yes,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-6G_S89_L001_R1_001.fastq.gz,R-040722-ITS-s-6G_S89_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-6G,NaN,R-040722-ITS-s-6G,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,R-070722-s-22H,2022-07-07,timeline,NaN,22.0,NaN,B5,no,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-22H_S193_L001_R1_001.fastq.gz, R-07...","[R-07072-s-22H_S193_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-22H_S193_L001_R1_001.fastq.gz,...","[R-070722-16S-s-22H_S193_L001_R2_001.fastq.gz,...",16S-R-07072-s-22H,R-070722-16S-s-22H,R-070722-16S-s-22H,True,False
46,R-070722-s-23H,2022-07-07,timeline,NaN,23.0,NaN,B16,no,NaN,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-23H_S201_L001_R1_001.fastq.gz, R-07...","[R-07072-s-23H_S201_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-23H_S201_L001_R1_001.fastq.gz,...","[R-070722-16S-s-23H_S201_L001_R2_001.fastq.gz,...",16S-R-07072-s-23H,R-070722-16S-s-23H,R-070722-16S-s-23H,True,False
47,R-070722-s-24H,2022-07-07,timeline,NaN,24.0,NaN,A5,yes,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-24H_S210_L001_R1_001.fastq.gz, R-07...","[R-07072-s-24H_S210_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-24H_S210_L001_R1_001.fastq.gz,...","[R-070722-16S-s-24H_S210_L001_R2_001.fastq.gz,...",16S-R-07072-s-24H,R-070722-16S-s-24H,R-070722-16S-s-24H,True,False
44,R-070722-s-21H,2022-07-07,timeline,NaN,21.0,NaN,B7,no,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-21H_S184_L001_R1_001.fastq.gz, R-07...","[R-07072-s-21H_S184_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-21H_S184_L001_R1_001.fastq.gz,...","[R-070722-16S-s-21H_S184_L001_R2_001.fastq.gz,...",16S-R-07072-s-21H,R-070722-16S-s-21H,R-070722-16S-s-21H,True,False
73,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-000022-16S-s-P1-pos_S149_L001_R1_001.fastq.gz,R-000022-16S-s-P1-pos_S149_L001_R2_001.fastq.gz,16S-R-s-pos,R-000022-16S-s-P1-pos,R-000022-16S-s-P1-pos,True,False

In [69]:
filtered_metadata_2022_washed_shotgun_amplicon_full=metadata_2022_washed_shotgun_amplicon_full[
    metadata_2022_washed_shotgun_amplicon_full.apply(
        lambda row: row['amplicon'] not in row['suggested_correct_seq_sample_ID'], axis=1
    )
]
metadata_2022_washed_shotgun_amplicon_full

,bio_sample_ID,sample_date,sample_type,block,Plot,subplot,ID_on_field,spray,fertilizer,Cultivar,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
75,R-040722-s-2G,2022-07-04,timeline,NaN,2.0,NaN,A7,yes,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-2G_S77_L001_R1_001.fastq.gz,R-040722-ITS-s-2G_S77_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-2G,NaN,R-040722-ITS-s-2G,False,False
76,R-040722-s-3G,2022-07-04,timeline,NaN,3.0,NaN,B5,no,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-3G_S80_L001_R1_001.fastq.gz,R-040722-ITS-s-3G_S80_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-3G,NaN,R-040722-ITS-s-3G,False,False
77,R-040722-s-4G,2022-07-04,timeline,NaN,4.0,NaN,B7,no,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-4G_S83_L001_R1_001.fastq.gz,R-040722-ITS-s-4G_S83_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-4G,NaN,R-040722-ITS-s-4G,False,False
78,R-040722-s-5G,2022-07-04,timeline,NaN,5.0,NaN,B16,no,NaN,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-5G_S86_L001_R1_001.fastq.gz,R-040722-ITS-s-5G_S86_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-5G,NaN,R-040722-ITS-s-5G,False,False
79,R-040722-s-6G,2022-07-04,timeline,NaN,6.0,NaN,A5,yes,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-040722-ITS-s-6G_S89_L001_R1_001.fastq.gz,R-040722-ITS-s-6G_S89_L001_R2_001.fastq.gz,ITS-R-040722-ITS-s-6G,NaN,R-040722-ITS-s-6G,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,R-070722-s-22H,2022-07-07,timeline,NaN,22.0,NaN,B5,no,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-22H_S193_L001_R1_001.fastq.gz, R-07...","[R-07072-s-22H_S193_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-22H_S193_L001_R1_001.fastq.gz,...","[R-070722-16S-s-22H_S193_L001_R2_001.fastq.gz,...",16S-R-07072-s-22H,R-070722-16S-s-22H,R-070722-16S-s-22H,True,False
46,R-070722-s-23H,2022-07-07,timeline,NaN,23.0,NaN,B16,no,NaN,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-23H_S201_L001_R1_001.fastq.gz, R-07...","[R-07072-s-23H_S201_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-23H_S201_L001_R1_001.fastq.gz,...","[R-070722-16S-s-23H_S201_L001_R2_001.fastq.gz,...",16S-R-07072-s-23H,R-070722-16S-s-23H,R-070722-16S-s-23H,True,False
47,R-070722-s-24H,2022-07-07,timeline,NaN,24.0,NaN,A5,yes,NaN,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-24H_S210_L001_R1_001.fastq.gz, R-07...","[R-07072-s-24H_S210_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-24H_S210_L001_R1_001.fastq.gz,...","[R-070722-16S-s-24H_S210_L001_R2_001.fastq.gz,...",16S-R-07072-s-24H,R-070722-16S-s-24H,R-070722-16S-s-24H,True,False
44,R-070722-s-21H,2022-07-07,timeline,NaN,21.0,NaN,B7,no,NaN,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[R-07072-s-21H_S184_L001_R1_001.fastq.gz, R-07...","[R-07072-s-21H_S184_L001_R2_001.fastq.gz, R-07...","[R-070722-16S-s-21H_S184_L001_R1_001.fastq.gz,...","[R-070722-16S-s-21H_S184_L001_R2_001.fastq.gz,...",16S-R-07072-s-21H,R-070722-16S-s-21H,R-070722-16S-s-21H,True,False
73,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,R-000022-16S-s-P1-pos_S149_L001_R1_001.fastq.gz,R-000022-16S-s-P1-pos_S149_L001_R2_001.fastq.gz,16S-R-s-pos,R-000022-16S-s-P1-pos,R-000022-16S-s-P1-pos,True,False

In [ ]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]
metadata_2022_washed_shotgun_amplicon_full["location"]=metadata_2022_washed_shotgun_amplicon_full["bio_sample_ID"].str.replace("_", "-").str.split("-").str[0]
metadata_2022_washed_shotgun_amplicon_full_SP=metadata_2022_washed_shotgun_amplicon_full.merge(pd.concat([SP_0000, SP_2022]), left_on=["Plot", "location"], right_on=["SP_plot", "SP_location"], how="left")#.to_csv("test.csv")

metadata_2022_washed_shotgun_amplicon_full_SP["triplicate"] = (metadata_2022_washed_shotgun_amplicon_full_SP["bio_sample_ID"].str.split("-").str[4].fillna(0)).astype(str)
metadata_2022_washed_shotgun_amplicon_full_SP["BS"] = (
    "BS_" +
    pd.to_datetime(metadata_2022_washed_shotgun_amplicon_full_SP["sample_date"])
    .dt.strftime("%y%m%d") + "_" + metadata_2022_washed_shotgun_amplicon_full_SP["LEAF_PROTOCOL"].str[0] + "_1" )

metadata_2022_washed_shotgun_amplicon_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2022_washed_shotgun_amplicon_full_SP["DNA_ext_date"], errors="coerce")
      .dt.strftime("%y%m%d")
      .fillna("000000"))

metadata_2022_washed_shotgun_amplicon_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2022_washed_shotgun_amplicon_full_SP["PCR2_date"])
    .dt.strftime("%y%m%d") + "_"+ metadata_2022_washed_shotgun_amplicon_full_SP["amplicon"] )

# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("alex-control")
is_water = metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("Ultrapure-water")
is_mystery= metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("T-150621-c-mystery")
is_des= metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("DES")
is_pbs= metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("1xPBS")
is_contaminated= metadata_2022_washed_shotgun_amplicon_full_SP[id_col].eq("contaminated-well")

control_mask = is_zymo | is_alex | is_water | is_des | is_pbs

# LY and SP fixed for all three
metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "EX"] = "EX_000000"

metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "LY_SP"] = (metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "LY"] + "__" + metadata_2022_washed_shotgun_amplicon_full_SP.loc[control_mask, "SP"])

metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "LY"] = "LY_Z_0000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "SP"] = "SP_000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "EX"] = "EX_000000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "LY_SP"] = (metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "SP"])

metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_contaminated, "LY"] = "LY_Z_0000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_contaminated, "SP"] = "SP_000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_contaminated, "EX"] = "EX_000000"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_contaminated, "LY_SP"] = (metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "SP"])

# BS depends on which control
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_mystery, "BS"] = "BS_MYSTRY_X_0"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_des, "BS"] = "BS_DESCTL_X_0"
metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_pbs, "BS"] = "BS_PBSCTL_X_0"

metadata_2022_washed_shotgun_amplicon_full_SP.loc[is_contaminated, "BS"] = "BS_CONTAM_X_0"

metadata_2022_washed_shotgun_amplicon_full_SP["LY_SP_BS"]=metadata_2022_washed_shotgun_amplicon_full_SP["LY"] + "__" + metadata_2022_washed_shotgun_amplicon_full_SP["SP"]+ "__"  +metadata_2022_washed_shotgun_amplicon_full_SP["BS"] 
metadata_2022_washed_shotgun_amplicon_full_SP["LY_SP_BS_EX"]=metadata_2022_washed_shotgun_amplicon_full_SP["LY_SP_BS"] + "__"  +metadata_2022_washed_shotgun_amplicon_full_SP["EX"] 
metadata_2022_washed_shotgun_amplicon_full_SP["LY_SP_BS_EX_LP"]=metadata_2022_washed_shotgun_amplicon_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2022_washed_shotgun_amplicon_full_SP["LP"] 

metadata_2022_washed_shotgun_amplicon_full_SP.to_csv("test.csv", sep="\t")

print(len(metadata_2022_washed_shotgun_amplicon_full))
print(len(metadata_2022_washed_shotgun_amplicon_full_SP))
metadata_2022_washed_shotgun_amplicon_full_SP

# metadata_2022_washed_shotgun_amplicon_full_SP[~metadata_2022_washed_shotgun_amplicon_full_SP["SP"].isna()].groupby("SP").count()

144
144

,bio_sample_ID,sample_date,sample_type,block,Plot,subplot,ID_on_field,spray,fertilizer,Cultivar,...,SP_lane,SP_parcel,SP_location,triplicate,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,R-040722-s-2G,2022-07-04,timeline,NaN,2.0,NaN,A7,yes,NaN,heerup,...,1.0,20.0,R,0,BS_220704_W_1,EX_221027,LP_230531_ITS,LY_R_2022__SP_002__BS_220704_W_1,LY_R_2022__SP_002__BS_220704_W_1__EX_221027,LY_R_2022__SP_002__BS_220704_W_1__EX_221027__L...
1,R-040722-s-3G,2022-07-04,timeline,NaN,3.0,NaN,B5,no,NaN,kvium,...,3.0,7.0,R,0,BS_220704_W_1,EX_221026,LP_230531_ITS,LY_R_2022__SP_003__BS_220704_W_1,LY_R_2022__SP_003__BS_220704_W_1__EX_221026,LY_R_2022__SP_003__BS_220704_W_1__EX_221026__L...
2,R-040722-s-4G,2022-07-04,timeline,NaN,4.0,NaN,B7,no,NaN,heerup,...,3.0,8.0,R,0,BS_220704_W_1,EX_221027,LP_230531_ITS,LY_R_2022__SP_004__BS_220704_W_1,LY_R_2022__SP_004__BS_220704_W_1__EX_221027,LY_R_2022__SP_004__BS_220704_W_1__EX_221027__L...
3,R-040722-s-5G,2022-07-04,timeline,NaN,5.0,NaN,B16,no,NaN,rembrandt,...,3.0,20.0,R,0,BS_220704_W_1,EX_221027,LP_230531_ITS,LY_R_2022__SP_005__BS_220704_W_1,LY_R_2022__SP_005__BS_220704_W_1__EX_221027,LY_R_2022__SP_005__BS_220704_W_1__EX_221027__L...
4,R-040722-s-6G,2022-07-04,timeline,NaN,6.0,NaN,A5,yes,NaN,kvium,...,4.0,23.0,R,0,BS_220704_W_1,EX_221031,LP_230531_ITS,LY_R_2022__SP_006__BS_220704_W_1,LY_R_2022__SP_006__BS_220704_W_1__EX_221031,LY_R_2022__SP_006__BS_220704_W_1__EX_221031__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,R-070722-s-22H,2022-07-07,timeline,NaN,22.0,NaN,B5,no,NaN,kvium,...,15.0,11.0,R,0,BS_220707_W_1,EX_221129,LP_230501_16S,LY_R_2022__SP_022__BS_220707_W_1,LY_R_2022__SP_022__BS_220707_W_1__EX_221129,LY_R_2022__SP_022__BS_220707_W_1__EX_221129__L...
140,R-070722-s-23H,2022-07-07,timeline,NaN,23.0,NaN,B16,no,NaN,rembrandt,...,15.0,19.0,R,0,BS_220707_W_1,EX_221129,LP_230501_16S,LY_R_2022__SP_023__BS_220707_W_1,LY_R_2022__SP_023__BS_220707_W_1__EX_221129,LY_R_2022__SP_023__BS_220707_W_1__EX_221129__L...
141,R-070722-s-24H,2022-07-07,timeline,NaN,24.0,NaN,A5,yes,NaN,kvium,...,16.0,9.0,R,0,BS_220707_W_1,EX_221129,LP_230501_16S,LY_R_2022__SP_024__BS_220707_W_1,LY_R_2022__SP_024__BS_220707_W_1__EX_221129,LY_R_2022__SP_024__BS_220707_W_1__EX_221129__L...
142,R-070722-s-21H,2022-07-07,timeline,NaN,21.0,NaN,B7,no,NaN,heerup,...,14.0,15.0,R,0,BS_220707_W_1,EX_221128,LP_230501_16S,LY_R_2022__SP_021__BS_220707_W_1,LY_R_2022__SP_021__BS_220707_W_1__EX_221128,LY_R_2022__SP_021__BS_220707_W_1__EX_221128__L...
143,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_230501_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...

## CRUSHED 2023 16S

In [115]:
# metadata_2023_crushed_amplicon_16S[metadata_2023_crushed_amplicon_16S["run_ID"]=="RISO2"]
# metadata_2023_crushed_amplicon_16S["run_ID"]=metadata_2023_crushed_amplicon_16S["run_ID"].str.replace("RIS2", "RISO2")
print("Number of samples: "  + str(len(metadata_2023_crushed_amplicon_16S)))
print("Number of sequence runs: "  + str(metadata_2023_crushed_amplicon_16S["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2023_crushed_amplicon_16S["run_ID"].value_counts()

Number of samples: 626
Number of sequence runs: 583

Number of sequence runs per folder:

run_ID
seq240820_C6WGP    189
seq240710_DR8PG    161
seq240826_X6DU5    140
seq240719_NR8NI     93
Name: count, dtype: int64

In [116]:
metadata_2023_crushed_amplicon_16S_full=metadata_2023_crushed_amplicon_16S.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2023_crushed_amplicon_16S_full=metadata_2023_crushed_amplicon_16S_full[metadata_2023_crushed_amplicon_16S_full["seq_sample_ID"].notna()]
metadata_2023_crushed_amplicon_16S_full['suggested_correct_seq_sample_ID'] = \
    metadata_2023_crushed_amplicon_16S_full['correct_seq_sample_ID'].fillna(metadata_2023_crushed_amplicon_16S_full['seq_sample_ID'])
metadata_2023_crushed_amplicon_16S_full['suggested_correct_seq_sample_ID'] = metadata_2023_crushed_amplicon_16S_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "").str.replace("16s", "16S")
metadata_2023_crushed_amplicon_16S_full=metadata_2023_crushed_amplicon_16S_full.sort_values("run_ID")
metadata_2023_crushed_amplicon_16S_full = metadata_2023_crushed_amplicon_16S_full.dropna(axis=1, how='all')

In [117]:
# Iterate over each row and print files
metadata_2023_crushed_amplicon_16S_full["forward_fq"]=""
metadata_2023_crushed_amplicon_16S_full["reverse_fq"]=""
metadata_2023_crushed_amplicon_16S_full["current_seq_sample_ID"]=""
metadata_2023_crushed_amplicon_16S_full["corrected_forward_fq"]=""
metadata_2023_crushed_amplicon_16S_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2023_crushed_amplicon_16S_full)  # Get the total number of rows

for index, row in metadata_2023_crushed_amplicon_16S_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        # Check if the number of matching files is not equal to 2
        if len(matching_files) == 2:
            metadata_2023_crushed_amplicon_16S_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2023_crushed_amplicon_16S_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2023_crushed_amplicon_16S_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2023_crushed_amplicon_16S_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2023_crushed_amplicon_16S_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2


    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1

# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

Processing... 100.00% complete
Processing complete!

In [118]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2023_crushed_amplicon_16S_full = metadata_2023_crushed_amplicon_16S_full[
    [col for col in metadata_2023_crushed_amplicon_16S_full.columns if col not in columns_to_move] + columns_to_move
]
# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_2023_crushed_amplicon_16S_full['forward_fq'] = metadata_2023_crushed_amplicon_16S_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_2023_crushed_amplicon_16S_full['reverse_fq'] = metadata_2023_crushed_amplicon_16S_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2023_crushed_amplicon_16S_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2023_crushed_amplicon_16S_full["suggested_correct_seq_sample_ID"] == metadata_2023_crushed_amplicon_16S_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2023_crushed_amplicon_16S_full["ALREADY_CORRECT"] = metadata_2023_crushed_amplicon_16S_full["suggested_correct_seq_sample_ID"] == metadata_2023_crushed_amplicon_16S_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2023_crushed_amplicon_16S_full = metadata_2023_crushed_amplicon_16S_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2023_crushed_amplicon_16S_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,spray_fungicide,fertiliser,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
215,T-130623-c-91C-1,321.0,91.0,2023-06-13,timeline,3.0,91.0,8.0,n,Zero,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,,,,,,NaN,T-130623-16S-c-91C-1,False,False
308,T-110723-c-41F-1,1037.0,41.0,2023-07-11,timeline,2.0,41.0,4.0,n,Half,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-110723-16S-c-41F-1_S11_L001_R1_001.fastq.gz,T-110723-16S-c-41F-1_S11_L001_R2_001.fastq.gz,T-110723-16S-c-41F-1_S11_L001_R1_001.fastq.gz,T-110723-16S-c-41F-1_S11_L001_R2_001.fastq.gz,T-110723-16S-c-41F-1,NaN,T-110723-16S-c-41F-1,False,True
262,T-040723-c-22E-1,845.0,22.0,2023-07-04,timeline,1.0,22.0,2.0,n,Half,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-040723-16S-c-22E-1_S153_L001_R1_001.fastq.gz,T-040723-16S-c-22E-1_S153_L001_R2_001.fastq.gz,T-040723-16S-c-22E-1_S153_L001_R1_001.fastq.gz,T-040723-16S-c-22E-1_S153_L001_R2_001.fastq.gz,T-040723-16S-c-22E-1,NaN,T-040723-16S-c-22E-1,False,True
261,T-040723-c-18E-1,849.0,18.0,2023-07-04,timeline,1.0,18.0,2.0,n,Half,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-040723-16S-c-18E-1_S152_L001_R1_001.fastq.gz,T-040723-16S-c-18E-1_S152_L001_R2_001.fastq.gz,T-040723-16S-c-18E-1_S152_L001_R1_001.fastq.gz,T-040723-16S-c-18E-1_S152_L001_R2_001.fastq.gz,T-040723-16S-c-18E-1,NaN,T-040723-16S-c-18E-1,False,True
260,T-040723-c-17E-1,853.0,17.0,2023-07-04,timeline,1.0,17.0,2.0,n,Half,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-040723-16S-c-17E-1_S151_L001_R1_001.fastq.gz,T-040723-16S-c-17E-1_S151_L001_R2_001.fastq.gz,T-040723-16S-c-17E-1_S151_L001_R1_001.fastq.gz,T-040723-16S-c-17E-1_S151_L001_R2_001.fastq.gz,T-040723-16S-c-17E-1,NaN,T-040723-16S-c-17E-1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-16S-c-P6-pos_S150_L001_R1_001.fastq.gz,T-2023-16S-c-P6-pos_S150_L001_R2_001.fastq.gz,T-000023-16S-c-P6-pos_S150_L001_R1_001.fastq.gz,T-000023-16S-c-P6-pos_S150_L001_R2_001.fastq.gz,T-2023-16S-c-P6-pos,T-000023-16S-c-P6-pos,T-000023-16S-c-P6-pos,True,False
93,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-16S-c-P1-pos_S2_L001_R1_001.fastq.gz,T-2023-16S-c-P1-pos_S2_L001_R2_001.fastq.gz,T-000023-16S-c-P1-pos_S2_L001_R1_001.fastq.gz,T-000023-16S-c-P1-pos_S2_L001_R2_001.fastq.gz,T-2023-16S-c-P1-pos,T-000023-16S-c-P1-pos,T-000023-16S-c-P1-pos,True,False
624,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-16S-c-P7-neg_S141_L001_R1_001.fastq.gz,T-2023-16S-c-P7-neg_S141_L001_R2_001.fastq.gz,T-000023-16S-c-P7-neg_S141_L001_R1_001.fastq.gz,T-000023-16S-c-P7-neg_S141_L001_R2_001.fastq.gz,T-2023-16S-c-P7-neg,T-000023-16S-c-P7-neg,T-000023-16S-c-P7-neg,True,False
92,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-16S-c-P1-neg_S1_L001_R1_001.fastq.gz,T-2023-16S-c-P1-neg_S1_L001_R2_001.fastq.gz,T-000023-16S-c-P1-neg_S1_L001_R1_001.fastq.gz,T-000023-16S-c-P1-neg_S1_L001_R2_001.fastq.gz,T-2023-16S-c-P1-neg,T-000023-16S-c-P1-neg,T-000023-16S-c-P1-neg,True,False
625,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-16S-c-P7-pos_S142_L001_R1_001.fastq.gz,T-2023-16S-c-P7-pos_S142_L001_R2_001.fastq.gz,T-000023-16S-c-P7-pos_S142_L001_R1_001.fastq.gz,T-000023-16S-c-P7-pos_S142_L001_R2_001.fastq.gz,T-2023-16S-c-P7-pos,T-000023-16S-c-P7-pos,T-000023-16S-c-P7-pos,True,False

In [119]:
filtered_metadata_2023_crushed_amplicon_16S_full=metadata_2023_crushed_amplicon_16S_full[
    metadata_2023_crushed_amplicon_16S_full.apply(
        lambda row: row['amplicon'] not in row['suggested_correct_seq_sample_ID'], axis=1)]
filtered_metadata_2023_crushed_amplicon_16S_full

Empty DataFrame
Columns: [bio_sample_ID, vila_ID, sample_number, sample_date, sample_type, block, plot, subplot, spray_fungicide, fertiliser, cultivar, density, harvest_date, sample_weight_plus_minus_2mg, DNA_plate_number, DNA_ext_date, DNA_conc_plate, lib_prep, amplicon, lib_plate_number, plate_position, PCR1_date, PCR2_date, lib_DNA_conc, index_set, S5_index_ID, S5_index, N7_index_ID, N7_index, index_pair, seq_sample_ID, run_ID, note, YEAR, LEAF_PROTOCOL, LIBRARY_PREPARATION, Unnamed: 0, dir_name, full_path, forward_fq, reverse_fq, corrected_forward_fq, corrected_reverse_fq, current_seq_sample_ID, correct_seq_sample_ID, suggested_correct_seq_sample_ID, SUGGESTED_EQUALS_CORRECT, ALREADY_CORRECT]
Index: []

[0 rows x 48 columns]

In [120]:
metadata_2023_crushed_amplicon_16S_full.groupby(["block", "plot",]).first().reset_index().to_csv("SP_2023_test.csv", sep="\t")

In [122]:
columns_SP=["sample_number", "sample_weight_plus_minus_2mg", "sample_date"]
columns_EX=["DNA_plate_number", "DNA_ext_date", "DNA_conc_plate"]
columns_LP=["lib_prep", "amplicon","lib_plate_number", "plate_position", "PCR1_date", "PCR2_date", "lib_DNA_conc", "index_set", "S5_index_ID", "S5_index", "N7_index_ID", "N7_index", "index_pair"]
metadata_2023_crushed_amplicon_16S_full["location"]=metadata_2023_crushed_amplicon_16S_full["bio_sample_ID"].str.split("-").str[0]
metadata_2023_crushed_amplicon_16S_full_SP=metadata_2023_crushed_amplicon_16S_full.merge(pd.concat([SP_0000, SP_2023]), left_on=["location", "sample_number"], right_on=["SP_location", "SP_sample_number"], how="left")#.to_csv("test.csv")

metadata_2023_crushed_amplicon_16S_full_SP["triplicate"] = (metadata_2023_crushed_amplicon_16S_full_SP["bio_sample_ID"].str.split("-").str[4].fillna(0)).astype(str)
metadata_2023_crushed_amplicon_16S_full_SP["BS"] = (
    "BS_" +
    pd.to_datetime(metadata_2023_crushed_amplicon_16S_full_SP["sample_date"])
    .dt.strftime("%y%m%d") + "_" + metadata_2023_crushed_amplicon_16S_full_SP["LEAF_PROTOCOL"].str[0] + "_" + metadata_2023_crushed_amplicon_16S_full_SP["triplicate"] )

metadata_2023_crushed_amplicon_16S_full_SP["EX"] = (
    "EX_" +
    pd.to_datetime(metadata_2023_crushed_amplicon_16S_full_SP["DNA_ext_date"], errors="coerce")
      .dt.strftime("%y%m%d")
      .fillna("000000"))

metadata_2023_crushed_amplicon_16S_full_SP["LP"] = (
    "LP_" +
    pd.to_datetime(metadata_2023_crushed_amplicon_16S_full_SP["PCR2_date"])
    .dt.strftime("%y%m%d") + "_"+ metadata_2023_crushed_amplicon_16S_full_SP["amplicon"] )


# --- set defaults for controls based on bio_sample_ID ---
id_col = "bio_sample_ID"

is_zymo = metadata_2023_crushed_amplicon_16S_full_SP[id_col].eq("ZymoBIOMICS-Microbial-Community-DNA-Standard-D6306")
is_alex = metadata_2023_crushed_amplicon_16S_full_SP[id_col].eq("alex-control")
is_water = metadata_2023_crushed_amplicon_16S_full_SP[id_col].eq("Ultrapure-water")
is_mystery= metadata_2023_crushed_amplicon_16S_full_SP[id_col].eq("T-150621-c-mystery")
is_contaminated= metadata_2023_crushed_amplicon_16S_full_SP[id_col].eq("contaminated-well")


control_mask = is_zymo | is_alex | is_water 

# LY and SP fixed for all three
metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "LY"] = "LY_X_0000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "SP"] = "SP_000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "EX"] = "EX_000000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "EX"] = "EX_000000"

metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "LY_SP"] = (metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "LY"] + "__" + metadata_2023_crushed_amplicon_16S_full_SP.loc[control_mask, "SP"])


metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "LY"] = "LY_Z_0000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "SP"] = "SP_000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "EX"] = "EX_000000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "LY_SP"] = (metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "SP"])


metadata_2023_crushed_amplicon_16S_full_SP.loc[is_contaminated, "LY"] = "LY_Z_0000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_contaminated, "SP"] = "SP_000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_contaminated, "EX"] = "EX_000000"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_contaminated, "LY_SP"] = (metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "LY"] + "__" + metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "SP"])


# BS depends on which control
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_zymo, "BS"] = "BS_ZYMCTL_X_0"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_alex, "BS"] = "BS_ALXCTL_X_0"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_water, "BS"] = "BS_ULWCTL_X_0"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_mystery, "BS"] = "BS_MYSTRY_X_0"
metadata_2023_crushed_amplicon_16S_full_SP.loc[is_contaminated, "BS"] = "BS_CONTAM_X_0"



metadata_2023_crushed_amplicon_16S_full_SP["LY_SP_BS"]=metadata_2023_crushed_amplicon_16S_full_SP["LY"] + "__" + metadata_2023_crushed_amplicon_16S_full_SP["SP"]+ "__"  +metadata_2023_crushed_amplicon_16S_full_SP["BS"] 
metadata_2023_crushed_amplicon_16S_full_SP["LY_SP_BS_EX"]=metadata_2023_crushed_amplicon_16S_full_SP["LY_SP_BS"] + "__"  +metadata_2023_crushed_amplicon_16S_full_SP["EX"] 
metadata_2023_crushed_amplicon_16S_full_SP["LY_SP_BS_EX_LP"]=metadata_2023_crushed_amplicon_16S_full_SP["LY_SP_BS_EX"] + "__"  +metadata_2023_crushed_amplicon_16S_full_SP["LP"] 


metadata_2023_crushed_amplicon_16S_full_SP.to_csv("test.csv", sep="\t")


print(len(metadata_2023_crushed_amplicon_16S_full))
print(len(metadata_2023_crushed_amplicon_16S_full_SP))
metadata_2023_crushed_amplicon_16S_full_SP


# TODO what is subplot? it makes no sense
# metadata_2023_crushed_amplicon_16S_full_SP[~metadata_2023_crushed_amplicon_16S_full_SP["SP"].isna()].groupby("SP").count()

583
583

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,spray_fungicide,fertiliser,...,SP_fertiliser,SP_cultivar,SP_density,triplicate,BS,EX,LP,LY_SP_BS,LY_SP_BS_EX,LY_SP_BS_EX_LP
0,T-130623-c-91C-1,321.0,91.0,2023-06-13,timeline,3.0,91.0,8.0,n,Zero,...,ZERO,Heerup,300.0,1,BS_230613_C_1,EX_240516,LP_240628_16S,LY_T_2023__SP_091__BS_230613_C_1,LY_T_2023__SP_091__BS_230613_C_1__EX_240516,LY_T_2023__SP_091__BS_230613_C_1__EX_240516__L...
1,T-110723-c-41F-1,1037.0,41.0,2023-07-11,timeline,2.0,41.0,4.0,n,Half,...,HALF,Rembrandt,300.0,1,BS_230711_C_1,EX_240521,LP_240701_16S,LY_T_2023__SP_041__BS_230711_C_1,LY_T_2023__SP_041__BS_230711_C_1__EX_240521,LY_T_2023__SP_041__BS_230711_C_1__EX_240521__L...
2,T-040723-c-22E-1,845.0,22.0,2023-07-04,timeline,1.0,22.0,2.0,n,Half,...,HALF,Kvium,300.0,1,BS_230704_C_1,EX_240516,LP_240628_16S,LY_T_2023__SP_022__BS_230704_C_1,LY_T_2023__SP_022__BS_230704_C_1__EX_240516,LY_T_2023__SP_022__BS_230704_C_1__EX_240516__L...
3,T-040723-c-18E-1,849.0,18.0,2023-07-04,timeline,1.0,18.0,2.0,n,Half,...,HALF,Heerup,300.0,1,BS_230704_C_1,EX_240516,LP_240628_16S,LY_T_2023__SP_018__BS_230704_C_1,LY_T_2023__SP_018__BS_230704_C_1__EX_240516,LY_T_2023__SP_018__BS_230704_C_1__EX_240516__L...
4,T-040723-c-17E-1,853.0,17.0,2023-07-04,timeline,1.0,17.0,2.0,n,Half,...,HALF,Rembrandt,300.0,1,BS_230704_C_1,EX_240516,LP_240628_16S,LY_T_2023__SP_017__BS_230704_C_1,LY_T_2023__SP_017__BS_230704_C_1__EX_240516,LY_T_2023__SP_017__BS_230704_C_1__EX_240516__L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_240716_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
579,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_240704_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...
580,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_240715_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
581,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,BS_ULWCTL_X_0,EX_000000,LP_240704_16S,LY_X_0000__SP_000__BS_ULWCTL_X_0,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ULWCTL_X_0__EX_000000__L...
582,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Standard,BS_ZYMCTL_X_0,EX_000000,LP_240715_16S,LY_X_0000__SP_000__BS_ZYMCTL_X_0,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000,LY_X_0000__SP_000__BS_ZYMCTL_X_0__EX_000000__L...

## SEQ CONTROLS

In [ ]:
print("Number of samples: "  + str(len(metadata_control_crushed_amplicon)))
print("Number of sequence runs: "  + str(metadata_control_crushed_amplicon["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_control_crushed_amplicon["run_ID"].value_counts().to_frame()

Number of samples: 360
Number of sequence runs: 360

Number of sequence runs per folder:

                 count
run_ID
seq230707_DWDQH     24
seq230526_JRV78     24
seq230714_FWU63     24
seq230710_GW4I8     24
seq240412_BRLUV     24
seq240209_KSVAZ     24
seq240508_LNERQ     24
seq231107_RISO1     24
seq240222_RQS8X     24
seq231206_RISO2     24
seq240424_T6U6R     24
seq240710_DR8PG     24
seq240719_NR8NI     24
seq240820_C6WGP     24
seq240826_X6DU5     24

In [ ]:
metadata_control_crushed_amplicon_full=metadata_control_crushed_amplicon.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_control_crushed_amplicon_full=metadata_control_crushed_amplicon_full[metadata_control_crushed_amplicon_full["seq_sample_ID"].notna()]

metadata_control_crushed_amplicon_full["number_bio"]=metadata_control_crushed_amplicon_full["bio_sample_ID"].str.split("-c-").str[1]
metadata_control_crushed_amplicon_full

metadata_control_crushed_amplicon_full["number_sample"]=metadata_control_crushed_amplicon_full["correct_seq_sample_ID"].str.split("-c-").str[1].str.rsplit( "-",n=1).str[0]
metadata_control_crushed_amplicon_full

metadata_control_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_control_crushed_amplicon_full['correct_seq_sample_ID'].fillna(metadata_control_crushed_amplicon_full['seq_sample_ID'])
metadata_control_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_control_crushed_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "")
metadata_control_crushed_amplicon_full=metadata_control_crushed_amplicon_full.sort_values("run_ID")

metadata_control_crushed_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_control_crushed_amplicon_full.apply(
    lambda row: row['suggested_correct_seq_sample_ID'].replace(str(row["number_sample"]), str(row["number_bio"]))
    if pd.notna(row['suggested_correct_seq_sample_ID']) else row['suggested_correct_seq_sample_ID'],
    axis=1)

metadata_control_crushed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,correct_seq_sample_ID,YEAR,LEAF_PROTOCOL,LIBRARY_PREPARATION,Unnamed: 0,dir_name,full_path,number_bio,number_sample,suggested_correct_seq_sample_ID
35,A-230622-c-66,NaN,66,2022-06-23,deep,3,18,NaN,B7,y,...,A-230622-ITS-c-66-JRV78,control,CRUSHED,amplicon,15,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,66,66,A-230622-ITS-c-66-JRV78
26,A-230622-c-61-3,NaN,61,2022-06-23,deep,3,13,NaN,A7,n,...,A-230622-ITS-c-61-3-JRV78,control,CRUSHED,amplicon,15,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,61-3,61-3,A-230622-ITS-c-61-3-JRV78
27,A-230622-c-62-1,NaN,62,2022-06-23,deep,3,14,NaN,A16,n,...,A-230622-ITS-c-62-1-JRV78,control,CRUSHED,amplicon,15,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,62-1,62-1,A-230622-ITS-c-62-1-JRV78
28,A-230622-c-62-2,NaN,62,2022-06-23,deep,3,14,NaN,A16,n,...,A-230622-ITS-c-62-2-JRV78,control,CRUSHED,amplicon,15,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,62-2,62-2,A-230622-ITS-c-62-2-JRV78
29,A-230622-c-62-3,NaN,62,2022-06-23,deep,3,14,NaN,A16,n,...,A-230622-ITS-c-62-3-JRV78,control,CRUSHED,amplicon,15,seq230526_JRV78,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,62-3,62-3,A-230622-ITS-c-62-3-JRV78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,A-230622-c-51-5,NaN,51,2022-06-23,deep,1,3,NaN,A5,n,...,A-230622-16S-c-51-5-X6DU5,control,CRUSHED,amplicon,13,seq240826_X6DU5,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,51-5,51-5,A-230622-16S-c-51-5-X6DU5
337,A-230622-c-51-4,NaN,51,2022-06-23,deep,1,3,NaN,A5,n,...,A-230622-16S-c-51-4-X6DU5,control,CRUSHED,amplicon,13,seq240826_X6DU5,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,51-4,51-4,A-230622-16S-c-51-4-X6DU5
336,A-230622-c-51-3,NaN,51,2022-06-23,deep,1,3,NaN,A5,n,...,A-230622-16S-c-51-3-X6DU5,control,CRUSHED,amplicon,13,seq240826_X6DU5,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,51-3,51-3,A-230622-16S-c-51-3-X6DU5
346,A-230622-c-57,NaN,57,2022-06-23,deep,2,9,NaN,B5,y,...,A-230622-16S-c-57-X6DU5,control,CRUSHED,amplicon,13,seq240826_X6DU5,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,57,57,A-230622-16S-c-57-X6DU5
359,A-230622-c-59-6,NaN,59,2022-06-23,deep,2,11,NaN,A5,n,...,A-230622-16S-c-59-6-X6DU5,control,CRUSHED,amplicon,13,seq240826_X6DU5,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,59-6,59-6,A-230622-16S-c-59-6-X6DU5

In [ ]:
def list_files_with_prefix(folder_path, prefix):
    """
    Returns sorted file paths from the already-loaded
    `trinucleotide_counts` DataFrame where:
      - 'Path' contains folder_path
      - 'Path' contains prefix
    """
    try:
        if "Path" not in trinucleotide_counts.columns:
            return []
        
        matching = trinucleotide_counts["Path"].str.contains(folder_path, na=False) & \
                   trinucleotide_counts["Path"].str.contains(prefix, na=False)
        
        matching_files = (
            trinucleotide_counts.loc[matching, "Path"]
            .sort_values()
            .tolist()
        )
        
        return matching_files
    
    except Exception:
        return []

# Iterate over each row and print files
metadata_control_crushed_amplicon_full["forward_fq"]=""
metadata_control_crushed_amplicon_full["reverse_fq"]=""
metadata_control_crushed_amplicon_full["current_seq_sample_ID"]=""
metadata_control_crushed_amplicon_full["corrected_forward_fq"]=""
metadata_control_crushed_amplicon_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_control_crushed_amplicon_full)  # Get the total number of rows

for index, row in metadata_control_crushed_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  
        prefix = row['seq_sample_ID'] + "_"  
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        if len(matching_files) >2:
            read_counts=trinucleotide_counts[trinucleotide_counts["Path"].isin(matching_files)].sort_values(by="Path")
            read_counts=read_counts[read_counts["Reads"]>0]
            if len(read_counts)==2:
                print(matching_files[0].split("/")[-2:], matching_files[2].split("/")[-1:])
                print()
                matching_files=read_counts["Path"].to_list()
        
        if len(matching_files) == 2:
            metadata_control_crushed_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_control_crushed_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_control_crushed_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_control_crushed_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_control_crushed_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1
    
print("\nProcessing complete!")

['seq240424_T6U6R', 'A-230622-16S-c-58-2_S17_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-2_S187_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-51-5_S177_L001_R1_001.fastq.gz'] ['A-230622-16S-c-51-5_S7_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-59-6_S198_L001_R1_001.fastq.gz'] ['A-230622-16S-c-59-6_S28_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-59-5_S197_L001_R1_001.fastq.gz'] ['A-230622-16S-c-59-5_S27_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-59-4_S196_L001_R1_001.fastq.gz'] ['A-230622-16S-c-59-4_S26_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-59-3_S195_L001_R1_001.fastq.gz'] ['A-230622-16S-c-59-3_S25_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-59-2_S194_L001_R1_001.fastq.gz'] ['A-230622-16S-c-59-2_S24_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-59-1_S193_L001_R1_001.fastq.gz'] ['A-230622-16S-c-59-1_S23_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-58-7_S192_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-7_S22_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-58-6_S191_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-6_S21_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-58-5_S190_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-5_S20_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-58-4_S189_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-4_S19_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-58-3_S188_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-3_S18_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-58-1_S16_L001_R1_001.fastq.gz'] ['A-230622-16S-c-58-1_S186_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-57_S15_L001_R1_001.fastq.gz'] ['A-230622-16S-c-57_S185_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-56_S14_L001_R1_001.fastq.gz'] ['A-230622-16S-c-56_S184_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-55_S13_L001_R1_001.fastq.gz'] ['A-230622-16S-c-55_S183_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-54_S12_L001_R1_001.fastq.gz'] ['A-230622-16S-c-54_S182_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-53_S11_L001_R1_001.fastq.gz'] ['A-230622-16S-c-53_S181_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-52_S10_L001_R1_001.fastq.gz'] ['A-230622-16S-c-52_S180_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-51-7_S179_L001_R1_001.fastq.gz'] ['A-230622-16S-c-51-7_S9_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-51-6_S178_L001_R1_001.fastq.gz'] ['A-230622-16S-c-51-6_S8_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-51-4_S176_L001_R1_001.fastq.gz'] ['A-230622-16S-c-51-4_S6_L001_R1_001.fastq.gz']

['seq240424_T6U6R', 'A-230622-16S-c-51-3_S175_L001_R1_001.fastq.gz'] ['A-230622-16S-c-51-3_S5_L001_R1_001.fastq.gz']

Processing... 100.00% complete
Processing complete!

In [ ]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_control_crushed_amplicon_full = metadata_control_crushed_amplicon_full[
    [col for col in metadata_control_crushed_amplicon_full.columns if col not in columns_to_move] + columns_to_move
]
# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_control_crushed_amplicon_full['forward_fq'] = metadata_control_crushed_amplicon_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_control_crushed_amplicon_full['reverse_fq'] = metadata_control_crushed_amplicon_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_control_crushed_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_control_crushed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_control_crushed_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_control_crushed_amplicon_full["ALREADY_CORRECT"] = metadata_control_crushed_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_control_crushed_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_control_crushed_amplicon_full = metadata_control_crushed_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_control_crushed_amplicon_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,ID_on_field,spray_fungicide,...,number_sample,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
178,A-230622-c-62-5,NaN,62,2022-06-23,deep,3,14,NaN,A16,n,...,63-5,washed-1-control-A-230622-ITS-c-63-5_S258_L001...,washed-1-control-A-230622-ITS-c-63-5_S258_L001...,A-230622-ITS-c-62-5-RISO1_S258_L001_R1_001.fas...,A-230622-ITS-c-62-5-RISO1_S258_L001_R2_001.fas...,washed-1-control-A-230622-ITS-c-63-5,A-230622-ITS-c-63-5-RISO1,A-230622-ITS-c-62-5-RISO1,False,False
170,A-230622-c-60-3,NaN,60,2022-06-23,deep,2,12,NaN,A7,n,...,61-3,washed-1-control-A-230622-ITS-c-61-3_S250_L001...,washed-1-control-A-230622-ITS-c-61-3_S250_L001...,A-230622-ITS-c-60-3-RISO1_S250_L001_R1_001.fas...,A-230622-ITS-c-60-3-RISO1_S250_L001_R2_001.fas...,washed-1-control-A-230622-ITS-c-61-3,A-230622-ITS-c-61-3-RISO1,A-230622-ITS-c-60-3-RISO1,False,False
171,A-230622-c-61-1,NaN,61,2022-06-23,deep,3,13,NaN,A7,n,...,62-1,washed-1-control-A-230622-ITS-c-62-1_S251_L001...,washed-1-control-A-230622-ITS-c-62-1_S251_L001...,A-230622-ITS-c-61-1-RISO1_S251_L001_R1_001.fas...,A-230622-ITS-c-61-1-RISO1_S251_L001_R2_001.fas...,washed-1-control-A-230622-ITS-c-62-1,A-230622-ITS-c-62-1-RISO1,A-230622-ITS-c-61-1-RISO1,False,False
172,A-230622-c-61-2,NaN,61,2022-06-23,deep,3,13,NaN,A7,n,...,62-2,washed-1-control-A-230622-ITS-c-62-2_S252_L001...,washed-1-control-A-230622-ITS-c-62-2_S252_L001...,A-230622-ITS-c-61-2-RISO1_S252_L001_R1_001.fas...,A-230622-ITS-c-61-2-RISO1_S252_L001_R2_001.fas...,washed-1-control-A-230622-ITS-c-62-2,A-230622-ITS-c-62-2-RISO1,A-230622-ITS-c-61-2-RISO1,False,False
173,A-230622-c-61-3,NaN,61,2022-06-23,deep,3,13,NaN,A7,n,...,62-3,washed-1-control-A-230622-ITS-c-62-3_S253_L001...,washed-1-control-A-230622-ITS-c-62-3_S253_L001...,A-230622-ITS-c-61-3-RISO1_S253_L001_R1_001.fas...,A-230622-ITS-c-61-3-RISO1_S253_L001_R2_001.fas...,washed-1-control-A-230622-ITS-c-62-3,A-230622-ITS-c-62-3-RISO1,A-230622-ITS-c-61-3-RISO1,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,A-230622-c-51-5,NaN,51,2022-06-23,deep,1,3,NaN,A5,n,...,51-5,A-230622-16S-c-51-5_S145_L001_R1_001.fastq.gz,A-230622-16S-c-51-5_S145_L001_R2_001.fastq.gz,A-230622-16S-c-51-5-X6DU5_S145_L001_R1_001.fas...,A-230622-16S-c-51-5-X6DU5_S145_L001_R2_001.fas...,A-230622-16S-c-51-5,A-230622-16S-c-51-5-X6DU5,A-230622-16S-c-51-5-X6DU5,True,False
337,A-230622-c-51-4,NaN,51,2022-06-23,deep,1,3,NaN,A5,n,...,51-4,A-230622-16S-c-51-4_S144_L001_R1_001.fastq.gz,A-230622-16S-c-51-4_S144_L001_R2_001.fastq.gz,A-230622-16S-c-51-4-X6DU5_S144_L001_R1_001.fas...,A-230622-16S-c-51-4-X6DU5_S144_L001_R2_001.fas...,A-230622-16S-c-51-4,A-230622-16S-c-51-4-X6DU5,A-230622-16S-c-51-4-X6DU5,True,False
336,A-230622-c-51-3,NaN,51,2022-06-23,deep,1,3,NaN,A5,n,...,51-3,A-230622-16S-c-51-3_S143_L001_R1_001.fastq.gz,A-230622-16S-c-51-3_S143_L001_R2_001.fastq.gz,A-230622-16S-c-51-3-X6DU5_S143_L001_R1_001.fas...,A-230622-16S-c-51-3-X6DU5_S143_L001_R2_001.fas...,A-230622-16S-c-51-3,A-230622-16S-c-51-3-X6DU5,A-230622-16S-c-51-3-X6DU5,True,False
346,A-230622-c-57,NaN,57,2022-06-23,deep,2,9,NaN,B5,y,...,57,A-230622-16S-c-57_S153_L001_R1_001.fastq.gz,A-230622-16S-c-57_S153_L001_R2_001.fastq.gz,A-230622-16S-c-57-X6DU5_S153_L001_R1_001.fastq.gz,A-230622-16S-c-57-X6DU5_S153_L001_R2_001.fastq.gz,A-230622-16S-c-57,A-230622-16S-c-57-X6DU5,A-230622-16S-c-57-X6DU5,True,False
359,A-230622-c-59-6,NaN,59,2022-06-23,deep,2,11,NaN,A5,n,...,59-6,A-230622-16S-c-59-6_S166_L001_R1_001.fastq.gz,A-230622-16S-c-59-6_S166_L001_R2_001.fastq.gz,A-230622-16S-c-59-6-X6DU5_S166_L001_R1_001.fas...,A-230622-16S-c-59-6-X6DU5_S166_L001_R2_001.fas...,A-230622-16S-c-59-6,A-230622-16S-c-59-6-X6DU5,A-230622-16S-c-59-6-X6DU5,True,False

In [ ]:
filtered_metadata_control_crushed_amplicon_full=metadata_control_crushed_amplicon_full[
    metadata_control_crushed_amplicon_full.apply(
        lambda row: row['amplicon'] not in row['suggested_correct_seq_sample_ID'], axis=1
    )
]
filtered_metadata_control_crushed_amplicon_full

Empty DataFrame
Columns: [bio_sample_ID, vila_ID, sample_number, sample_date, sample_type, block, plot, subplot, ID_on_field, spray_fungicide, fertiliser, cultivar, density, harvest_date, yield_grain, yield_straw, yield_TGW, sample_weight_plus_minus_2mg, lyophilised_date, crushed_date, DNA_plate_number, DNA_ext_date, DNA_conc_plate_dilutedx10, lib_prep, amplicon, lib_plate_number, plate_position, PCR1_date, PCR2_date, lib_DNA_conc, index_set, S5_index_ID, S5_index, N7_index_ID, N7_index, index_pair, seq_sample_ID, run_ID, note, YEAR, LEAF_PROTOCOL, LIBRARY_PREPARATION, Unnamed: 0, dir_name, full_path, number_bio, number_sample, forward_fq, reverse_fq, corrected_forward_fq, corrected_reverse_fq, current_seq_sample_ID, correct_seq_sample_ID, suggested_correct_seq_sample_ID, SUGGESTED_EQUALS_CORRECT, ALREADY_CORRECT]
Index: []

[0 rows x 56 columns]

## Shotgun 2023 amplicon

In [ ]:
print("Number of samples: "  + str(len(metadata_2023_washed_shotgun_amplicon)))
print("Number of sequence runs: "  + str(metadata_2023_washed_shotgun_amplicon["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2023_washed_shotgun_amplicon["run_ID"].value_counts()

Number of samples: 240
Number of sequence runs: 240

Number of sequence runs per folder:

run_ID
seq240508_LNERQ    97
seq240719_NR8NI    94
seq240710_DR8PG    41
seq231107_RISO1     8
Name: count, dtype: int64

In [ ]:
metadata_2023_washed_shotgun_amplicon_full=metadata_2023_washed_shotgun_amplicon.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2023_washed_shotgun_amplicon_full=metadata_2023_washed_shotgun_amplicon_full[metadata_2023_washed_shotgun_amplicon_full["seq_sample_ID"].notna()]
metadata_2023_washed_shotgun_amplicon_full['suggested_correct_seq_sample_ID'] = \
    metadata_2023_washed_shotgun_amplicon_full['correct_seq_sample_ID'].fillna(metadata_2023_washed_shotgun_amplicon_full['seq_sample_ID'])
metadata_2023_washed_shotgun_amplicon_full['suggested_correct_seq_sample_ID'] = metadata_2023_washed_shotgun_amplicon_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "")
metadata_2023_washed_shotgun_amplicon_full=metadata_2023_washed_shotgun_amplicon_full.sort_values("run_ID")

In [ ]:


# Iterate over each row and print files
metadata_2023_washed_shotgun_amplicon_full["forward_fq"]=""
metadata_2023_washed_shotgun_amplicon_full["reverse_fq"]=""
metadata_2023_washed_shotgun_amplicon_full["current_seq_sample_ID"]=""
metadata_2023_washed_shotgun_amplicon_full["corrected_forward_fq"]=""
metadata_2023_washed_shotgun_amplicon_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2023_washed_shotgun_amplicon_full)  # Get the total number of rows

for index, row in metadata_2023_washed_shotgun_amplicon_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        if len(matching_files) == 2:
            metadata_2023_washed_shotgun_amplicon_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2023_washed_shotgun_amplicon_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2023_washed_shotgun_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2023_washed_shotgun_amplicon_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2023_washed_shotgun_amplicon_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2


        if len(matching_files) >2:

            
            
            grouped_files = defaultdict(list)
            
            # Loop over each file and group by the part before R1/R2
            for file in matching_files:
                # Split the file name at R1 or R2
                base_name = file.split("/")[-1].rsplit("_R", 1)[0]  # Split from the last occurrence of "_R"
                grouped_files[base_name].append(file.split("/")[-1])
            
            metadata_2023_washed_shotgun_amplicon_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", grouped_files[base_name][0].split("/")[-1])[0]
     
            
            # Print the grouped files
            m=0
            for base_name, files in grouped_files.items():      
                if len(files)==2:
            
                    if m==0:
                        # print(grouped_files[base_name][0])
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "forward_fq"] = [grouped_files[base_name][0]]
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "reverse_fq"] = [grouped_files[base_name][1]]
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "corrected_forward_fq"] = [correct_seq_sample_ID + ending_R1]
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "corrected_reverse_fq"] = [correct_seq_sample_ID + ending_R2]
            
            
                    else:
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "forward_fq"].append(grouped_files[base_name][0])
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "reverse_fq"].append(grouped_files[base_name][1])
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "corrected_forward_fq"].append(correct_seq_sample_ID + ending_R1)
                        metadata_2023_washed_shotgun_amplicon_full.loc[index, "corrected_reverse_fq"].append(correct_seq_sample_ID + ending_R2)
            
                
                    m=m+1
                else:
                    print("ERROR", base_name, files)


    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1
    
# After the loop, print 100% to indicate completion
print("\nProcessing complete!")

Processing... 100.00% complete
Processing complete!

In [ ]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2023_washed_shotgun_amplicon_full = metadata_2023_washed_shotgun_amplicon_full[
    [col for col in metadata_2023_washed_shotgun_amplicon_full.columns if col not in columns_to_move] + columns_to_move
]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2023_washed_shotgun_amplicon_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2023_washed_shotgun_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2023_washed_shotgun_amplicon_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2023_washed_shotgun_amplicon_full["ALREADY_CORRECT"] = metadata_2023_washed_shotgun_amplicon_full["suggested_correct_seq_sample_ID"] == metadata_2023_washed_shotgun_amplicon_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2023_washed_shotgun_amplicon_full = metadata_2023_washed_shotgun_amplicon_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2023_washed_shotgun_amplicon_full#.shotgun("metadata_shotgun_19_03_2025_2023_shotgun_amplicon.csv")

,bio_sample_ID,sample_date,sample_type,block,plot,subplot,ID_on_field,spray,fertilizer,cultivar,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
239,T-210623-aphid-107D,2023-06-21,timeline,3.0,107,9.0,NaN,NaN,Normal,sheriff,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-200723-ITS-w-aphid-107D_S279_L001_R1_001.fas...,T-200723-ITS-w-aphid-107D_S279_L001_R2_001.fas...,washed-1-T-200723-ITS-w-aphid-107D,NaN,T-200723-ITS-w-aphid-107D,False,False
237,T-210623-aphid-100D,2023-06-21,timeline,3.0,100,9.0,NaN,NaN,Normal,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-200723-ITS-w-aphid-100D_S277_L001_R1_001.fas...,T-200723-ITS-w-aphid-100D_S277_L001_R2_001.fas...,washed-1-T-200723-ITS-w-aphid-100D,NaN,T-200723-ITS-w-aphid-100D,False,False
236,T-210623-aphid-98D,2023-06-21,timeline,3.0,98,9.0,NaN,NaN,Normal,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-200723-ITS-w-aphid-98D_S276_L001_R1_001.fast...,T-200723-ITS-w-aphid-98D_S276_L001_R2_001.fast...,washed-1-T-200723-ITS-w-aphid-98D,NaN,T-200723-ITS-w-aphid-98D,False,False
235,T-210623-aphid-72D,2023-06-21,timeline,2.0,72,6.0,NaN,NaN,Normal,rembrandt,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-200723-ITS-w-aphid-72D_S275_L001_R1_001.fast...,T-200723-ITS-w-aphid-72D_S275_L001_R2_001.fast...,washed-1-T-200723-ITS-w-aphid-72D,NaN,T-200723-ITS-w-aphid-72D,False,False
234,T-210623-aphid-66D,2023-06-21,timeline,2.0,66,6.0,NaN,NaN,Normal,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-200723-ITS-w-aphid-66D_S274_L001_R1_001.fast...,T-200723-ITS-w-aphid-66D_S274_L001_R2_001.fast...,washed-1-T-200723-ITS-w-aphid-66D,NaN,T-200723-ITS-w-aphid-66D,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-000023-16S-s-P2-pos_S110_L001_R1_001.fastq.gz,T-000023-16S-s-P2-pos_S110_L001_R2_001.fastq.gz,T-2023-16S-s-P2-pos,T-000023-16S-s-P2-pos,T-000023-16S-s-P2-pos,True,False
231,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-000023-ITS-s-P2-pos_S92_L001_R1_001.fastq.gz,T-000023-ITS-s-P2-pos_S92_L001_R2_001.fastq.gz,T-2023-ITS-s-P2-pos,T-000023-ITS-s-P2-pos,T-000023-ITS-s-P2-pos,True,False
110,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-000023-16S-s-P2-neg_S109_L001_R1_001.fastq.gz,T-000023-16S-s-P2-neg_S109_L001_R2_001.fastq.gz,T-2023-16S-s-P2-neg,T-000023-16S-s-P2-neg,T-000023-16S-s-P2-neg,True,False
92,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-000023-16S-s-P1-neg_S92_L001_R1_001.fastq.gz,T-000023-16S-s-P1-neg_S92_L001_R2_001.fastq.gz,T-2023-16S-s-P1-neg,T-000023-16S-s-P1-neg,T-000023-16S-s-P1-neg,True,False
93,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-000023-16S-s-P1-pos_S93_L001_R1_001.fastq.gz,T-000023-16S-s-P1-pos_S93_L001_R2_001.fastq.gz,T-2023-16S-s-P1-pos,T-000023-16S-s-P1-pos,T-000023-16S-s-P1-pos,True,False

In [ ]:
filtered_metadata_2023_washed_shotgun_amplicon_full=metadata_2023_washed_shotgun_amplicon_full[
    metadata_2023_washed_shotgun_amplicon_full.apply(
        lambda row: row['amplicon'] not in row['suggested_correct_seq_sample_ID'], axis=1)]
filtered_metadata_2023_washed_shotgun_amplicon_full

Empty DataFrame
Columns: [bio_sample_ID, sample_date, sample_type, block, plot, subplot, ID_on_field , spray, fertilizer, cultivar, density, x, y, harvest_date, yield_grain, yield_straw, yield_TGW, sample_weight_g, washed_date, DNA_ext_date, days_between_DNA_x, DNA_conc_individual, speedvac_DNA_conc_individual, amplicon, lib_plate_number, plate_position, PCR1_date, PCR2_date, lib_DNA_conc, index_set, S5_index_ID, S5_index, N7_index_ID, N7_index, index_pair, seq_sample_ID, run_ID, note, YEAR, LEAF_PROTOCOL, LIBRARY_PREPARATION, Unnamed: 0, dir_name, full_path, forward_fq, reverse_fq, corrected_forward_fq, corrected_reverse_fq, current_seq_sample_ID, correct_seq_sample_ID, suggested_correct_seq_sample_ID, SUGGESTED_EQUALS_CORRECT, ALREADY_CORRECT]
Index: []

[0 rows x 53 columns]

## Shotgun 2023

In [ ]:
# metadata_2023_washed_shotgun[metadata_2023_washed_shotgun["run_ID"]=="RISO2"]
# metadata_2023_washed_shotgun["run_ID"]=metadata_2023_washed_shotgun["run_ID"].str.replace("RIS2", "RISO2")
print("Number of samples: "  + str(len(metadata_2023_washed_shotgun)))
print("Number of sequence runs: "  + str(metadata_2023_washed_shotgun["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2023_washed_shotgun["run_ID"].value_counts()

Number of samples: 299
Number of sequence runs: 299

Number of sequence runs per folder:

run_ID
seq240515_E8KTD    291
seq240222_RQS8X      8
Name: count, dtype: int64

In [ ]:
metadata_2023_washed_shotgun_full=metadata_2023_washed_shotgun.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2023_washed_shotgun_full=metadata_2023_washed_shotgun_full[metadata_2023_washed_shotgun_full["seq_sample_ID"].notna()]

if 'correct_seq_sample_ID' not in metadata_2023_washed_shotgun_full.columns:
    metadata_2023_washed_shotgun_full['correct_seq_sample_ID'] = np.nan
    
metadata_2023_washed_shotgun_full['suggested_correct_seq_sample_ID'] = \
    metadata_2023_washed_shotgun_full['correct_seq_sample_ID'].fillna(metadata_2023_washed_shotgun_full['seq_sample_ID'])
metadata_2023_washed_shotgun_full['suggested_correct_seq_sample_ID'] = metadata_2023_washed_shotgun_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "")
metadata_2023_washed_shotgun_full=metadata_2023_washed_shotgun_full.sort_values("run_ID")

metadata_2023_washed_shotgun_full

,bio_sample_ID,sample_date,sample_type,block,plot,subplot,ID_on_field,spray,fertilizer,cultivar,...,run_ID,note,correct_seq_sample_ID,YEAR,LEAF_PROTOCOL,LIBRARY_PREPARATION,Unnamed: 0,dir_name,full_path,suggested_correct_seq_sample_ID
298,T-210623-aphid-107D,2023-06-21,timeline,3.0,107,9.0,NaN,NaN,Normal,sheriff,...,seq240222_RQS8X,NaN,NaN,2023,WASHED,shotgun,2,seq240222_RQS8X,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-107D
291,T-210623-aphid-3-61D,2023-06-21,timeline,NaN,3_61,NaN,NaN,NaN,Normal,heerup,...,seq240222_RQS8X,mix_of_sample_3_and_6_pooled_after_centrifugat...,NaN,2023,WASHED,shotgun,2,seq240222_RQS8X,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-3-61D
292,T-210623-aphid-5-68D,2023-06-21,timeline,NaN,5_68,NaN,NaN,NaN,Normal,sheriff,...,seq240222_RQS8X,mix_of_sample_5_and_68_hole_in_beaker_lost_20ml,NaN,2023,WASHED,shotgun,2,seq240222_RQS8X,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-5-68D
293,T-210623-aphid-66D,2023-06-21,timeline,2.0,66,6.0,NaN,NaN,Normal,kvium,...,seq240222_RQS8X,NaN,NaN,2023,WASHED,shotgun,2,seq240222_RQS8X,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-66D
297,T-210623-aphid-104D,2023-06-21,timeline,3.0,104,9.0,NaN,NaN,Normal,kvium,...,seq240222_RQS8X,NaN,NaN,2023,WASHED,shotgun,2,seq240222_RQS8X,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-104D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,T-130623-80C,2023-06-13,timeline,3.0,80,7.0,NaN,NaN,Half,heerup,...,seq240515_E8KTD,NaN,NaN,2023,WASHED,shotgun,21,seq240515_E8KTD,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-130623-s-80C
96,T-130623-75C,2023-06-13,timeline,3.0,75,7.0,NaN,NaN,Half,sheriff,...,seq240515_E8KTD,NaN,NaN,2023,WASHED,shotgun,21,seq240515_E8KTD,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-130623-s-75C
95,T-130623-72C,2023-06-13,timeline,2.0,72,6.0,NaN,NaN,Normal,rembrandt,...,seq240515_E8KTD,NaN,NaN,2023,WASHED,shotgun,21,seq240515_E8KTD,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-130623-s-72C
93,T-130623-66C,2023-06-13,timeline,2.0,66,6.0,NaN,NaN,Normal,kvium,...,seq240515_E8KTD,NaN,NaN,2023,WASHED,shotgun,21,seq240515_E8KTD,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-130623-s-66C
149,T-270623-18E,2023-06-27,timeline,1.0,18,2.0,NaN,NaN,Half,heerup,...,seq240515_E8KTD,NaN,NaN,2023,WASHED,shotgun,21,seq240515_E8KTD,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-270623-s-18E

In [ ]:
# Iterate over each row and print files
metadata_2023_washed_shotgun_full["forward_fq"]=""
metadata_2023_washed_shotgun_full["reverse_fq"]=""
metadata_2023_washed_shotgun_full["current_seq_sample_ID"]=""
metadata_2023_washed_shotgun_full["corrected_forward_fq"]=""
metadata_2023_washed_shotgun_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2023_washed_shotgun_full)  # Get the total number of rows

for index, row in metadata_2023_washed_shotgun_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        if len(matching_files) == 2:
            metadata_2023_washed_shotgun_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2023_washed_shotgun_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2023_washed_shotgun_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2023_washed_shotgun_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2023_washed_shotgun_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2


        if len(matching_files) >2:

            # print(correct_seq_sample_ID)
            
            grouped_files = defaultdict(list)
            
            # Loop over each file and group by the part before R1/R2
            for file in matching_files:
                # Split the file name at R1 or R2
                base_name = file.split("/")[-1].rsplit("_R", 1)[0]  # Split from the last occurrence of "_R"
                grouped_files[base_name].append(file.split("/")[-1])
            
            metadata_2023_washed_shotgun_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", grouped_files[base_name][0].split("/")[-1])[0]
     
            
            # Print the grouped files
            m=0
            for base_name, files in grouped_files.items():      
                if len(files)==2:
            
                    if m==0:
                        # print(grouped_files[base_name][0])
                        metadata_2023_washed_shotgun_full.loc[index, "forward_fq"] = [grouped_files[base_name][0]]
                        metadata_2023_washed_shotgun_full.loc[index, "reverse_fq"] = [grouped_files[base_name][1]]
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2023_washed_shotgun_full.loc[index, "corrected_forward_fq"] = [correct_seq_sample_ID + ending_R1]
                        metadata_2023_washed_shotgun_full.loc[index, "corrected_reverse_fq"] = [correct_seq_sample_ID + ending_R2]
            
            
                    else:
                        metadata_2023_washed_shotgun_full.loc[index, "forward_fq"].append(grouped_files[base_name][0])
                        metadata_2023_washed_shotgun_full.loc[index, "reverse_fq"].append(grouped_files[base_name][1])
                        ending_R1= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][0].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][0])[1]
                        ending_R2= "_S" + re.search(r"_S(\d+)", grouped_files[base_name][1].split("/")[-1]).group(1) + re.split(r"_S\d+", grouped_files[base_name][1])[1]
                        metadata_2023_washed_shotgun_full.loc[index, "corrected_forward_fq"].append(correct_seq_sample_ID + ending_R1)
                        metadata_2023_washed_shotgun_full.loc[index, "corrected_reverse_fq"].append(correct_seq_sample_ID + ending_R2)
            
                
                    m=m+1
                else:
                    print("ERROR", base_name, files)

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1
    
# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

Processing... 100.00% complete
Processing complete!

In [ ]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2023_washed_shotgun_full = metadata_2023_washed_shotgun_full[
    [col for col in metadata_2023_washed_shotgun_full.columns if col not in columns_to_move] + columns_to_move
]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2023_washed_shotgun_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2023_washed_shotgun_full["suggested_correct_seq_sample_ID"] == metadata_2023_washed_shotgun_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2023_washed_shotgun_full["ALREADY_CORRECT"] = metadata_2023_washed_shotgun_full["suggested_correct_seq_sample_ID"] == metadata_2023_washed_shotgun_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2023_washed_shotgun_full = metadata_2023_washed_shotgun_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2023_washed_shotgun_full

/tmp/ipykernel_3922490/1254514943.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_2023_washed_shotgun_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2023_washed_shotgun_full["suggested_correct_seq_sample_ID"] == metadata_2023_washed_shotgun_full["correct_seq_sample_ID"]
/tmp/ipykernel_3922490/1254514943.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_2023_washed_shotgun_full["ALREADY_CORRECT"] = metadata_2023_washed_shotgun_full["suggested_correct_seq_sample_ID"] == metadata_2023_washed_shotgun_full["current_seq_sample_ID"]

,bio_sample_ID,sample_date,sample_type,block,plot,subplot,ID_on_field,spray,fertilizer,cultivar,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
298,T-210623-aphid-107D,2023-06-21,timeline,3.0,107,9.0,NaN,NaN,Normal,sheriff,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-107D_S160_L001_R1_001.fastq.gz,T-210623-s-aphid-107D_S160_L001_R2_001.fastq.gz,T-210623-s-aphid-107D,NaN,T-210623-s-aphid-107D,False,True
291,T-210623-aphid-3-61D,2023-06-21,timeline,NaN,3_61,NaN,NaN,NaN,Normal,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-3-61D_S153_L001_R1_001.fastq.gz,T-210623-s-aphid-3-61D_S153_L001_R2_001.fastq.gz,T-210623-s-aphid-3-61D,NaN,T-210623-s-aphid-3-61D,False,True
292,T-210623-aphid-5-68D,2023-06-21,timeline,NaN,5_68,NaN,NaN,NaN,Normal,sheriff,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-5-68D_S154_L001_R1_001.fastq.gz,T-210623-s-aphid-5-68D_S154_L001_R2_001.fastq.gz,T-210623-s-aphid-5-68D,NaN,T-210623-s-aphid-5-68D,False,True
293,T-210623-aphid-66D,2023-06-21,timeline,2.0,66,6.0,NaN,NaN,Normal,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-66D_S155_L001_R1_001.fastq.gz,T-210623-s-aphid-66D_S155_L001_R2_001.fastq.gz,T-210623-s-aphid-66D,NaN,T-210623-s-aphid-66D,False,True
297,T-210623-aphid-104D,2023-06-21,timeline,3.0,104,9.0,NaN,NaN,Normal,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-210623-s-aphid-104D_S159_L001_R1_001.fastq.gz,T-210623-s-aphid-104D_S159_L001_R2_001.fastq.gz,T-210623-s-aphid-104D,NaN,T-210623-s-aphid-104D,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,T-130623-66C,2023-06-13,timeline,2.0,66,6.0,NaN,NaN,Normal,kvium,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[T-130623-s-66C_S248_L001_R1_001.fastq.gz, T-1...","[T-130623-s-66C_S248_L001_R2_001.fastq.gz, T-1...","[T-130623-s-66C_S248_L001_R1_001.fastq.gz, T-1...","[T-130623-s-66C_S248_L001_R2_001.fastq.gz, T-1...",T-130623-s-66C,NaN,T-130623-s-66C,False,True
149,T-270623-18E,2023-06-27,timeline,1.0,18,2.0,NaN,NaN,Half,heerup,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[T-270623-s-18E_S127_L001_R1_001.fastq.gz, T-2...","[T-270623-s-18E_S127_L001_R2_001.fastq.gz, T-2...","[T-270623-s-18E_S127_L001_R1_001.fastq.gz, T-2...","[T-270623-s-18E_S127_L001_R2_001.fastq.gz, T-2...",T-270623-s-18E,NaN,T-270623-s-18E,False,True
290,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,"[shotgun-hug-p4-neg_S291_L001_R1_001.fastq.gz,...","[shotgun-hug-p4-neg_S291_L001_R2_001.fastq.gz,...",[T-000023-s-hug-P4-neg_S291_L001_R1_001.fastq....,[T-000023-s-hug-P4-neg_S291_L001_R2_001.fastq....,shotgun-hug-p4-neg,T-000023-s-hug-P4-neg,T-000023-s-hug-P4-neg,True,False
289,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,[shotgun-std15-P3-neg_S259_L001_R1_001.fastq.g...,[shotgun-std15-P3-neg_S259_L001_R2_001.fastq.g...,[T-000023-s-nex15-P3-neg_S259_L001_R1_001.fast...,[T-000023-s-nex15-P3-neg_S259_L001_R2_001.fast...,shotgun-std15-P3-neg,T-000023-s-nex15-P3-neg,T-000023-s-nex15-P3-neg,True,False
288,Ultrapure-water,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,[shotgun-std15-P2-neg_S171_L001_R1_001.fastq.g...,[shotgun-std15-P2-neg_S171_L001_R2_001.fastq.g...,[T-000023-s-nex15-P2-neg_S171_L001_R1_001.fast...,[T-000023-s-nex15-P2-neg_S171_L001_R2_001.fast...,shotgun-std15-P2-neg,T-000023-s-nex15-P2-neg,T-000023-s-nex15-P2-neg,True,False

## CRUSHED 2023 ITS

In [ ]:
# metadata_2023_crushed_amplicon_ITS[metadata_2023_crushed_amplicon_ITS["run_ID"]=="RISO2"]
# metadata_2023_crushed_amplicon_ITS["run_ID"]=metadata_2023_crushed_amplicon_ITS["run_ID"].str.replace("RIS2", "RISO2")
print("Number of samples: "  + str(len(metadata_2023_crushed_amplicon_ITS)))
print("Number of sequence runs: "  + str(metadata_2023_crushed_amplicon_ITS["run_ID"].value_counts().sum()))
print()
print("Number of sequence runs per folder: ")
metadata_2023_crushed_amplicon_ITS["run_ID"].value_counts()

Number of samples: 628
Number of sequence runs: 585

Number of sequence runs per folder:

run_ID
seq240826_X6DU5    188
seq240719_NR8NI    162
seq240820_C6WGP    142
seq240710_DR8PG     93
Name: count, dtype: int64

In [ ]:
metadata_2023_crushed_amplicon_ITS_full=metadata_2023_crushed_amplicon_ITS.merge(df_folder_structure, left_on="run_ID", right_on="dir_name", how="left")
metadata_2023_crushed_amplicon_ITS_full=metadata_2023_crushed_amplicon_ITS_full[metadata_2023_crushed_amplicon_ITS_full["seq_sample_ID"].notna()]
metadata_2023_crushed_amplicon_ITS_full['suggested_correct_seq_sample_ID'] = \
    metadata_2023_crushed_amplicon_ITS_full['correct_seq_sample_ID'].fillna(metadata_2023_crushed_amplicon_ITS_full['seq_sample_ID'])
metadata_2023_crushed_amplicon_ITS_full['suggested_correct_seq_sample_ID'] = metadata_2023_crushed_amplicon_ITS_full['suggested_correct_seq_sample_ID'].str.replace("_", "-").str.replace("crushed-1-", "").str.replace("16s", "16S")
metadata_2023_crushed_amplicon_ITS_full=metadata_2023_crushed_amplicon_ITS_full.sort_values("run_ID")
metadata_2023_crushed_amplicon_ITS_full = metadata_2023_crushed_amplicon_ITS_full.dropna(axis=1, how='all')

In [ ]:


# Iterate over each row and print files
metadata_2023_crushed_amplicon_ITS_full["forward_fq"]=""
metadata_2023_crushed_amplicon_ITS_full["reverse_fq"]=""
metadata_2023_crushed_amplicon_ITS_full["current_seq_sample_ID"]=""
metadata_2023_crushed_amplicon_ITS_full["corrected_forward_fq"]=""
metadata_2023_crushed_amplicon_ITS_full["corrected_reverse_fq"]=""
n=0
total_rows = len(metadata_2023_crushed_amplicon_ITS_full)  # Get the total number of rows

for index, row in metadata_2023_crushed_amplicon_ITS_full.iterrows():
    try:
        folder_path = row['full_path']  # Get the folder path
        prefix = row['seq_sample_ID'] + "_"  # Get the prefix from the column
        matching_files = list_files_with_prefix(folder_path, prefix)
        correct_seq_sample_ID= row['suggested_correct_seq_sample_ID']

        # Check if the number of matching files is not equal to 2
        if len(matching_files) == 2:
            metadata_2023_crushed_amplicon_ITS_full.loc[index, "forward_fq"] = matching_files[0]
            metadata_2023_crushed_amplicon_ITS_full.loc[index, "reverse_fq"] = matching_files[1]
            ending_R1= "_S" + re.search(r"_S(\d+)", matching_files[0].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[0])[1]
            ending_R2= "_S" + re.search(r"_S(\d+)", matching_files[1].split("/")[-1]).group(1) + re.split(r"_S\d+", matching_files[1])[1]
            metadata_2023_crushed_amplicon_ITS_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files[0].split("/")[-1])[0]
            metadata_2023_crushed_amplicon_ITS_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + ending_R1
            metadata_2023_crushed_amplicon_ITS_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + ending_R2

        # else:
        #     # prefix2=prefix.replace("crushed-1-", "").replace("-", "_")
        #     prefix2=prefix.replace("washed-1-", "")#.replace("-", "_")
        #     matching_files2 = list_files_with_prefix(folder_path, prefix2)
    
        #     if len(matching_files2) == 2:
        #         metadata_2023_crushed_amplicon_ITS_full.loc[index, "forward_fq"] = matching_files2[0]
        #         metadata_2023_crushed_amplicon_ITS_full.loc[index, "reverse_fq"] = matching_files2[1]
        #         metadata_2023_crushed_amplicon_ITS_full.loc[index, "current_seq_sample_ID"] = re.split(r"_S\d+", matching_files2[0].split("/")[-1])[0]
        #         metadata_2023_crushed_amplicon_ITS_full.loc[index, "corrected_forward_fq"] = correct_seq_sample_ID + "_S" + re.split(r"_S\d+", matching_files2[0])[1]
        #         metadata_2023_crushed_amplicon_ITS_full.loc[index, "corrected_reverse_fq"] = correct_seq_sample_ID + "_S" + re.split(r"_S\d+", matching_files2[1])[1]
        #     else:
        #         print(f"Files in {folder_path} containing {prefix2}:")
            
            # print(correct_seq_sample_ID)
            # print(prefix)
            # print()

        #         print(f" - {prefix}")
        #         print(f" - {matching_files}")

    except Exception as e:
        # Print the error and the problematic row
        print(f"Error occurred for row {index}: {row}")
        print(f"Error details: {e}")

    # Print the percentage of completion
    percent_complete = (n + 1) / total_rows * 100
    print(f"Processing... {percent_complete:.2f}% complete", end="\r")
    n=n+1

# After the loop, print 100% to indicate completion
print("\nProcessing complete!")
# crushed-1 SAMPLES, what to to with "correct_seq_sample_ID

Processing... 100.00% complete
Processing complete!

In [ ]:
columns_to_move=["current_seq_sample_ID","correct_seq_sample_ID", "suggested_correct_seq_sample_ID"]
# Reorder the DataFrame so that the specified columns are moved to the end
metadata_2023_crushed_amplicon_ITS_full = metadata_2023_crushed_amplicon_ITS_full[
    [col for col in metadata_2023_crushed_amplicon_ITS_full.columns if col not in columns_to_move] + columns_to_move
]

# Extract only the file names from the 'forward_fq' column (removes the path)
metadata_2023_crushed_amplicon_ITS_full['forward_fq'] = metadata_2023_crushed_amplicon_ITS_full['forward_fq'].str.split("/").str[-1]

# Extract only the file names from the 'reverse_fq' column (removes the path)
metadata_2023_crushed_amplicon_ITS_full['reverse_fq'] = metadata_2023_crushed_amplicon_ITS_full['reverse_fq'].str.split("/").str[-1]

# Create a new column "SUGGESTED_EQUALS_CORRECT" that is True if the suggested correct seq_sample_ID equals the correct seq_sample_ID
metadata_2023_crushed_amplicon_ITS_full["SUGGESTED_EQUALS_CORRECT"] = metadata_2023_crushed_amplicon_ITS_full["suggested_correct_seq_sample_ID"] == metadata_2023_crushed_amplicon_ITS_full["correct_seq_sample_ID"]

# Create a new column "ALREADY_CORRECT" that is True if the suggested correct seq_sample_ID equals the current seq_sample_ID
metadata_2023_crushed_amplicon_ITS_full["ALREADY_CORRECT"] = metadata_2023_crushed_amplicon_ITS_full["suggested_correct_seq_sample_ID"] == metadata_2023_crushed_amplicon_ITS_full["current_seq_sample_ID"]

# Sort the DataFrame by "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" columns
# The rows with "True" for "SUGGESTED_EQUALS_CORRECT" and "ALREADY_CORRECT" will come first
metadata_2023_crushed_amplicon_ITS_full = metadata_2023_crushed_amplicon_ITS_full.sort_values(["SUGGESTED_EQUALS_CORRECT", "ALREADY_CORRECT"])
metadata_2023_crushed_amplicon_ITS_full

,bio_sample_ID,vila_ID,sample_number,sample_date,sample_type,block,plot,subplot,spray_fungicide,fertiliser,...,full_path,forward_fq,reverse_fq,corrected_forward_fq,corrected_reverse_fq,current_seq_sample_ID,correct_seq_sample_ID,suggested_correct_seq_sample_ID,SUGGESTED_EQUALS_CORRECT,ALREADY_CORRECT
110,T-300523-c-3A-1,1.0,3.0,2023-05-30,timeline,1.0,3.0,1.0,n,Normal,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-300523-ITS-c-3A-1_S17_L001_R1_001.fastq.gz,T-300523-ITS-c-3A-1_S17_L001_R2_001.fastq.gz,T-300523-ITS-c-3A-1_S17_L001_R1_001.fastq.gz,T-300523-ITS-c-3A-1_S17_L001_R2_001.fastq.gz,T-300523-ITS-c-3A-1,NaN,T-300523-ITS-c-3A-1,False,True
141,T-300523-c-91A-1,32.0,91.0,2023-05-30,timeline,3.0,91.0,8.0,n,Zero,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-300523-ITS-c-91A-1_S36_L001_R1_001.fastq.gz,T-300523-ITS-c-91A-1_S36_L001_R2_001.fastq.gz,T-300523-ITS-c-91A-1_S36_L001_R1_001.fastq.gz,T-300523-ITS-c-91A-1_S36_L001_R2_001.fastq.gz,T-300523-ITS-c-91A-1,NaN,T-300523-ITS-c-91A-1,False,True
142,T-300523-c-98A-1,33.0,98.0,2023-05-30,timeline,3.0,98.0,9.0,n,Normal,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-300523-ITS-c-98A-1_S37_L001_R1_001.fastq.gz,T-300523-ITS-c-98A-1_S37_L001_R2_001.fastq.gz,T-300523-ITS-c-98A-1_S37_L001_R1_001.fastq.gz,T-300523-ITS-c-98A-1_S37_L001_R2_001.fastq.gz,T-300523-ITS-c-98A-1,NaN,T-300523-ITS-c-98A-1,False,True
143,T-300523-c-100A-1,34.0,100.0,2023-05-30,timeline,3.0,100.0,9.0,n,Normal,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-300523-ITS-c-100A-1_S38_L001_R1_001.fastq.gz,T-300523-ITS-c-100A-1_S38_L001_R2_001.fastq.gz,T-300523-ITS-c-100A-1_S38_L001_R1_001.fastq.gz,T-300523-ITS-c-100A-1_S38_L001_R2_001.fastq.gz,T-300523-ITS-c-100A-1,NaN,T-300523-ITS-c-100A-1,False,True
144,T-300523-c-104A-1,35.0,104.0,2023-05-30,timeline,3.0,104.0,9.0,n,Normal,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-300523-ITS-c-104A-1_S39_L001_R1_001.fastq.gz,T-300523-ITS-c-104A-1_S39_L001_R2_001.fastq.gz,T-300523-ITS-c-104A-1_S39_L001_R1_001.fastq.gz,T-300523-ITS-c-104A-1_S39_L001_R2_001.fastq.gz,T-300523-ITS-c-104A-1,NaN,T-300523-ITS-c-104A-1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-ITS-c-redo-neg_S47_L001_R1_001.fastq.gz,T-2023-ITS-c-redo-neg_S47_L001_R2_001.fastq.gz,T-000023-ITS-c-redo-neg_S47_L001_R1_001.fastq.gz,T-000023-ITS-c-redo-neg_S47_L001_R2_001.fastq.gz,T-2023-ITS-c-redo-neg,T-000023-ITS-c-redo-neg,T-000023-ITS-c-redo-neg,True,False
92,Ultrapure-water,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-ITS-c-P1-neg_S93_L001_R1_001.fastq.gz,T-2023-ITS-c-P1-neg_S93_L001_R2_001.fastq.gz,T-000023-ITS-c-P1-neg_S93_L001_R1_001.fastq.gz,T-000023-ITS-c-P1-neg_S93_L001_R2_001.fastq.gz,T-2023-ITS-c-P1-neg,T-000023-ITS-c-P1-neg,T-000023-ITS-c-P1-neg,True,False
93,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-ITS-c-P1-pos_S94_L001_R1_001.fastq.gz,T-2023-ITS-c-P1-pos_S94_L001_R2_001.fastq.gz,T-000023-ITS-c-P1-pos_S94_L001_R1_001.fastq.gz,T-000023-ITS-c-P1-pos_S94_L001_R2_001.fastq.gz,T-2023-ITS-c-P1-pos,T-000023-ITS-c-P1-pos,T-000023-ITS-c-P1-pos,True,False
477,Ultrapure-water,NaN,NaN,NaT,timeline,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-ITS-c-P5-neg_S95_L001_R1_001.fastq.gz,T-2023-ITS-c-P5-neg_S95_L001_R2_001.fastq.gz,T-000023-ITS-c-P5-neg_S95_L001_R1_001.fastq.gz,T-000023-ITS-c-P5-neg_S95_L001_R2_001.fastq.gz,T-2023-ITS-c-P5-neg,T-000023-ITS-c-P5-neg,T-000023-ITS-c-P5-neg,True,False
478,ZymoBIOMICS-Microbial-Community-DNA-Standard-D...,NaN,NaN,NaT,timeline,NaN,NaN,NaN,NaN,NaN,...,/home/jovyan/work/CCRP/MATRIX/RawData/Microbio...,T-2023-ITS-c-P5-pos_S96_L001_R1_001.fastq.gz,T-2023-ITS-c-P5-pos_S96_L001_R2_001.fastq.gz,T-000023-ITS-c-P5-pos_S96_L001_R1_001.fastq.gz,T-000023-ITS-c-P5-pos_S96_L001_R2_001.fastq.gz,T-2023-ITS-c-P5-pos,T-000023-ITS-c-P5-pos,T-000023-ITS-c-P5-pos,True,False

In [ ]:
filtered_metadata_2023_crushed_amplicon_ITS_full=metadata_2023_crushed_amplicon_ITS_full[
    metadata_2023_crushed_amplicon_ITS_full.apply(
        lambda row: row['amplicon'] not in row['suggested_correct_seq_sample_ID'], axis=1)]
filtered_metadata_2023_crushed_amplicon_ITS_full

Empty DataFrame
Columns: [bio_sample_ID, vila_ID, sample_number, sample_date, sample_type, block, plot, subplot, spray_fungicide, fertiliser, cultivar, density, harvest_date, sample_weight_plus_minus_2mg, DNA_plate_number, DNA_ext_date, DNA_conc_plate, lib_prep, amplicon, lib_plate_number, plate_position, PCR1_date, PCR2_date, lib_DNA_conc, index_set, S5_index_ID, S5_index, N7_index_ID, N7_index, index_pair, seq_sample_ID, run_ID, note, YEAR, LEAF_PROTOCOL, LIBRARY_PREPARATION, Unnamed: 0, dir_name, full_path, forward_fq, reverse_fq, corrected_forward_fq, corrected_reverse_fq, current_seq_sample_ID, correct_seq_sample_ID, suggested_correct_seq_sample_ID, SUGGESTED_EQUALS_CORRECT, ALREADY_CORRECT]
Index: []

[0 rows x 48 columns]

In [ ]:
# metadata_control_crushed_amplicon_full.to_csv("metadata_control_crushed_amplicon.csv", index=False)
# metadata_2022_washed_shotgun_amplicon_full.to_csv("metadata_2022_washed_shotgun_amplicon.csv", index=False)
# metadata_2022_washed_shotgun_full.to_csv("metadata_2022_washed_shotgun.csv", index=False)
# metadata_2023_washed_shotgun_amplicon_full.to_csv("metadata_2023_washed_shotgun_amplicon.csv", index=False)
# metadata_2023_washed_shotgun_full.to_csv("metadata_2023_washed_shotgun.csv", index=False)
# metadata_2020_washed_amplicon_full.to_csv("metadata_2020_washed_amplicon.csv", index=False)
# metadata_2022_washed_amplicon_full.to_csv("metadata_2022_washed_amplicon.csv", index=False)
# metadata_2021_crushed_amplicon_full.to_csv("metadata_2021_crushed_amplicon.csv", index=False)
# metadata_2022_crushed_amplicon_full.to_csv("metadata_2022_crushed_amplicon.csv", index=False)
# metadata_2023_crushed_amplicon_16S_full.to_csv("metadata_2023_crushed_amplicon_16S.csv", index=False)
# metadata_2023_crushed_amplicon_ITS_full.to_csv("metadata_2023_crushed_amplicon_ITS.csv", index=False)